/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { AuthSubRestErrorResponseforplanner } from '../models/authSubRestErrorResponseforplanner.js';

/**
 * Creates an instance of AuthRestErrorResponseforplanner
 */
interface AuthRestErrorResponseforplanner {
  fault?: AuthSubRestErrorResponseforplanner;
}

export class AuthRestErrorResponseforplannerError extends ApiError<
  AuthRestErrorResponseforplanner
> {}
