/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of ErrorResponse
 */
interface ErrorResponse {
  responseCode?: string;
  message?: string;
}

export class ErrorResponseError extends ApiError<ErrorResponse> {}
