/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of M404Management
 */
interface M404Management {
  error?: string;
  error_description?: string;
  cause?: string;
}

export class M404ManagementError extends ApiError<M404Management> {}
