/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of M500Management
 */
interface M500Management {
  error?: string;
  error_description?: string;
  cause?: string;
}

export class M500ManagementError extends ApiError<M500Management> {}
