/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of Response
 */
interface Response {
  /** The short summary of the error */
  error: string;
  /** The detailed description of the error */
  description: string;
}

export class ResponseError extends ApiError<Response> {}
