/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of RestErrorResponseforplanner
 */
interface RestErrorResponseforplanner {
  errorCode?: string;
  errorMessage?: string;
  errorUrl?: string;
}

export class RestErrorResponseforplannerError extends ApiError<
  RestErrorResponseforplanner
> {}
