/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of RuleRestErrorResponse
 */
interface RuleRestErrorResponse {
  errorCode?: string;
  errorMessage?: string;
}

export class RuleRestErrorResponseError extends ApiError<
  RuleRestErrorResponse
> {}
