/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  anyOf,
  isMappedValueValidForSchema,
  lazy,
  Schema,
} from '../../schema.js';
import {
  ConditionObjectCall,
  conditionObjectCallSchema,
} from '../conditionObjectCall.js';
import {
  ConditionTypeEnum,
  conditionTypeEnumSchema,
} from '../conditionTypeEnum.js';

/** This is a container type for any-of types. */
export type AccountLevelObjectCondition =
  | ConditionTypeEnum
  | ConditionObjectCall;

export const accountLevelObjectConditionSchema: Schema<AccountLevelObjectCondition> = lazy(
  () => anyOf([conditionTypeEnumSchema, conditionObjectCallSchema])
);

export namespace AccountLevelObjectCondition {
  /**
   * Validation method to narrow down union type to ConditionTypeEnum type case.
   *
   * This is conditionType case.
   */
  export function isConditionTypeEnum(
    value: unknown
  ): value is ConditionTypeEnum {
    return isMappedValueValidForSchema(value, conditionTypeEnumSchema);
  }

  /**
   * Validation method to narrow down union type to ConditionObjectCall type case.
   *
   * This is conditionObjectCall case.
   */
  export function isConditionObjectCall(
    value: unknown
  ): value is ConditionObjectCall {
    return isMappedValueValidForSchema(value, conditionObjectCallSchema);
  }
}
