/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  isMappedValueValidForSchema,
  lazy,
  oneOf,
  Schema,
} from '../../schema.js';
import {
  AccidentCauseCode,
  accidentCauseCodeSchema,
} from '../accidentCauseCode.js';
import {
  EmergencyVehicleApproachingCauseCode,
  emergencyVehicleApproachingCauseCodeSchema,
} from '../emergencyVehicleApproachingCauseCode.js';
import {
  ImpassabilityCauseCode,
  impassabilityCauseCodeSchema,
} from '../impassabilityCauseCode.js';
import {
  RoadworksCauseCode,
  roadworksCauseCodeSchema,
} from '../roadworksCauseCode.js';
import {
  TrafficConditionCauseCode,
  trafficConditionCauseCodeSchema,
} from '../trafficConditionCauseCode.js';
import {
  WrongWayDrivingCauseCode,
  wrongWayDrivingCauseCodeSchema,
} from '../wrongWayDrivingCauseCode.js';

/** This is a container type for one-of types. */
export type CauseCodeChoice =
  | TrafficConditionCauseCode
  | AccidentCauseCode
  | RoadworksCauseCode
  | ImpassabilityCauseCode
  | WrongWayDrivingCauseCode
  | EmergencyVehicleApproachingCauseCode;

export const causeCodeChoiceSchema: Schema<CauseCodeChoice> = lazy(() =>
  oneOf([
    trafficConditionCauseCodeSchema,
    accidentCauseCodeSchema,
    roadworksCauseCodeSchema,
    impassabilityCauseCodeSchema,
    wrongWayDrivingCauseCodeSchema,
    emergencyVehicleApproachingCauseCodeSchema,
  ])
);

export namespace CauseCodeChoice {
  /**
   * Validation method to narrow down union type to TrafficConditionCauseCode type case.
   *
   * This is TrafficConditionCauseCode case.
   */
  export function isTrafficConditionCauseCode(
    value: unknown
  ): value is TrafficConditionCauseCode {
    return isMappedValueValidForSchema(value, trafficConditionCauseCodeSchema);
  }

  /**
   * Validation method to narrow down union type to AccidentCauseCode type case.
   *
   * This is AccidentCauseCode case.
   */
  export function isAccidentCauseCode(
    value: unknown
  ): value is AccidentCauseCode {
    return isMappedValueValidForSchema(value, accidentCauseCodeSchema);
  }

  /**
   * Validation method to narrow down union type to RoadworksCauseCode type case.
   *
   * This is RoadworksCauseCode case.
   */
  export function isRoadworksCauseCode(
    value: unknown
  ): value is RoadworksCauseCode {
    return isMappedValueValidForSchema(value, roadworksCauseCodeSchema);
  }

  /**
   * Validation method to narrow down union type to ImpassabilityCauseCode type case.
   *
   * This is ImpassabilityCauseCode case.
   */
  export function isImpassabilityCauseCode(
    value: unknown
  ): value is ImpassabilityCauseCode {
    return isMappedValueValidForSchema(value, impassabilityCauseCodeSchema);
  }

  /**
   * Validation method to narrow down union type to WrongWayDrivingCauseCode type case.
   *
   * This is WrongWayDrivingCauseCode case.
   */
  export function isWrongWayDrivingCauseCode(
    value: unknown
  ): value is WrongWayDrivingCauseCode {
    return isMappedValueValidForSchema(value, wrongWayDrivingCauseCodeSchema);
  }

  /**
   * Validation method to narrow down union type to EmergencyVehicleApproachingCauseCode type case.
   *
   * This is EmergencyVehicleApproachingCauseCode case.
   */
  export function isEmergencyVehicleApproachingCauseCode(
    value: unknown
  ): value is EmergencyVehicleApproachingCauseCode {
    return isMappedValueValidForSchema(
      value,
      emergencyVehicleApproachingCauseCodeSchema
    );
  }
}
