/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  anyOf,
  isMappedValueValidForSchema,
  lazy,
  Schema,
} from '../../schema.js';
import {
  ActiveAnomalyIndicator,
  activeAnomalyIndicatorSchema,
} from '../activeAnomalyIndicator.js';
import {
  ActiveTriggerIndicator,
  activeTriggerIndicatorSchema,
} from '../activeTriggerIndicator.js';
import { TriggerType1, triggerType1Schema } from '../triggerType1.js';

/** This is a container type for any-of types. */
export type CreateTriggerRequestOptions2 =
  | TriggerType1
  | ActiveAnomalyIndicator
  | ActiveTriggerIndicator;

export const createTriggerRequestOptions2Schema: Schema<CreateTriggerRequestOptions2> = lazy(
  () =>
    anyOf([
      triggerType1Schema,
      activeAnomalyIndicatorSchema,
      activeTriggerIndicatorSchema,
    ])
);

export namespace CreateTriggerRequestOptions2 {
  /**
   * Validation method to narrow down union type to TriggerType1 type case.
   *
   * This is TriggerType1 case.
   */
  export function isTriggerType1(value: unknown): value is TriggerType1 {
    return isMappedValueValidForSchema(value, triggerType1Schema);
  }

  /**
   * Validation method to narrow down union type to ActiveAnomalyIndicator type case.
   *
   * This is ActiveAnomalyIndicator case.
   */
  export function isActiveAnomalyIndicator(
    value: unknown
  ): value is ActiveAnomalyIndicator {
    return isMappedValueValidForSchema(value, activeAnomalyIndicatorSchema);
  }

  /**
   * Validation method to narrow down union type to ActiveTriggerIndicator type case.
   *
   * This is ActiveTriggerIndicator case.
   */
  export function isActiveTriggerIndicator(
    value: unknown
  ): value is ActiveTriggerIndicator {
    return isMappedValueValidForSchema(value, activeTriggerIndicatorSchema);
  }
}
