/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  anyOf,
  isMappedValueValidForSchema,
  lazy,
  Schema,
} from '../../schema.js';
import {
  AccountGroupShareCreateTriggerRequest,
  accountGroupShareCreateTriggerRequestSchema,
} from '../accountGroupShareCreateTriggerRequest.js';
import {
  AccountLevelCreateTriggerRequest,
  accountLevelCreateTriggerRequestSchema,
} from '../accountLevelCreateTriggerRequest.js';
import {
  AccountLevelObject,
  accountLevelObjectSchema,
} from '../accountLevelObject.js';
import {
  AccountShareCreateTriggerRequest,
  accountShareCreateTriggerRequestSchema,
} from '../accountShareCreateTriggerRequest.js';
import {
  Createtriggerchunk,
  createtriggerchunkSchema,
} from '../createtriggerchunk.js';
import {
  DeviceLevelCreateTriggerRequest,
  deviceLevelCreateTriggerRequestSchema,
} from '../deviceLevelCreateTriggerRequest.js';
import {
  PayAsYouGoCreateTriggerRequest,
  payAsYouGoCreateTriggerRequestSchema,
} from '../payAsYouGoCreateTriggerRequest.js';

/** This is a container type for any-of types. */
export type CreateTriggerRulesBody =
  | AccountLevelCreateTriggerRequest
  | AccountLevelObject
  | DeviceLevelCreateTriggerRequest
  | AccountGroupShareCreateTriggerRequest
  | AccountShareCreateTriggerRequest
  | PayAsYouGoCreateTriggerRequest
  | Createtriggerchunk;

export const createTriggerRulesBodySchema: Schema<CreateTriggerRulesBody> = lazy(
  () =>
    anyOf([
      accountLevelCreateTriggerRequestSchema,
      accountLevelObjectSchema,
      deviceLevelCreateTriggerRequestSchema,
      accountGroupShareCreateTriggerRequestSchema,
      accountShareCreateTriggerRequestSchema,
      payAsYouGoCreateTriggerRequestSchema,
      createtriggerchunkSchema,
    ])
);

export namespace CreateTriggerRulesBody {
  /**
   * Validation method to narrow down union type to AccountLevelCreateTriggerRequest type case.
   *
   * This is accountLevelCreateTriggerRequest case.
   */
  export function isAccountLevelCreateTriggerRequest(
    value: unknown
  ): value is AccountLevelCreateTriggerRequest {
    return isMappedValueValidForSchema(
      value,
      accountLevelCreateTriggerRequestSchema
    );
  }

  /**
   * Validation method to narrow down union type to AccountLevelObject type case.
   *
   * This is accountLevelObject case.
   */
  export function isAccountLevelObject(
    value: unknown
  ): value is AccountLevelObject {
    return isMappedValueValidForSchema(value, accountLevelObjectSchema);
  }

  /**
   * Validation method to narrow down union type to DeviceLevelCreateTriggerRequest type case.
   *
   * This is deviceLevelCreateTriggerRequest case.
   */
  export function isDeviceLevelCreateTriggerRequest(
    value: unknown
  ): value is DeviceLevelCreateTriggerRequest {
    return isMappedValueValidForSchema(
      value,
      deviceLevelCreateTriggerRequestSchema
    );
  }

  /**
   * Validation method to narrow down union type to AccountGroupShareCreateTriggerRequest type case.
   *
   * This is accountGroupShareCreateTriggerRequest case.
   */
  export function isAccountGroupShareCreateTriggerRequest(
    value: unknown
  ): value is AccountGroupShareCreateTriggerRequest {
    return isMappedValueValidForSchema(
      value,
      accountGroupShareCreateTriggerRequestSchema
    );
  }

  /**
   * Validation method to narrow down union type to AccountShareCreateTriggerRequest type case.
   *
   * This is accountShareCreateTriggerRequest case.
   */
  export function isAccountShareCreateTriggerRequest(
    value: unknown
  ): value is AccountShareCreateTriggerRequest {
    return isMappedValueValidForSchema(
      value,
      accountShareCreateTriggerRequestSchema
    );
  }

  /**
   * Validation method to narrow down union type to PayAsYouGoCreateTriggerRequest type case.
   *
   * This is payAsYouGoCreateTriggerRequest case.
   */
  export function isPayAsYouGoCreateTriggerRequest(
    value: unknown
  ): value is PayAsYouGoCreateTriggerRequest {
    return isMappedValueValidForSchema(
      value,
      payAsYouGoCreateTriggerRequestSchema
    );
  }

  /**
   * Validation method to narrow down union type to Createtriggerchunk type case.
   *
   * This is createtriggerchunk case.
   */
  export function isCreatetriggerchunk(
    value: unknown
  ): value is Createtriggerchunk {
    return isMappedValueValidForSchema(value, createtriggerchunkSchema);
  }
}
