/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  isMappedValueValidForSchema,
  lazy,
  oneOf,
  Schema,
} from '../../schema.js';
import {
  FurtherInfoMsgId,
  furtherInfoMsgIdSchema,
} from '../furtherInfoMsgId.js';
import { RoadSignMsgId, roadSignMsgIdSchema } from '../roadSignMsgId.js';

/** This is a container type for one-of types. */
export type DataFrameMsgId = FurtherInfoMsgId | RoadSignMsgId;

export const dataFrameMsgIdSchema: Schema<DataFrameMsgId> = lazy(() =>
  oneOf([furtherInfoMsgIdSchema, roadSignMsgIdSchema])
);

export namespace DataFrameMsgId {
  /**
   * Validation method to narrow down union type to FurtherInfoMsgId type case.
   *
   * This is FurtherInfoMsgId case.
   */
  export function isFurtherInfoMsgId(
    value: unknown
  ): value is FurtherInfoMsgId {
    return isMappedValueValidForSchema(value, furtherInfoMsgIdSchema);
  }

  /**
   * Validation method to narrow down union type to RoadSignMsgId type case.
   *
   * This is RoadSignMsgId case.
   */
  export function isRoadSignMsgId(value: unknown): value is RoadSignMsgId {
    return isMappedValueValidForSchema(value, roadSignMsgIdSchema);
  }
}
