/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  isMappedValueValidForSchema,
  lazy,
  oneOf,
  Schema,
} from '../../schema.js';
import { AdvisoryContent, advisoryContentSchema } from '../advisoryContent.js';
import {
  ExitServiceContent,
  exitServiceContentSchema,
} from '../exitServiceContent.js';
import {
  GenericSignContent,
  genericSignContentSchema,
} from '../genericSignContent.js';
import {
  SpeedLimitContent,
  speedLimitContentSchema,
} from '../speedLimitContent.js';
import { WorkZoneContent, workZoneContentSchema } from '../workZoneContent.js';

/** This is a container type for one-of types. */
export type DataFrameContent =
  | AdvisoryContent
  | WorkZoneContent
  | GenericSignContent
  | SpeedLimitContent
  | ExitServiceContent;

export const dataFrameContentSchema: Schema<DataFrameContent> = lazy(() =>
  oneOf([
    advisoryContentSchema,
    workZoneContentSchema,
    genericSignContentSchema,
    speedLimitContentSchema,
    exitServiceContentSchema,
  ])
);

export namespace DataFrameContent {
  /**
   * Validation method to narrow down union type to AdvisoryContent type case.
   *
   * This is AdvisoryContent case.
   */
  export function isAdvisoryContent(value: unknown): value is AdvisoryContent {
    return isMappedValueValidForSchema(value, advisoryContentSchema);
  }

  /**
   * Validation method to narrow down union type to WorkZoneContent type case.
   *
   * This is WorkZoneContent case.
   */
  export function isWorkZoneContent(value: unknown): value is WorkZoneContent {
    return isMappedValueValidForSchema(value, workZoneContentSchema);
  }

  /**
   * Validation method to narrow down union type to GenericSignContent type case.
   *
   * This is GenericSignContent case.
   */
  export function isGenericSignContent(
    value: unknown
  ): value is GenericSignContent {
    return isMappedValueValidForSchema(value, genericSignContentSchema);
  }

  /**
   * Validation method to narrow down union type to SpeedLimitContent type case.
   *
   * This is SpeedLimitContent case.
   */
  export function isSpeedLimitContent(
    value: unknown
  ): value is SpeedLimitContent {
    return isMappedValueValidForSchema(value, speedLimitContentSchema);
  }

  /**
   * Validation method to narrow down union type to ExitServiceContent type case.
   *
   * This is ExitServiceContent case.
   */
  export function isExitServiceContent(
    value: unknown
  ): value is ExitServiceContent {
    return isMappedValueValidForSchema(value, exitServiceContentSchema);
  }
}
