/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  anyOf,
  isMappedValueValidForSchema,
  lazy,
  Schema,
} from '../../schema.js';
import { DeviceId, deviceIdSchema } from '../deviceId.js';
import {
  PropertyDeviceId,
  propertyDeviceIdSchema,
} from '../propertyDeviceId.js';

/** This is a container type for any-of types. */
export type DeactivateDeviceListIds = DeviceId | PropertyDeviceId;

export const deactivateDeviceListIdsSchema: Schema<DeactivateDeviceListIds> = lazy(
  () => anyOf([deviceIdSchema, propertyDeviceIdSchema])
);

export namespace DeactivateDeviceListIds {
  /**
   * Validation method to narrow down union type to DeviceId type case.
   *
   * This is DeviceId case.
   */
  export function isDeviceId(value: unknown): value is DeviceId {
    return isMappedValueValidForSchema(value, deviceIdSchema);
  }

  /**
   * Validation method to narrow down union type to PropertyDeviceId type case.
   *
   * This is PropertyDeviceId case.
   */
  export function isPropertyDeviceId(
    value: unknown
  ): value is PropertyDeviceId {
    return isMappedValueValidForSchema(value, propertyDeviceIdSchema);
  }
}
