/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  isMappedValueValidForSchema,
  lazy,
  oneOf,
  Schema,
} from '../../schema.js';
import { DeviceId, deviceIdSchema } from '../deviceId.js';

/** This is a container type for one-of types. */
export type DeleteDevicesResultDeviceIds = DeviceId[] | DeviceId;

export const deleteDevicesResultDeviceIdsSchema: Schema<DeleteDevicesResultDeviceIds> = lazy(
  () => oneOf([array(deviceIdSchema), deviceIdSchema])
);

export namespace DeleteDevicesResultDeviceIds {
  /**
   * Validation method to narrow down union type to DeviceId[] type case.
   *
   * This is Array of DeviceId case.
   */
  export function isArrayOfDeviceId(value: unknown): value is DeviceId[] {
    if (!Array.isArray(value)) {
      return false;
    }
    return isMappedValueValidForSchema(value, array(deviceIdSchema));
  }

  /**
   * Validation method to narrow down union type to DeviceId type case.
   *
   * This is DeviceId case.
   */
  export function isDeviceId(value: unknown): value is DeviceId {
    return isMappedValueValidForSchema(value, deviceIdSchema);
  }
}
