/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  isMappedValueValidForSchema,
  lazy,
  oneOf,
  Schema,
} from '../../schema.js';
import {
  DescriptionOfRoadSurfaceAsphaltOrTar,
  descriptionOfRoadSurfaceAsphaltOrTarSchema,
} from '../descriptionOfRoadSurfaceAsphaltOrTar.js';
import {
  DescriptionOfRoadSurfaceCinders,
  descriptionOfRoadSurfaceCindersSchema,
} from '../descriptionOfRoadSurfaceCinders.js';
import {
  DescriptionOfRoadSurfaceGrass,
  descriptionOfRoadSurfaceGrassSchema,
} from '../descriptionOfRoadSurfaceGrass.js';
import {
  DescriptionOfRoadSurfaceGravel,
  descriptionOfRoadSurfaceGravelSchema,
} from '../descriptionOfRoadSurfaceGravel.js';
import {
  DescriptionOfRoadSurfaceIce,
  descriptionOfRoadSurfaceIceSchema,
} from '../descriptionOfRoadSurfaceIce.js';
import {
  DescriptionOfRoadSurfacePortlandCement,
  descriptionOfRoadSurfacePortlandCementSchema,
} from '../descriptionOfRoadSurfacePortlandCement.js';
import {
  DescriptionOfRoadSurfaceRock,
  descriptionOfRoadSurfaceRockSchema,
} from '../descriptionOfRoadSurfaceRock.js';
import {
  DescriptionOfRoadSurfaceSnow,
  descriptionOfRoadSurfaceSnowSchema,
} from '../descriptionOfRoadSurfaceSnow.js';

/** This is a container type for one-of types. */
export type DescriptionOfRoadSurface =
  | DescriptionOfRoadSurfacePortlandCement
  | DescriptionOfRoadSurfaceAsphaltOrTar
  | DescriptionOfRoadSurfaceGravel
  | DescriptionOfRoadSurfaceGrass
  | DescriptionOfRoadSurfaceCinders
  | DescriptionOfRoadSurfaceRock
  | DescriptionOfRoadSurfaceIce
  | DescriptionOfRoadSurfaceSnow;

export const descriptionOfRoadSurfaceSchema: Schema<DescriptionOfRoadSurface> = lazy(
  () =>
    oneOf([
      descriptionOfRoadSurfacePortlandCementSchema,
      descriptionOfRoadSurfaceAsphaltOrTarSchema,
      descriptionOfRoadSurfaceGravelSchema,
      descriptionOfRoadSurfaceGrassSchema,
      descriptionOfRoadSurfaceCindersSchema,
      descriptionOfRoadSurfaceRockSchema,
      descriptionOfRoadSurfaceIceSchema,
      descriptionOfRoadSurfaceSnowSchema,
    ])
);

export namespace DescriptionOfRoadSurface {
  /**
   * Validation method to narrow down union type to DescriptionOfRoadSurfacePortlandCement type case.
   *
   * This is DescriptionOfRoadSurface_PortlandCement case.
   */
  export function isDescriptionOfRoadSurfacePortlandCement(
    value: unknown
  ): value is DescriptionOfRoadSurfacePortlandCement {
    return isMappedValueValidForSchema(
      value,
      descriptionOfRoadSurfacePortlandCementSchema
    );
  }

  /**
   * Validation method to narrow down union type to DescriptionOfRoadSurfaceAsphaltOrTar type case.
   *
   * This is DescriptionOfRoadSurface_AsphaltOrTar case.
   */
  export function isDescriptionOfRoadSurfaceAsphaltOrTar(
    value: unknown
  ): value is DescriptionOfRoadSurfaceAsphaltOrTar {
    return isMappedValueValidForSchema(
      value,
      descriptionOfRoadSurfaceAsphaltOrTarSchema
    );
  }

  /**
   * Validation method to narrow down union type to DescriptionOfRoadSurfaceGravel type case.
   *
   * This is DescriptionOfRoadSurface_Gravel case.
   */
  export function isDescriptionOfRoadSurfaceGravel(
    value: unknown
  ): value is DescriptionOfRoadSurfaceGravel {
    return isMappedValueValidForSchema(
      value,
      descriptionOfRoadSurfaceGravelSchema
    );
  }

  /**
   * Validation method to narrow down union type to DescriptionOfRoadSurfaceGrass type case.
   *
   * This is DescriptionOfRoadSurface_Grass case.
   */
  export function isDescriptionOfRoadSurfaceGrass(
    value: unknown
  ): value is DescriptionOfRoadSurfaceGrass {
    return isMappedValueValidForSchema(
      value,
      descriptionOfRoadSurfaceGrassSchema
    );
  }

  /**
   * Validation method to narrow down union type to DescriptionOfRoadSurfaceCinders type case.
   *
   * This is DescriptionOfRoadSurface_Cinders case.
   */
  export function isDescriptionOfRoadSurfaceCinders(
    value: unknown
  ): value is DescriptionOfRoadSurfaceCinders {
    return isMappedValueValidForSchema(
      value,
      descriptionOfRoadSurfaceCindersSchema
    );
  }

  /**
   * Validation method to narrow down union type to DescriptionOfRoadSurfaceRock type case.
   *
   * This is DescriptionOfRoadSurface_Rock case.
   */
  export function isDescriptionOfRoadSurfaceRock(
    value: unknown
  ): value is DescriptionOfRoadSurfaceRock {
    return isMappedValueValidForSchema(
      value,
      descriptionOfRoadSurfaceRockSchema
    );
  }

  /**
   * Validation method to narrow down union type to DescriptionOfRoadSurfaceIce type case.
   *
   * This is DescriptionOfRoadSurface_Ice case.
   */
  export function isDescriptionOfRoadSurfaceIce(
    value: unknown
  ): value is DescriptionOfRoadSurfaceIce {
    return isMappedValueValidForSchema(
      value,
      descriptionOfRoadSurfaceIceSchema
    );
  }

  /**
   * Validation method to narrow down union type to DescriptionOfRoadSurfaceSnow type case.
   *
   * This is DescriptionOfRoadSurface_Snow case.
   */
  export function isDescriptionOfRoadSurfaceSnow(
    value: unknown
  ): value is DescriptionOfRoadSurfaceSnow {
    return isMappedValueValidForSchema(
      value,
      descriptionOfRoadSurfaceSnowSchema
    );
  }
}
