/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  anyOf,
  isMappedValueValidForSchema,
  lazy,
  Schema,
} from '../../schema.js';
import { DeviceId2, deviceId2Schema } from '../deviceId2.js';
import { ESIMDeviceId, eSIMDeviceIdSchema } from '../eSIMDeviceId.js';

/** This is a container type for any-of types. */
export type DeviceList2Ids = ESIMDeviceId | DeviceId2;

export const deviceList2IdsSchema: Schema<DeviceList2Ids> = lazy(() =>
  anyOf([eSIMDeviceIdSchema, deviceId2Schema])
);

export namespace DeviceList2Ids {
  /**
   * Validation method to narrow down union type to ESIMDeviceId type case.
   *
   * This is eSIMDeviceId case.
   */
  export function isESIMDeviceId(value: unknown): value is ESIMDeviceId {
    return isMappedValueValidForSchema(value, eSIMDeviceIdSchema);
  }

  /**
   * Validation method to narrow down union type to DeviceId2 type case.
   *
   * This is DeviceId2 case.
   */
  export function isDeviceId2(value: unknown): value is DeviceId2 {
    return isMappedValueValidForSchema(value, deviceId2Schema);
  }
}
