/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  isMappedValueValidForSchema,
  lazy,
  oneOf,
  Schema,
} from '../../schema.js';
import { DevicesFilter, devicesFilterSchema } from '../devicesFilter.js';
import {
  PaginationFilter,
  paginationFilterSchema,
} from '../paginationFilter.js';

/** This is a container type for one-of types. */
export type DevicesRequestFilter = DevicesFilter | PaginationFilter;

export const devicesRequestFilterSchema: Schema<DevicesRequestFilter> = lazy(
  () => oneOf([devicesFilterSchema, paginationFilterSchema])
);

export namespace DevicesRequestFilter {
  /**
   * Validation method to narrow down union type to DevicesFilter type case.
   *
   * This is DevicesFilter case.
   */
  export function isDevicesFilter(value: unknown): value is DevicesFilter {
    return isMappedValueValidForSchema(value, devicesFilterSchema);
  }

  /**
   * Validation method to narrow down union type to PaginationFilter type case.
   *
   * This is PaginationFilter case.
   */
  export function isPaginationFilter(
    value: unknown
  ): value is PaginationFilter {
    return isMappedValueValidForSchema(value, paginationFilterSchema);
  }
}
