/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  isMappedValueValidForSchema,
  lazy,
  oneOf,
  Schema,
} from '../../schema.js';
import { LineString, lineStringSchema } from '../lineString.js';
import { MultiLineString, multiLineStringSchema } from '../multiLineString.js';
import { MultiPolygon, multiPolygonSchema } from '../multiPolygon.js';
import { Polygon, polygonSchema } from '../polygon.js';

/** This is a container type for one-of types. */
export type Geometry = LineString | Polygon | MultiLineString | MultiPolygon;

export const geometrySchema: Schema<Geometry> = lazy(() =>
  oneOf([
    lineStringSchema,
    polygonSchema,
    multiLineStringSchema,
    multiPolygonSchema,
  ])
);

export namespace Geometry {
  /**
   * Validation method to narrow down union type to LineString type case.
   *
   * This is LineString case.
   */
  export function isLineString(value: unknown): value is LineString {
    return isMappedValueValidForSchema(value, lineStringSchema);
  }

  /**
   * Validation method to narrow down union type to Polygon type case.
   *
   * This is Polygon case.
   */
  export function isPolygon(value: unknown): value is Polygon {
    return isMappedValueValidForSchema(value, polygonSchema);
  }

  /**
   * Validation method to narrow down union type to MultiLineString type case.
   *
   * This is MultiLineString case.
   */
  export function isMultiLineString(value: unknown): value is MultiLineString {
    return isMappedValueValidForSchema(value, multiLineStringSchema);
  }

  /**
   * Validation method to narrow down union type to MultiPolygon type case.
   *
   * This is MultiPolygon case.
   */
  export function isMultiPolygon(value: unknown): value is MultiPolygon {
    return isMappedValueValidForSchema(value, multiPolygonSchema);
  }
}
