/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  anyOf,
  isMappedValueValidForSchema,
  lazy,
  Schema,
} from '../../schema.js';
import { DeviceLabels, deviceLabelsSchema } from '../deviceLabels.js';

/** This is a container type for any-of types. */
export type LabelsListDeviceIds = DeviceLabels;

export const labelsListDeviceIdsSchema: Schema<LabelsListDeviceIds> = lazy(() =>
  anyOf([deviceLabelsSchema])
);

export namespace LabelsListDeviceIds {
  /**
   * Validation method to narrow down union type to DeviceLabels type case.
   *
   * This is DeviceLabels case.
   */
  export function isDeviceLabels(value: unknown): value is DeviceLabels {
    return isMappedValueValidForSchema(value, deviceLabelsSchema);
  }
}
