/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  isMappedValueValidForSchema,
  lazy,
  oneOf,
  Schema,
} from '../../schema.js';
import { HeadingItem, headingItemSchema } from '../headingItem.js';
import { SpeedItem, speedItemSchema } from '../speedItem.js';

/** This is a container type for one-of types. */
export type Limits = SpeedItem | HeadingItem;

export const limitsSchema: Schema<Limits> = lazy(() =>
  oneOf([speedItemSchema, headingItemSchema])
);

export namespace Limits {
  /**
   * Validation method to narrow down union type to SpeedItem type case.
   *
   * This is SpeedItem case.
   */
  export function isSpeedItem(value: unknown): value is SpeedItem {
    return isMappedValueValidForSchema(value, speedItemSchema);
  }

  /**
   * Validation method to narrow down union type to HeadingItem type case.
   *
   * This is HeadingItem case.
   */
  export function isHeadingItem(value: unknown): value is HeadingItem {
    return isMappedValueValidForSchema(value, headingItemSchema);
  }
}
