/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  anyOf,
  isMappedValueValidForSchema,
  lazy,
  Schema,
} from '../../schema.js';
import {
  M5gBiaccountNameobject,
  m5gBiaccountNameobjectSchema,
} from '../m5gBiaccountNameobject.js';

/** This is a container type for any-of types. */
export type M5gBideviceDetailsresponseDevices = M5gBiaccountNameobject;

export const m5gBideviceDetailsresponseDevicesSchema: Schema<M5gBideviceDetailsresponseDevices> = lazy(
  () => anyOf([m5gBiaccountNameobjectSchema])
);

export namespace M5gBideviceDetailsresponseDevices {
  /**
   * Validation method to narrow down union type to M5gBiaccountNameobject type case.
   *
   * This is 5gbiaccountNameobject case.
   */
  export function isM5gBiaccountNameobject(
    value: unknown
  ): value is M5gBiaccountNameobject {
    return isMappedValueValidForSchema(value, m5gBiaccountNameobjectSchema);
  }
}
