/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  anyOf,
  isMappedValueValidForSchema,
  lazy,
  Schema,
} from '../../schema.js';
import {
  M5gBiaddressAndcustomerinfo,
  m5gBiaddressAndcustomerinfoSchema,
} from '../m5gBiaddressAndcustomerinfo.js';
import {
  M5gBideviceIdarray,
  m5gBideviceIdarraySchema,
} from '../m5gBideviceIdarray.js';

/** This is a container type for any-of types. */
export type M5gBiactivateRequestDeviceListWithServiceAddress =
  | M5gBideviceIdarray
  | M5gBiaddressAndcustomerinfo;

export const m5gBiactivateRequestDeviceListWithServiceAddressSchema: Schema<M5gBiactivateRequestDeviceListWithServiceAddress> = lazy(
  () => anyOf([m5gBideviceIdarraySchema, m5gBiaddressAndcustomerinfoSchema])
);

export namespace M5gBiactivateRequestDeviceListWithServiceAddress {
  /**
   * Validation method to narrow down union type to M5gBideviceIdarray type case.
   *
   * This is 5gbideviceIdarray case.
   */
  export function isM5gBideviceIdarray(
    value: unknown
  ): value is M5gBideviceIdarray {
    return isMappedValueValidForSchema(value, m5gBideviceIdarraySchema);
  }

  /**
   * Validation method to narrow down union type to M5gBiaddressAndcustomerinfo type case.
   *
   * This is 5gbiaddressAndcustomerinfo case.
   */
  export function isM5gBiaddressAndcustomerinfo(
    value: unknown
  ): value is M5gBiaddressAndcustomerinfo {
    return isMappedValueValidForSchema(
      value,
      m5gBiaddressAndcustomerinfoSchema
    );
  }
}
