/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  anyOf,
  isMappedValueValidForSchema,
  lazy,
  Schema,
} from '../../schema.js';
import { M5gBikeyValue1, m5gBikeyValue1Schema } from '../m5gBikeyValue1.js';

/** This is a container type for any-of types. */
export type M5gBiaccountNameobjectCustomFields = M5gBikeyValue1;

export const m5gBiaccountNameobjectCustomFieldsSchema: Schema<M5gBiaccountNameobjectCustomFields> = lazy(
  () => anyOf([m5gBikeyValue1Schema])
);

export namespace M5gBiaccountNameobjectCustomFields {
  /**
   * Validation method to narrow down union type to M5gBikeyValue1 type case.
   *
   * This is 5gbikeyValue1 case.
   */
  export function isM5gBikeyValue1(value: unknown): value is M5gBikeyValue1 {
    return isMappedValueValidForSchema(value, m5gBikeyValue1Schema);
  }
}
