/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  isMappedValueValidForSchema,
  lazy,
  oneOf,
  Schema,
} from '../../schema.js';
import {
  ETXMAPMessageGeoJSONPolygon,
  eTXMAPMessageGeoJSONPolygonSchema,
} from '../eTXMAPMessageGeoJSONPolygon.js';
import {
  ETXMAPMessageIntersectionCoordinates,
  eTXMAPMessageIntersectionCoordinatesSchema,
} from '../eTXMAPMessageIntersectionCoordinates.js';

/** This is a container type for one-of types. */
export type MapDataQueryRequest =
  | ETXMAPMessageIntersectionCoordinates
  | ETXMAPMessageGeoJSONPolygon;

export const mapDataQueryRequestSchema: Schema<MapDataQueryRequest> = lazy(() =>
  oneOf([
    eTXMAPMessageIntersectionCoordinatesSchema,
    eTXMAPMessageGeoJSONPolygonSchema,
  ])
);

export namespace MapDataQueryRequest {
  /**
   * Validation method to narrow down union type to ETXMAPMessageIntersectionCoordinates type case.
   *
   * This is ETX MAP Message Intersection Coordinates case.
   */
  export function isETXMAPMessageIntersectionCoordinates(
    value: unknown
  ): value is ETXMAPMessageIntersectionCoordinates {
    return isMappedValueValidForSchema(
      value,
      eTXMAPMessageIntersectionCoordinatesSchema
    );
  }

  /**
   * Validation method to narrow down union type to ETXMAPMessageGeoJSONPolygon type case.
   *
   * This is ETX MAP Message GeoJSON Polygon case.
   */
  export function isETXMAPMessageGeoJSONPolygon(
    value: unknown
  ): value is ETXMAPMessageGeoJSONPolygon {
    return isMappedValueValidForSchema(
      value,
      eTXMAPMessageGeoJSONPolygonSchema
    );
  }
}
