/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  anyOf,
  isMappedValueValidForSchema,
  lazy,
  Schema,
} from '../../schema.js';
import { Carriercode1, carriercode1Schema } from '../carriercode1.js';

/** This is a container type for any-of types. */
export type NotifyThreshold = Carriercode1;

export const notifyThresholdSchema: Schema<NotifyThreshold> = lazy(() =>
  anyOf([carriercode1Schema])
);

export namespace NotifyThreshold {
  /**
   * Validation method to narrow down union type to Carriercode1 type case.
   *
   * This is carriercode1 case.
   */
  export function isCarriercode1(value: unknown): value is Carriercode1 {
    return isMappedValueValidForSchema(value, carriercode1Schema);
  }
}
