/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  anyOf,
  isMappedValueValidForSchema,
  lazy,
  Schema,
} from '../../schema.js';
import { Addressquery, addressquerySchema } from '../addressquery.js';
import {
  Customernamequery,
  customernamequerySchema,
} from '../customernamequery.js';

/** This is a container type for any-of types. */
export type ProfileRequestPrimaryPlaceOfUse = Customernamequery | Addressquery;

export const profileRequestPrimaryPlaceOfUseSchema: Schema<ProfileRequestPrimaryPlaceOfUse> = lazy(
  () => anyOf([customernamequerySchema, addressquerySchema])
);

export namespace ProfileRequestPrimaryPlaceOfUse {
  /**
   * Validation method to narrow down union type to Customernamequery type case.
   *
   * This is customernamequery case.
   */
  export function isCustomernamequery(
    value: unknown
  ): value is Customernamequery {
    return isMappedValueValidForSchema(value, customernamequerySchema);
  }

  /**
   * Validation method to narrow down union type to Addressquery type case.
   *
   * This is addressquery case.
   */
  export function isAddressquery(value: unknown): value is Addressquery {
    return isMappedValueValidForSchema(value, addressquerySchema);
  }
}
