/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  anyOf,
  isMappedValueValidForSchema,
  lazy,
  Schema,
} from '../../schema.js';
import {
  DtoDeviceActionSetRequest,
  dtoDeviceActionSetRequestSchema,
} from '../dtoDeviceActionSetRequest.js';
import {
  DtoDeviceCommand,
  dtoDeviceCommandSchema,
} from '../dtoDeviceCommand.js';

/** This is a container type for any-of types. */
export type SensorInsightsDeviceActionSetRequestBody =
  | DtoDeviceActionSetRequest
  | DtoDeviceCommand;

export const sensorInsightsDeviceActionSetRequestBodySchema: Schema<SensorInsightsDeviceActionSetRequestBody> = lazy(
  () => anyOf([dtoDeviceActionSetRequestSchema, dtoDeviceCommandSchema])
);

export namespace SensorInsightsDeviceActionSetRequestBody {
  /**
   * Validation method to narrow down union type to DtoDeviceActionSetRequest type case.
   *
   * This is dto.DeviceActionSetRequest case.
   */
  export function isDtoDeviceActionSetRequest(
    value: unknown
  ): value is DtoDeviceActionSetRequest {
    return isMappedValueValidForSchema(value, dtoDeviceActionSetRequestSchema);
  }

  /**
   * Validation method to narrow down union type to DtoDeviceCommand type case.
   *
   * This is dto.deviceCommand case.
   */
  export function isDtoDeviceCommand(
    value: unknown
  ): value is DtoDeviceCommand {
    return isMappedValueValidForSchema(value, dtoDeviceCommandSchema);
  }
}
