/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  anyOf,
  isMappedValueValidForSchema,
  lazy,
  Schema,
} from '../../schema.js';
import { GIOSmsMessage, gIOSmsMessageSchema } from '../gIOSmsMessage.js';

/** This is a container type for any-of types. */
export type SmsMessagesResponseMessages = GIOSmsMessage;

export const smsMessagesResponseMessagesSchema: Schema<SmsMessagesResponseMessages> = lazy(
  () => anyOf([gIOSmsMessageSchema])
);

export namespace SmsMessagesResponseMessages {
  /**
   * Validation method to narrow down union type to GIOSmsMessage type case.
   *
   * This is GIOSmsMessage case.
   */
  export function isGIOSmsMessage(value: unknown): value is GIOSmsMessage {
    return isMappedValueValidForSchema(value, gIOSmsMessageSchema);
  }
}
