/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  isMappedValueValidForSchema,
  lazy,
  oneOf,
  Schema,
} from '../../schema.js';
import { ITISItemWrapper, iTISItemWrapperSchema } from '../iTISItemWrapper.js';
import {
  TextPhraseItemWrapper,
  textPhraseItemWrapperSchema,
} from '../textPhraseItemWrapper.js';

/** This is a container type for one-of types. */
export type TextPhraseOrITIS = ITISItemWrapper | TextPhraseItemWrapper;

export const textPhraseOrITISSchema: Schema<TextPhraseOrITIS> = lazy(() =>
  oneOf([iTISItemWrapperSchema, textPhraseItemWrapperSchema])
);

export namespace TextPhraseOrITIS {
  /**
   * Validation method to narrow down union type to ITISItemWrapper type case.
   *
   * This is ITISItemWrapper case.
   */
  export function isITISItemWrapper(value: unknown): value is ITISItemWrapper {
    return isMappedValueValidForSchema(value, iTISItemWrapperSchema);
  }

  /**
   * Validation method to narrow down union type to TextPhraseItemWrapper type case.
   *
   * This is TextPhraseItemWrapper case.
   */
  export function isTextPhraseItemWrapper(
    value: unknown
  ): value is TextPhraseItemWrapper {
    return isMappedValueValidForSchema(value, textPhraseItemWrapperSchema);
  }
}
