/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  anyOf,
  isMappedValueValidForSchema,
  lazy,
  Schema,
} from '../../schema.js';
import {
  AnomalyTriggerValue,
  anomalyTriggerValueSchema,
} from '../anomalyTriggerValue.js';
import { TriggerType2, triggerType2Schema } from '../triggerType2.js';

/** This is a container type for any-of types. */
export type TriggersListOptions2 = AnomalyTriggerValue | TriggerType2;

export const triggersListOptions2Schema: Schema<TriggersListOptions2> = lazy(
  () => anyOf([anomalyTriggerValueSchema, triggerType2Schema])
);

export namespace TriggersListOptions2 {
  /**
   * Validation method to narrow down union type to AnomalyTriggerValue type case.
   *
   * This is AnomalyTriggerValue case.
   */
  export function isAnomalyTriggerValue(
    value: unknown
  ): value is AnomalyTriggerValue {
    return isMappedValueValidForSchema(value, anomalyTriggerValueSchema);
  }

  /**
   * Validation method to narrow down union type to TriggerType2 type case.
   *
   * This is TriggerType2 case.
   */
  export function isTriggerType2(value: unknown): value is TriggerType2 {
    return isMappedValueValidForSchema(value, triggerType2Schema);
  }
}
