/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  anyOf,
  isMappedValueValidForSchema,
  lazy,
  Schema,
} from '../../schema.js';
import { Triggervalues2, triggervalues2Schema } from '../triggervalues2.js';

/** This is a container type for any-of types. */
export type TriggervalueChunk2 = Triggervalues2;

export const triggervalueChunk2Schema: Schema<TriggervalueChunk2> = lazy(() =>
  anyOf([triggervalues2Schema])
);

export namespace TriggervalueChunk2 {
  /**
   * Validation method to narrow down union type to Triggervalues2 type case.
   *
   * This is Triggervalues2 case.
   */
  export function isTriggervalues2(value: unknown): value is Triggervalues2 {
    return isMappedValueValidForSchema(value, triggervalues2Schema);
  }
}
