/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  anyOf,
  isMappedValueValidForSchema,
  lazy,
  Schema,
} from '../../schema.js';
import { Triggervalues, triggervaluesSchema } from '../triggervalues.js';

/** This is a container type for any-of types. */
export type TriggervalueChunk = Triggervalues;

export const triggervalueChunkSchema: Schema<TriggervalueChunk> = lazy(() =>
  anyOf([triggervaluesSchema])
);

export namespace TriggervalueChunk {
  /**
   * Validation method to narrow down union type to Triggervalues type case.
   *
   * This is Triggervalues case.
   */
  export function isTriggervalues(value: unknown): value is Triggervalues {
    return isMappedValueValidForSchema(value, triggervaluesSchema);
  }
}
