/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  anyOf,
  isMappedValueValidForSchema,
  lazy,
  Schema,
} from '../../schema.js';
import {
  DataPercentage100TriggerAttribute,
  dataPercentage100TriggerAttributeSchema,
} from '../dataPercentage100TriggerAttribute.js';
import {
  DataPercentage50TriggerAttribute,
  dataPercentage50TriggerAttributeSchema,
} from '../dataPercentage50TriggerAttribute.js';
import {
  DataPercentage75TriggerAttribute,
  dataPercentage75TriggerAttributeSchema,
} from '../dataPercentage75TriggerAttribute.js';
import {
  DataPercentage90TriggerAttribute,
  dataPercentage90TriggerAttributeSchema,
} from '../dataPercentage90TriggerAttribute.js';
import {
  NotificationGroupNameTriggerAttribute,
  notificationGroupNameTriggerAttributeSchema,
} from '../notificationGroupNameTriggerAttribute.js';
import {
  ServicePlanTriggerAttribute,
  servicePlanTriggerAttributeSchema,
} from '../servicePlanTriggerAttribute.js';

/** This is a container type for any-of types. */
export type TriggerAttributesOptions2 =
  | NotificationGroupNameTriggerAttribute
  | ServicePlanTriggerAttribute
  | DataPercentage50TriggerAttribute
  | DataPercentage75TriggerAttribute
  | DataPercentage90TriggerAttribute
  | DataPercentage100TriggerAttribute;

export const triggerAttributesOptions2Schema: Schema<TriggerAttributesOptions2> = lazy(
  () =>
    anyOf([
      notificationGroupNameTriggerAttributeSchema,
      servicePlanTriggerAttributeSchema,
      dataPercentage50TriggerAttributeSchema,
      dataPercentage75TriggerAttributeSchema,
      dataPercentage90TriggerAttributeSchema,
      dataPercentage100TriggerAttributeSchema,
    ])
);

export namespace TriggerAttributesOptions2 {
  /**
   * Validation method to narrow down union type to NotificationGroupNameTriggerAttribute type case.
   *
   * This is NotificationGroupNameTriggerAttribute case.
   */
  export function isNotificationGroupNameTriggerAttribute(
    value: unknown
  ): value is NotificationGroupNameTriggerAttribute {
    return isMappedValueValidForSchema(
      value,
      notificationGroupNameTriggerAttributeSchema
    );
  }

  /**
   * Validation method to narrow down union type to ServicePlanTriggerAttribute type case.
   *
   * This is ServicePlanTriggerAttribute case.
   */
  export function isServicePlanTriggerAttribute(
    value: unknown
  ): value is ServicePlanTriggerAttribute {
    return isMappedValueValidForSchema(
      value,
      servicePlanTriggerAttributeSchema
    );
  }

  /**
   * Validation method to narrow down union type to DataPercentage50TriggerAttribute type case.
   *
   * This is DataPercentage50TriggerAttribute case.
   */
  export function isDataPercentage50TriggerAttribute(
    value: unknown
  ): value is DataPercentage50TriggerAttribute {
    return isMappedValueValidForSchema(
      value,
      dataPercentage50TriggerAttributeSchema
    );
  }

  /**
   * Validation method to narrow down union type to DataPercentage75TriggerAttribute type case.
   *
   * This is DataPercentage75TriggerAttribute case.
   */
  export function isDataPercentage75TriggerAttribute(
    value: unknown
  ): value is DataPercentage75TriggerAttribute {
    return isMappedValueValidForSchema(
      value,
      dataPercentage75TriggerAttributeSchema
    );
  }

  /**
   * Validation method to narrow down union type to DataPercentage90TriggerAttribute type case.
   *
   * This is DataPercentage90TriggerAttribute case.
   */
  export function isDataPercentage90TriggerAttribute(
    value: unknown
  ): value is DataPercentage90TriggerAttribute {
    return isMappedValueValidForSchema(
      value,
      dataPercentage90TriggerAttributeSchema
    );
  }

  /**
   * Validation method to narrow down union type to DataPercentage100TriggerAttribute type case.
   *
   * This is DataPercentage100TriggerAttribute case.
   */
  export function isDataPercentage100TriggerAttribute(
    value: unknown
  ): value is DataPercentage100TriggerAttribute {
    return isMappedValueValidForSchema(
      value,
      dataPercentage100TriggerAttributeSchema
    );
  }
}
