/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  anyOf,
  isMappedValueValidForSchema,
  lazy,
  Schema,
} from '../../schema.js';
import { Cellphonenumber, cellphonenumberSchema } from '../cellphonenumber.js';

/** This is a container type for any-of types. */
export type V2TriggersRequestSmsNumbers = Cellphonenumber;

export const v2TriggersRequestSmsNumbersSchema: Schema<V2TriggersRequestSmsNumbers> = lazy(
  () => anyOf([cellphonenumberSchema])
);

export namespace V2TriggersRequestSmsNumbers {
  /**
   * Validation method to narrow down union type to Cellphonenumber type case.
   *
   * This is cellphonenumber case.
   */
  export function isCellphonenumber(value: unknown): value is Cellphonenumber {
    return isMappedValueValidForSchema(value, cellphonenumberSchema);
  }
}
