/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  GetAccountInformationResponseforplanner,
  getAccountInformationResponseforplannerSchema,
} from '../models/getAccountInformationResponseforplanner.js';
import { string } from '../schema.js';
import { BaseController } from './baseController.js';
import { AuthRestErrorResponseforplannerError } from '../errors/authRestErrorResponseforplannerError.js';
import { RestErrorResponseforplannerError } from '../errors/restErrorResponseforplannerError.js';

export class AccountServiceController extends BaseController {
  /**
   * Returns aaccount information associated with a specified account.
   *
   * @param accountName The account's numeric name, including leading zeroes.
   * @return Response from the API call
   */
  async getAccountInformationUsingGET(
    accountName: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<GetAccountInformationResponseforplanner>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ accountName: [accountName, string()] });
    req.appendTemplatePath`/v1/accounts/${mapped.accountName}`;
    req.throwOn(400, RestErrorResponseforplannerError, 'Bad request');
    req.throwOn(401, AuthRestErrorResponseforplannerError, 'Unauthorized');
    req.throwOn(403, RestErrorResponseforplannerError, 'Forbidden');
    req.throwOn(
      404,
      RestErrorResponseforplannerError,
      'Not Found / Does not exist'
    );
    req.throwOn(
      406,
      RestErrorResponseforplannerError,
      'Format / Request Unacceptable'
    );
    req.throwOn(429, RestErrorResponseforplannerError, 'Too many requests');
    req.defaultToError(RestErrorResponseforplannerError, 'Error response');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(
      getAccountInformationResponseforplannerSchema,
      requestOptions
    );
  }
}
