/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  NotificationReportRequest,
  notificationReportRequestSchema,
} from '../models/notificationReportRequest.js';
import {
  RequestResponse,
  requestResponseSchema,
} from '../models/requestResponse.js';
import {
  StopMonitorRequest,
  stopMonitorRequestSchema,
} from '../models/stopMonitorRequest.js';
import { BaseController } from './baseController.js';
import { RestErrorResponseError } from '../errors/restErrorResponseError.js';

export class DeviceMonitoringController extends BaseController {
  /**
   * @param body         Create Reachability Report Request
   * @return Response from the API call
   */
  async deviceReachability(
    body: NotificationReportRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<RequestResponse>> {
    const req = this.createRequest(
      'POST',
      '/m2m/v1/diagnostics/basic/devicereachability'
    );
    const mapped = req.prepareArgs({
      body: [body, notificationReportRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, RestErrorResponseError, 'Error Response');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(requestResponseSchema, requestOptions);
  }

  /**
   * @param stopreachabilitypayload Payload for the Stop Device Reachability monitors
   *                                                             request.
   * @return Response from the API call
   */
  async stopDeviceReachability(
    stopreachabilitypayload: StopMonitorRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<RequestResponse>> {
    const req = this.createRequest(
      'DELETE',
      '/m2m/v1/diagnostics/basic/devicereachability'
    );
    const mapped = req.prepareArgs({
      stopreachabilitypayload: [
        stopreachabilitypayload,
        stopMonitorRequestSchema,
      ],
    });
    req.query('stopreachabilitypayload', mapped.stopreachabilitypayload);
    req.throwOn(400, RestErrorResponseError, 'Error Response');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(requestResponseSchema, requestOptions);
  }
}
