/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  AccountDeviceListRequest,
  accountDeviceListRequestSchema,
} from '../models/accountDeviceListRequest.js';
import {
  AccountDeviceListResult,
  accountDeviceListResultSchema,
} from '../models/accountDeviceListResult.js';
import {
  AddDevicesRequest,
  addDevicesRequestSchema,
} from '../models/addDevicesRequest.js';
import {
  AddDevicesResult,
  addDevicesResultSchema,
} from '../models/addDevicesResult.js';
import {
  AssociateLabelRequest,
  associateLabelRequestSchema,
} from '../models/associateLabelRequest.js';
import {
  BilledusageListRequest,
  billedusageListRequestSchema,
} from '../models/billedusageListRequest.js';
import {
  CarrierActionsRequest,
  carrierActionsRequestSchema,
} from '../models/carrierActionsRequest.js';
import {
  CarrierActivateRequest,
  carrierActivateRequestSchema,
} from '../models/carrierActivateRequest.js';
import {
  CarrierDeactivateRequest,
  carrierDeactivateRequestSchema,
} from '../models/carrierDeactivateRequest.js';
import {
  ChangeDeviceIdRequest,
  changeDeviceIdRequestSchema,
} from '../models/changeDeviceIdRequest.js';
import {
  CheckOrderStatusRequest,
  checkOrderStatusRequestSchema,
} from '../models/checkOrderStatusRequest.js';
import {
  ConnectionHistoryResult,
  connectionHistoryResultSchema,
} from '../models/connectionHistoryResult.js';
import {
  ContactInfoUpdateRequest,
  contactInfoUpdateRequestSchema,
} from '../models/contactInfoUpdateRequest.js';
import {
  CustomFieldsUpdateRequest,
  customFieldsUpdateRequestSchema,
} from '../models/customFieldsUpdateRequest.js';
import {
  DeleteDevicesRequest,
  deleteDevicesRequestSchema,
} from '../models/deleteDevicesRequest.js';
import {
  DeleteDevicesResult,
  deleteDevicesResultSchema,
} from '../models/deleteDevicesResult.js';
import {
  DeviceActivationRequest,
  deviceActivationRequestSchema,
} from '../models/deviceActivationRequest.js';
import {
  DeviceAggregateUsageListRequest,
  deviceAggregateUsageListRequestSchema,
} from '../models/deviceAggregateUsageListRequest.js';
import {
  DeviceConnectionListRequest,
  deviceConnectionListRequestSchema,
} from '../models/deviceConnectionListRequest.js';
import {
  DeviceCostCenterRequest,
  deviceCostCenterRequestSchema,
} from '../models/deviceCostCenterRequest.js';
import {
  DeviceExtendedDiagnosticsRequest,
  deviceExtendedDiagnosticsRequestSchema,
} from '../models/deviceExtendedDiagnosticsRequest.js';
import {
  DeviceExtendedDiagnosticsResult,
  deviceExtendedDiagnosticsResultSchema,
} from '../models/deviceExtendedDiagnosticsResult.js';
import {
  DeviceManagementResult,
  deviceManagementResultSchema,
} from '../models/deviceManagementResult.js';
import {
  DeviceMismatchListRequest,
  deviceMismatchListRequestSchema,
} from '../models/deviceMismatchListRequest.js';
import {
  DeviceMismatchListResult,
  deviceMismatchListResultSchema,
} from '../models/deviceMismatchListResult.js';
import {
  DevicePrlListRequest,
  devicePrlListRequestSchema,
} from '../models/devicePrlListRequest.js';
import {
  DeviceProvisioningHistoryListRequest,
  deviceProvisioningHistoryListRequestSchema,
} from '../models/deviceProvisioningHistoryListRequest.js';
import {
  DeviceProvisioningHistoryListResult,
  deviceProvisioningHistoryListResultSchema,
} from '../models/deviceProvisioningHistoryListResult.js';
import {
  DeviceSuspensionStatusRequest,
  deviceSuspensionStatusRequestSchema,
} from '../models/deviceSuspensionStatusRequest.js';
import {
  DeviceUploadRequest,
  deviceUploadRequestSchema,
} from '../models/deviceUploadRequest.js';
import {
  DeviceUsageListRequest,
  deviceUsageListRequestSchema,
} from '../models/deviceUsageListRequest.js';
import {
  DeviceUsageListResult,
  deviceUsageListResultSchema,
} from '../models/deviceUsageListResult.js';
import {
  GoToStateRequest,
  goToStateRequestSchema,
} from '../models/goToStateRequest.js';
import { LabelsList, labelsListSchema } from '../models/labelsList.js';
import {
  MoveDeviceRequest,
  moveDeviceRequestSchema,
} from '../models/moveDeviceRequest.js';
import {
  RequestResponse,
  requestResponseSchema,
} from '../models/requestResponse.js';
import {
  ServicePlanUpdateRequest,
  servicePlanUpdateRequestSchema,
} from '../models/servicePlanUpdateRequest.js';
import {
  UploadsActivatesDeviceRequest,
  uploadsActivatesDeviceRequestSchema,
} from '../models/uploadsActivatesDeviceRequest.js';
import { array, string } from '../schema.js';
import { BaseController } from './baseController.js';
import { ConnectivityManagementResultError } from '../errors/connectivityManagementResultError.js';
import { RestErrorResponseError } from '../errors/restErrorResponseError.js';

export class DeviceManagementController extends BaseController {
  /**
   * If the devices do not already exist in the account, this API resource adds them before activation.
   *
   * @param body         Request for activating a service on devices.
   * @return Response from the API call
   */
  async activateServiceForDevices(
    body: CarrierActivateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DeviceManagementResult>> {
    const req = this.createRequest('POST', '/m2m/v1/devices/actions/activate');
    const mapped = req.prepareArgs({
      body: [body, carrierActivateRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ConnectivityManagementResultError, 'Error response.');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(deviceManagementResultSchema, requestOptions);
  }

  /**
   * Use this API if you want to manage some device settings before you are ready to activate service for
   * the devices.
   *
   * @param body         Devices to add.
   * @return Response from the API call
   */
  async addDevices(
    body: AddDevicesRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AddDevicesResult[]>> {
    const req = this.createRequest('POST', '/m2m/v1/devices/actions/add');
    const mapped = req.prepareArgs({ body: [body, addDevicesRequestSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ConnectivityManagementResultError, 'Error response.');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(array(addDevicesResultSchema), requestOptions);
  }

  /**
   * Sends a CarrierService callback message for each device in the request when the contact information
   * has been changed, or if there was a problem and the change could not be completed.
   *
   * @param body         Request to update contact information for devices.
   * @return Response from the API call
   */
  async updateDevicesContactInformation(
    body: ContactInfoUpdateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DeviceManagementResult>> {
    const req = this.createRequest(
      'PUT',
      '/m2m/v1/devices/actions/contactInfo'
    );
    const mapped = req.prepareArgs({
      body: [body, contactInfoUpdateRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ConnectivityManagementResultError, 'Error response.');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(deviceManagementResultSchema, requestOptions);
  }

  /**
   * Sends a CarrierService callback message for each device in the request when the custom fields have
   * been changed, or if there was a problem and the change could not be completed.
   *
   * @param body         Request to update custom field of devices.
   * @return Response from the API call
   */
  async updateDevicesCustomFields(
    body: CustomFieldsUpdateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DeviceManagementResult>> {
    const req = this.createRequest(
      'PUT',
      '/m2m/v1/devices/actions/customFields'
    );
    const mapped = req.prepareArgs({
      body: [body, customFieldsUpdateRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ConnectivityManagementResultError, 'Error response.');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(deviceManagementResultSchema, requestOptions);
  }

  /**
   * Deactivating service for a device may result in an early termination fee (ETF) being charged to the
   * account, depending on the terms of the contract with Verizon. If your contract allows ETF waivers
   * and if you want to use one for a particular deactivation, set the etfWaiver value to True.
   *
   * @param body         Request to deactivate service for one or more devices.
   * @return Response from the API call
   */
  async deactivateServiceForDevices(
    body: CarrierDeactivateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DeviceManagementResult>> {
    const req = this.createRequest(
      'POST',
      '/m2m/v1/devices/actions/deactivate'
    );
    const mapped = req.prepareArgs({
      body: [body, carrierDeactivateRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ConnectivityManagementResultError, 'Error response.');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(deviceManagementResultSchema, requestOptions);
  }

  /**
   * Use this API to remove unneeded devices from an account.
   *
   * @param body         Devices to delete.
   * @return Response from the API call
   */
  async deleteDeactivatedDevices(
    body: DeleteDevicesRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DeleteDevicesResult[]>> {
    const req = this.createRequest('POST', '/m2m/v1/devices/actions/delete');
    const mapped = req.prepareArgs({
      body: [body, deleteDevicesRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ConnectivityManagementResultError, 'Error response.');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(array(deleteDevicesResultSchema), requestOptions);
  }

  /**
   * Returns information about a single device or information about all devices that match the given
   * parameters. Returned information includes device provisioning state, service plan, MDN, MIN, and IP
   * address.
   *
   * @param body         Device information query.
   * @return Response from the API call
   */
  async listDevicesInformation(
    body: AccountDeviceListRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AccountDeviceListResult>> {
    const req = this.createRequest('POST', '/m2m/v1/devices/actions/list');
    const mapped = req.prepareArgs({
      body: [body, accountDeviceListRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ConnectivityManagementResultError, 'Error response.');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(accountDeviceListResultSchema, requestOptions);
  }

  /**
   * Returns a list of all 4G devices with an ICCID (SIM) that was not activated with the expected IMEI
   * (hardware) during a specified time frame.
   *
   * @param body         Request to list devices with mismatched IMEIs and ICCIDs.
   * @return Response from the API call
   */
  async listDevicesWithImeiIccidMismatch(
    body: DeviceMismatchListRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DeviceMismatchListResult>> {
    const req = this.createRequest(
      'POST',
      '/m2m/v1/devices/actions/list/imeiiccidmismatch'
    );
    const mapped = req.prepareArgs({
      body: [body, deviceMismatchListRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ConnectivityManagementResultError, 'Error response.');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(deviceMismatchListResultSchema, requestOptions);
  }

  /**
   * Move active devices from one billing account to another within a customer profile.
   *
   * @param body         Request to move devices between accounts.
   * @return Response from the API call
   */
  async moveDevicesWithinAccountsOfProfile(
    body: MoveDeviceRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DeviceManagementResult>> {
    const req = this.createRequest('PUT', '/m2m/v1/devices/actions/move');
    const mapped = req.prepareArgs({ body: [body, moveDeviceRequestSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ConnectivityManagementResultError, 'Error response.');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(deviceManagementResultSchema, requestOptions);
  }

  /**
   * Changes the provisioning state of one or more devices to a specified customer-defined service and
   * state.
   *
   * @param body         Request to change device state to one defined by the user.
   * @return Response from the API call
   */
  async updateDevicesState(
    body: GoToStateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DeviceManagementResult>> {
    const req = this.createRequest('PUT', '/m2m/v1/devices/actions/gotostate');
    const mapped = req.prepareArgs({ body: [body, goToStateRequestSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ConnectivityManagementResultError, 'Error response.');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(deviceManagementResultSchema, requestOptions);
  }

  /**
   * Changes the service plan for one or more devices.
   *
   * @param body         Request to change device service plan.
   * @return Response from the API call
   */
  async changeDevicesServicePlan(
    body: ServicePlanUpdateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DeviceManagementResult>> {
    const req = this.createRequest('PUT', '/m2m/v1/devices/actions/plan');
    const mapped = req.prepareArgs({
      body: [body, servicePlanUpdateRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ConnectivityManagementResultError, 'Error response.');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(deviceManagementResultSchema, requestOptions);
  }

  /**
   * Suspends service for one or more devices.
   *
   * @param body         Request to suspend service for one or more devices.
   * @return Response from the API call
   */
  async suspendServiceForDevices(
    body: CarrierActionsRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DeviceManagementResult>> {
    const req = this.createRequest('POST', '/m2m/v1/devices/actions/suspend');
    const mapped = req.prepareArgs({
      body: [body, carrierActionsRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ConnectivityManagementResultError, 'Error response.');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(deviceManagementResultSchema, requestOptions);
  }

  /**
   * Restores service to one or more suspended devices.
   *
   * @param body         Request to restore services of one or more suspended devices.
   * @return Response from the API call
   */
  async restoreServiceForSuspendedDevices(
    body: CarrierActionsRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DeviceManagementResult>> {
    const req = this.createRequest('POST', '/m2m/v1/devices/actions/restore');
    const mapped = req.prepareArgs({
      body: [body, carrierActionsRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ConnectivityManagementResultError, 'Error response.');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(deviceManagementResultSchema, requestOptions);
  }

  /**
   * Checks whether specified devices are registered by the manufacturer with the Verizon network and are
   * available to be activated.
   *
   * @param body         Request to check if devices can be activated or not.
   * @return Response from the API call
   */
  async checkDevicesAvailabilityForActivation(
    body: DeviceActivationRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DeviceManagementResult>> {
    const req = this.createRequest(
      'POST',
      '/m2m/v1/devices/availability/actions/list'
    );
    const mapped = req.prepareArgs({
      body: [body, deviceActivationRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ConnectivityManagementResultError, 'Error response.');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(deviceManagementResultSchema, requestOptions);
  }

  /**
   * Each response includes a maximum of 500 records. To obtain more records, you can call the API
   * multiple times, adjusting the earliest value each time to start where the previous request finished.
   *
   * @param body         Query to retrieve device connection history.
   * @return Response from the API call
   */
  async retrieveDeviceConnectionHistory(
    body: DeviceConnectionListRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ConnectionHistoryResult>> {
    const req = this.createRequest(
      'POST',
      '/m2m/v1/devices/connections/actions/listHistory'
    );
    const mapped = req.prepareArgs({
      body: [body, deviceConnectionListRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ConnectivityManagementResultError, 'Error response.');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(connectionHistoryResultSchema, requestOptions);
  }

  /**
   * Changes or removes the CostCenterCode value or customer name and address (Primary Place of Use) for
   * one or more devices.
   *
   * @param body         Request to update cost center code value for one or more
   *                                                       devices.
   * @return Response from the API call
   */
  async updateDevicesCostCenterCode(
    body: DeviceCostCenterRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DeviceManagementResult>> {
    const req = this.createRequest('PUT', '/m2m/v1/devices/costCenter');
    const mapped = req.prepareArgs({
      body: [body, deviceCostCenterRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ConnectivityManagementResultError, 'Error response.');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(deviceManagementResultSchema, requestOptions);
  }

  /**
   * Returns extended diagnostic information about a specified device, including connectivity,
   * provisioning, billing and location status.
   *
   * @param body         Request to query extended diagnostics information
   *                                                                for a device.
   * @return Response from the API call
   */
  async getDeviceExtendedDiagnosticInformation(
    body: DeviceExtendedDiagnosticsRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DeviceExtendedDiagnosticsResult>> {
    const req = this.createRequest(
      'POST',
      '/m2m/v1/devices/extendeddiagnostics/actions/list'
    );
    const mapped = req.prepareArgs({
      body: [body, deviceExtendedDiagnosticsRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ConnectivityManagementResultError, 'Error response.');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(
      deviceExtendedDiagnosticsResultSchema,
      requestOptions
    );
  }

  /**
   * Returns the provisioning history of a specified device during a specified time period.
   *
   * @param body         Query to obtain device provisioning history.
   * @return Response from the API call
   */
  async listDevicesProvisioningHistory(
    body: DeviceProvisioningHistoryListRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DeviceProvisioningHistoryListResult[]>> {
    const req = this.createRequest(
      'POST',
      '/m2m/v1/devices/history/actions/list'
    );
    const mapped = req.prepareArgs({
      body: [body, deviceProvisioningHistoryListRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ConnectivityManagementResultError, 'Error response.');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(
      array(deviceProvisioningHistoryListResultSchema),
      requestOptions
    );
  }

  /**
   * 4G and GSM devices do not have a PRL.
   *
   * @param body         Request to query device PRL.
   * @return Response from the API call
   */
  async listCurrentDevicesPRLVersion(
    body: DevicePrlListRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DeviceManagementResult>> {
    const req = this.createRequest('POST', '/m2m/v1/devices/prl/actions/list');
    const mapped = req.prepareArgs({
      body: [body, devicePrlListRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ConnectivityManagementResultError, 'Error response.');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(deviceManagementResultSchema, requestOptions);
  }

  /**
   * Returns DeviceSuspensionStatus callback messages containing the current device state and information
   * on how many days a device has been suspended and can continue to be suspended.
   *
   * @param body         Request to obtain service suspenstion status for a
   *                                                             device.
   * @return Response from the API call
   */
  async getDeviceServiceSuspensionStatus(
    body: DeviceSuspensionStatusRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DeviceManagementResult>> {
    const req = this.createRequest('POST', '/m2m/v1/devices/suspension/status');
    const mapped = req.prepareArgs({
      body: [body, deviceSuspensionStatusRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ConnectivityManagementResultError, 'Error response.');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(deviceManagementResultSchema, requestOptions);
  }

  /**
   * Returns the network data usage history of a device during a specified time period.
   *
   * @param body         Request to obtain usage history for a specific device.
   * @return Response from the API call
   */
  async listDevicesUsageHistory(
    body: DeviceUsageListRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DeviceUsageListResult>> {
    const req = this.createRequest(
      'POST',
      '/m2m/v1/devices/usage/actions/list'
    );
    const mapped = req.prepareArgs({
      body: [body, deviceUsageListRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ConnectivityManagementResultError, 'Error response.');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(deviceUsageListResultSchema, requestOptions);
  }

  /**
   * The information is returned in a callback response, so you must register a URL for DeviceUsage
   * callback messages using the POST /callbacks API.
   *
   * @param body         A request to retrieve aggregated device usage
   *                                                               history information.
   * @return Response from the API call
   */
  async retrieveAggregateDeviceUsageHistory(
    body: DeviceAggregateUsageListRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DeviceManagementResult>> {
    const req = this.createRequest(
      'POST',
      '/m2m/v1/devices/usage/actions/list/aggregate'
    );
    const mapped = req.prepareArgs({
      body: [body, deviceAggregateUsageListRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ConnectivityManagementResultError, 'Error response.');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(deviceManagementResultSchema, requestOptions);
  }

  /**
   * Changes the identifier of a 3G or 4G device to match hardware changes made for a line of service.
   * Use this request to transfer the line of service and the MDN to new hardware, or to change the MDN.
   *
   * @param serviceType  Identifier type.
   * @param body         Request to update device id.
   * @return Response from the API call
   */
  async updateDeviceId(
    serviceType: string,
    body: ChangeDeviceIdRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DeviceManagementResult>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({
      serviceType: [serviceType, string()],
      body: [body, changeDeviceIdRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/m2m/v1/devices/${mapped.serviceType}/actions/deviceId`;
    req.throwOn(400, ConnectivityManagementResultError, 'Error response.');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(deviceManagementResultSchema, requestOptions);
  }

  /**
   * Upload a device record
   *
   * @param body         Device Upload Query
   * @return Response from the API call
   */
  async deviceUpload(
    body: DeviceUploadRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<RequestResponse>> {
    const req = this.createRequest('POST', '/m2m/v1/devices/actions/upload');
    const mapped = req.prepareArgs({ body: [body, deviceUploadRequestSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, RestErrorResponseError, 'Error Response');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(requestResponseSchema, requestOptions);
  }

  /**
   * Gets billed usage for for either multiple devices or an entire billing account.
   *
   * @param body         Request to list devices with mismatched IMEIs and ICCIDs.
   * @return Response from the API call
   */
  async billedUsageInfo(
    body: BilledusageListRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DeviceManagementResult>> {
    const req = this.createRequest(
      'POST',
      '/m2m/v1/devices/usage/actions/billedusage/list'
    );
    const mapped = req.prepareArgs({
      body: [body, billedusageListRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ConnectivityManagementResultError, 'Error response.');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(deviceManagementResultSchema, requestOptions);
  }

  /**
   * Allows you to associate your own usage segmentation label with a device.
   *
   * @param body         Request to associate a label to a device.
   * @return Response from the API call
   */
  async usageSegmentationLabelAssociation(
    body: AssociateLabelRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DeviceManagementResult>> {
    const req = this.createRequest(
      'POST',
      '/m2m/v1/devices/actions/usagesegmentationlabels'
    );
    const mapped = req.prepareArgs({
      body: [body, associateLabelRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ConnectivityManagementResultError, 'Error response.');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(deviceManagementResultSchema, requestOptions);
  }

  /**
   * Allow customers to remove the associated label from a device.
   *
   * @param accountName The numeric name of the account.
   * @param labelList   A list of the Label IDs to remove from the exclusion list.
   * @return Response from the API call
   */
  async usageSegmentationLabelDeletion(
    accountName: string,
    labelList: LabelsList,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DeviceManagementResult>> {
    const req = this.createRequest(
      'DELETE',
      '/m2m/v1/devices/actions/usagesegmentationlabels'
    );
    const mapped = req.prepareArgs({
      accountName: [accountName, string()],
      labelList: [labelList, labelsListSchema],
    });
    req.query('accountName', mapped.accountName);
    req.query('LabelList', mapped.labelList);
    req.throwOn(400, ConnectivityManagementResultError, 'Error response.');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(deviceManagementResultSchema, requestOptions);
  }

  /**
   * Uploads and activates device identifiers and SKUs for new devices from OEMs to Verizon.
   *
   * @param body         Request to Upload and Activate device.
   * @return Response from the API call
   */
  async uploadActivateDevice(
    body: UploadsActivatesDeviceRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DeviceManagementResult>> {
    const req = this.createRequest(
      'POST',
      '/m2m/v1/devices/actions/uploadactivate'
    );
    const mapped = req.prepareArgs({
      body: [body, uploadsActivatesDeviceRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ConnectivityManagementResultError, 'Error response.');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(deviceManagementResultSchema, requestOptions);
  }

  /**
   * Checks the status of an activation order and lists where the order is in the provisioning process.
   *
   * @param body         The request body identifies the device and reporting period
   *                                                       that you want included in the report.
   * @return Response from the API call
   */
  async deviceUploadStatus(
    body: CheckOrderStatusRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DeviceManagementResult>> {
    const req = this.createRequest('POST', '/m2m/v1/devices/requests/status');
    const mapped = req.prepareArgs({
      body: [body, checkOrderStatusRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ConnectivityManagementResultError, 'Error response.');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(deviceManagementResultSchema, requestOptions);
  }
}
