/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  DiagnosticObservationSetting,
  diagnosticObservationSettingSchema,
} from '../models/diagnosticObservationSetting.js';
import { array, string } from '../schema.js';
import { BaseController } from './baseController.js';
import { DeviceDiagnosticsResultError } from '../errors/deviceDiagnosticsResultError.js';

export class DiagnosticsSettingsController extends BaseController {
  /**
   * This endpoint retrieves diagnostics settings synchronously.
   *
   * @param accountName Account identifier.
   * @param devices     Devices list formatted as "id, kind"
   * @return Response from the API call
   */
  async listDiagnosticsSettings(
    accountName: string,
    devices: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DiagnosticObservationSetting[]>> {
    const req = this.createRequest('GET', '/devices/settings');
    req.baseUrl('Device Diagnostics');
    const mapped = req.prepareArgs({
      accountName: [accountName, string()],
      devices: [devices, string()],
    });
    req.query('accountName', mapped.accountName);
    req.query('devices', mapped.devices);
    req.defaultToError(DeviceDiagnosticsResultError, 'Error response.');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(
      array(diagnosticObservationSettingSchema),
      requestOptions
    );
  }
}
