/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  DeviceResetRequest,
  deviceResetRequestSchema,
} from '../models/deviceResetRequest.js';
import {
  DiagnosticsObservationResult,
  diagnosticsObservationResultSchema,
} from '../models/diagnosticsObservationResult.js';
import { BaseController } from './baseController.js';
import { DeviceDiagnosticsResultError } from '../errors/deviceDiagnosticsResultError.js';

export class DiagnosticsFactoryResetController extends BaseController {
  /**
   * Performs a device reboot or a factory reset on the modem portion of the device.
   *
   * @param body         A request to perform a device reboot.
   * @return Response from the API call
   */
  async decivesRestart(
    body: DeviceResetRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DiagnosticsObservationResult>> {
    const req = this.createRequest('POST', '/devices/actions/restart');
    req.baseUrl('Device Diagnostics');
    const mapped = req.prepareArgs({ body: [body, deviceResetRequestSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.defaultToError(DeviceDiagnosticsResultError, 'Error response.');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(diagnosticsObservationResultSchema, requestOptions);
  }
}
