/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  ClientPersistenceResponse,
  clientPersistenceResponseSchema,
} from '../models/clientPersistenceResponse.js';
import {
  ClientRegistrationRequestV2,
  clientRegistrationRequestV2Schema,
} from '../models/clientRegistrationRequestV2.js';
import {
  ClientRegistrationResponse,
  clientRegistrationResponseSchema,
} from '../models/clientRegistrationResponse.js';
import {
  ConnectionRequest,
  connectionRequestSchema,
} from '../models/connectionRequest.js';
import {
  ConnectionResponse,
  connectionResponseSchema,
} from '../models/connectionResponse.js';
import {
  ConnectionResponseV3,
  connectionResponseV3Schema,
} from '../models/connectionResponseV3.js';
import {
  DevicesRequest,
  devicesRequestSchema,
} from '../models/devicesRequest.js';
import {
  DevicesResponse,
  devicesResponseSchema,
} from '../models/devicesResponse.js';
import {
  ETXClientIDLookup,
  eTXClientIDLookupSchema,
} from '../models/eTXClientIDLookup.js';
import { array, optional, string, unknown } from '../schema.js';
import { BaseController } from './baseController.js';
import { ETXRespondingError } from '../errors/eTXRespondingError.js';

export class ETXRegistrationController extends BaseController {
  /**
   * With this API call the user (client) registers its device or software service to the ETX system.
   * Therefore, when a connection is initiated from the device or software service to the ETX system
   * along with the credential provided by this registration call, then the connection will be authorized.
   *
   * - The user can register multiple devices or software services, which can all be used at the same
   * time.
   * - There rules set in the system that limit the type and subtype of the clients that are allowed to
   * be registered under the VendorID. The rules are created based ont he agreement between the Vendor
   * and Verizon.
   * - The user will only be able to register a limited number of devices or software services under the
   * same VendorID. This registration limit is specified by the agreement between the Vendor and Verizon.
   *
   * Note: The user needs to authenticate with their ThingSpace credentials using the Access/Bearer and
   * Session/M2M tokens in order to call this API.
   *
   *
   * @param body
   * @param xTransactionId   Optional transaction identifier for tracing
   *                                                               requests. If not provided, the application will
   *                                                               generate one.
   * @return Response from the API call
   */
  async registerETXClient(
    body: ClientRegistrationRequestV2,
    xTransactionId?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ClientRegistrationResponse>> {
    const req = this.createRequest('POST', '/api/v2/clients/registration');
    req.baseUrl('IMP Server');
    const mapped = req.prepareArgs({
      body: [body, clientRegistrationRequestV2Schema],
      xTransactionId: [xTransactionId, optional(string())],
    });
    req.header('Content-Type', 'application/json');
    req.header('X-Transaction-Id', mapped.xTransactionId);
    req.json(mapped.body);
    req.throwOn(400, ETXRespondingError, 'Invalid Request');
    req.throwOn(401, ETXRespondingError, 'Unauthorized Request');
    req.throwOn(403, ETXRespondingError, 'Forbidden Request');
    req.throwOn(429, ETXRespondingError, 'Too Many Requests');
    req.throwOn(503, ETXRespondingError, 'Internal Server Error');
    req.defaultToError(ETXRespondingError, 'Forbidden');
    req.authenticate([{ thingspaceOauth: true, sessionToken: true }]);
    return req.callAsJson(clientRegistrationResponseSchema, requestOptions);
  }

  /**
   * With this API call the user (client) can:
   * - renew the certificate of a device or software service in the ETX system if the original
   * certificate has expired. If the client's certificate expired or going to expire within 30 days and
   * new certificate will be issued. If the certificate expires more than 30 days, the current
   * certificate will be returned to the client.
   * - complete its device or software service registration to the ETX system if the original
   * registration request was not successful because of a pending certificate generation. Whenever the
   * user receives a "client registration is pending" response (HTTP 202) from POST /clients/registration
   * call. The client should initiate this PUT API call to finish the registration process and get the
   * required certificate.
   *
   * Note: The user needs to authenticate with their ThingSpace credentials using the Access/Bearer and
   * Session/M2M tokens in order to call this API.
   *
   *
   * @param deviceID
   * @param vendorID         The VendorID set during the Vendor registration call.
   * @param xTransactionId   Optional transaction identifier for tracing requests. If not provided, the
   *                                    application will generate one.
   * @param body
   * @return Response from the API call
   */
  async renewETXClientCertificate(
    deviceID: string,
    vendorID: string,
    xTransactionId?: string,
    body?: unknown,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ClientRegistrationResponse>> {
    const req = this.createRequest('PUT', '/api/v2/clients/registration');
    req.baseUrl('IMP Server');
    const mapped = req.prepareArgs({
      deviceID: [deviceID, string()],
      vendorID: [vendorID, string()],
      xTransactionId: [xTransactionId, optional(string())],
      body: [body, optional(unknown())],
    });
    req.header('DeviceID', mapped.deviceID);
    req.header('VendorID', mapped.vendorID);
    req.header('Content-Type', 'application/json');
    req.header('X-Transaction-Id', mapped.xTransactionId);
    req.json(mapped.body);
    req.throwOn(400, ETXRespondingError, 'Invalid Request');
    req.throwOn(401, ETXRespondingError, 'Unauthorized Request');
    req.throwOn(403, ETXRespondingError, 'Forbidden Request');
    req.throwOn(429, ETXRespondingError, 'Too Many Requests');
    req.throwOn(503, ETXRespondingError, 'Internal Server Error');
    req.defaultToError(ETXRespondingError, 'Forbidden');
    req.authenticate([{ thingspaceOauth: true, sessionToken: true }]);
    return req.callAsJson(clientRegistrationResponseSchema, requestOptions);
  }

  /**
   * With this API call the user (client) can unregister its devices and software services from the ETX
   * system. The unregistered devices and services will no longer be able to use the ETX Message Exchange.
   *
   * Note: The user needs to authenticate with their ThingSpace credentials using the Access/Bearer and
   * Session/M2M tokens in order to call this API.
   *
   *
   * @param deviceIDs        The list of device IDs and software service IDs to be unregistered
   * @param vendorID         The VendorID set during the Vendor registration call.
   * @param xTransactionId   Optional transaction identifier for tracing requests. If not provided, the
   *                                     application will generate one.
   * @return Response from the API call
   */
  async unregisterETXClients(
    deviceIDs: string[],
    vendorID: string,
    xTransactionId?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('DELETE', '/api/v2/clients/registration');
    req.baseUrl('IMP Server');
    const mapped = req.prepareArgs({
      deviceIDs: [deviceIDs, array(string())],
      vendorID: [vendorID, string()],
      xTransactionId: [xTransactionId, optional(string())],
    });
    req.header('VendorID', mapped.vendorID);
    req.header('X-Transaction-Id', mapped.xTransactionId);
    req.query('DeviceIDs', mapped.deviceIDs);
    req.throwOn(400, ETXRespondingError, 'Invalid Request');
    req.throwOn(401, ETXRespondingError, 'Unauthorized Request');
    req.throwOn(403, ETXRespondingError, 'Forbidden Request');
    req.throwOn(429, ETXRespondingError, 'Too Many Requests');
    req.throwOn(503, ETXRespondingError, 'Internal Server Error');
    req.defaultToError(ETXRespondingError, 'Forbidden');
    req.authenticate([{ thingspaceOauth: true, sessionToken: true }]);
    return req.call(requestOptions);
  }

  /**
   * With this API call the user can check the certificate of the device. At least one of the DeviceID,
   * IMEI, ICCID or IMSI is required to make the call.
   *
   * Note: The user needs to authenticate with their ThingSpace credentials using the Access/Bearer and
   * Session/M2M tokens in order to call this API.
   *
   *
   * @param iD               One of the following IDs is required- DeviceID, IMEI, ICCID,
   *                                                     IMSI. If more than one ID is provided, the API will return the
   *                                                     certificate for the first ID found. The IDs are evaluated in
   *                                                     the following order: DeviceID, IMEI, ICCID, IMSI. If the first
   *                                                     provided ID is not found, the API will return an error.
   * @param vendorID         The VendorID set during the Vendor registration call.
   * @param xTransactionId   Optional transaction identifier for tracing requests. If not
   *                                                     provided, the application will generate one.
   * @return Response from the API call
   */
  async getETXClientCertificate(
    iD: ETXClientIDLookup,
    vendorID: string,
    xTransactionId?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ClientPersistenceResponse>> {
    const req = this.createRequest('GET', '/api/v2/clients/registration');
    req.baseUrl('IMP Server');
    const mapped = req.prepareArgs({
      iD: [iD, eTXClientIDLookupSchema],
      vendorID: [vendorID, string()],
      xTransactionId: [xTransactionId, optional(string())],
    });
    req.header('VendorID', mapped.vendorID);
    req.header('X-Transaction-Id', mapped.xTransactionId);
    req.query('ID', mapped.iD);
    req.throwOn(400, ETXRespondingError, 'Invalid request');
    req.throwOn(401, ETXRespondingError, 'Unauthorized');
    req.throwOn(403, ETXRespondingError, 'Forbidden Request');
    req.throwOn(404, ETXRespondingError, 'Not Found');
    req.throwOn(429, ETXRespondingError, 'Too Many Requests');
    req.throwOn(500, ETXRespondingError, 'Internal server Error');
    req.defaultToError(ETXRespondingError, 'Forbidden');
    req.authenticate([{ thingspaceOauth: true, sessionToken: true }]);
    return req.callAsJson(clientPersistenceResponseSchema, requestOptions);
  }

  /**
   * With this API call the device or software service requests the MQTT URL for the location that it
   * needs to connect. To determine the proper URL the device or software service needs to provide its ID
   * (the one that was provided in the registration request), location (GPS coordinates), and whether it
   * is on the Verizon cellular network or not.
   *
   * Note: The user needs to authenticate with their ThingSpace credentials using the Access/Bearer and
   * Session/M2M tokens in order to call this API.
   *
   *
   * @param vendorID         The VendorID set during the Vendor registration call.
   * @param body
   * @param xTransactionId   Optional transaction identifier for tracing requests. If not
   *                                                     provided, the application will generate one.
   * @return Response from the API call
   */
  async getETXConnectionUrl(
    vendorID: string,
    body: ConnectionRequest,
    xTransactionId?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ConnectionResponse>> {
    const req = this.createRequest('POST', '/api/v2/clients/connection');
    req.baseUrl('IMP Server');
    const mapped = req.prepareArgs({
      vendorID: [vendorID, string()],
      body: [body, connectionRequestSchema],
      xTransactionId: [xTransactionId, optional(string())],
    });
    req.header('VendorID', mapped.vendorID);
    req.header('Content-Type', 'application/json');
    req.header('X-Transaction-Id', mapped.xTransactionId);
    req.json(mapped.body);
    req.throwOn(400, ETXRespondingError, 'Invalid request');
    req.throwOn(401, ETXRespondingError, 'Unauthorized');
    req.throwOn(403, ETXRespondingError, 'Forbidden Request');
    req.throwOn(429, ETXRespondingError, 'Too Many Requests');
    req.throwOn(503, ETXRespondingError, 'Internal server Error');
    req.defaultToError(ETXRespondingError, 'Forbidden');
    req.authenticate([{ thingspaceOauth: true, sessionToken: true }]);
    return req.callAsJson(connectionResponseSchema, requestOptions);
  }

  /**
   * With this API call the device or software service requests the MQTT URL for the location that it
   * needs to connect. To determine the proper URL the device or software service needs to provide its ID
   * (the one that was provided in the registration request), location (GPS coordinates), and whether it
   * is on the Verizon cellular network or not.
   *
   * If there are multiple MECs that serve the location of the client all options are provided in the
   * response, and the client is free to choose which MEC they want to connect.
   *
   * Note: The user needs to authenticate with their ThingSpace credentials using the Access/Bearer and
   * Session/M2M tokens in order to call this API.
   *
   *
   * @param vendorID         The VendorID set during the Vendor registration call.
   * @param body
   * @param xTransactionId   Optional transaction identifier for tracing requests. If not
   *                                                     provided, the application will generate one.
   * @return Response from the API call
   */
  async getETXConnectionUrlMultiMec(
    vendorID: string,
    body: ConnectionRequest,
    xTransactionId?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ConnectionResponseV3>> {
    const req = this.createRequest('POST', '/api/v3/clients/connection');
    req.baseUrl('IMP Server');
    const mapped = req.prepareArgs({
      vendorID: [vendorID, string()],
      body: [body, connectionRequestSchema],
      xTransactionId: [xTransactionId, optional(string())],
    });
    req.header('VendorID', mapped.vendorID);
    req.header('Content-Type', 'application/json');
    req.header('X-Transaction-Id', mapped.xTransactionId);
    req.json(mapped.body);
    req.throwOn(400, ETXRespondingError, 'Invalid request');
    req.throwOn(401, ETXRespondingError, 'Unauthorized');
    req.throwOn(403, ETXRespondingError, 'Forbidden Request');
    req.throwOn(429, ETXRespondingError, 'Too Many Requests');
    req.throwOn(503, ETXRespondingError, 'Internal server Error');
    req.defaultToError(ETXRespondingError, 'Forbidden');
    req.authenticate([{ thingspaceOauth: true, sessionToken: true }]);
    return req.callAsJson(connectionResponseV3Schema, requestOptions);
  }

  /**
   * This API allows retrieving devices by vendor ID and optional filters. The request should include the
   * VendorID and any filters to apply.
   *
   *
   * @param body
   * @param xTransactionId   Optional transaction identifier for tracing requests. If not
   *                                                  provided, the application will generate one.
   * @return Response from the API call
   */
  async queryETXDevices(
    body: DevicesRequest,
    xTransactionId?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DevicesResponse[]>> {
    const req = this.createRequest('POST', '/api/v1/clients/query');
    req.baseUrl('IMP Server');
    const mapped = req.prepareArgs({
      body: [body, devicesRequestSchema],
      xTransactionId: [xTransactionId, optional(string())],
    });
    req.header('Content-Type', 'application/json');
    req.header('X-Transaction-Id', mapped.xTransactionId);
    req.json(mapped.body);
    req.throwOn(400, ETXRespondingError, 'Invalid Request');
    req.throwOn(401, ETXRespondingError, 'Unauthorized Request');
    req.throwOn(500, ETXRespondingError, 'Internal Server Error');
    req.defaultToError(ETXRespondingError, 'Forbidden');
    req.authenticate([{ thingspaceOauth: true, sessionToken: true }]);
    return req.callAsJson(array(devicesResponseSchema), requestOptions);
  }
}
