/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  HplAddDevicesRequest,
  hplAddDevicesRequestSchema,
} from '../models/hplAddDevicesRequest.js';
import { array } from '../schema.js';
import { BaseController } from './baseController.js';
import { HyperPreciseLocationResultError } from '../errors/hyperPreciseLocationResultError.js';

export class HPLDeviceManagementController extends BaseController {
  /**
   * Use this API if you want to manage some device settings before you are ready to activate service for
   * the devices.
   *
   * @param body         Devices to add to the account.
   * @return Response from the API call
   */
  async addDevicesHyperPrecise(
    body: HplAddDevicesRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<HplAddDevicesRequest[]>> {
    const req = this.createRequest('POST', '/devices/actions/add');
    req.baseUrl('Hyper Precise Location');
    const mapped = req.prepareArgs({
      body: [body, hplAddDevicesRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, HyperPreciseLocationResultError, 'Bad Request.');
    req.throwOn(401, HyperPreciseLocationResultError, 'Unauthorized');
    req.throwOn(403, HyperPreciseLocationResultError, 'Forbidden');
    req.throwOn(
      404,
      HyperPreciseLocationResultError,
      'Not Found / Does not exist'
    );
    req.throwOn(405, HyperPreciseLocationResultError, 'Method Not Allowed');
    req.throwOn(
      406,
      HyperPreciseLocationResultError,
      'Format / Request Unacceptable'
    );
    req.throwOn(429, HyperPreciseLocationResultError, 'Too many requests');
    req.throwOn(500, HyperPreciseLocationResultError, 'Internal Server Error');
    req.defaultToError(HyperPreciseLocationResultError, 'Error response');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(array(hplAddDevicesRequestSchema), requestOptions);
  }
}
