/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  AsynchronousRequestResultforplanner,
  asynchronousRequestResultforplannerSchema,
} from '../models/asynchronousRequestResultforplanner.js';
import {
  GetDeviceStatusesRequestforplanner,
  getDeviceStatusesRequestforplannerSchema,
} from '../models/getDeviceStatusesRequestforplanner.js';
import {
  GetDeviceStatusesResponseforplanner,
  getDeviceStatusesResponseforplannerSchema,
} from '../models/getDeviceStatusesResponseforplanner.js';
import {
  GetDevicesWindowsRequestforplanner,
  getDevicesWindowsRequestforplannerSchema,
} from '../models/getDevicesWindowsRequestforplanner.js';
import { optional } from '../schema.js';
import { BaseController } from './baseController.js';
import { AuthRestErrorResponseforplannerError } from '../errors/authRestErrorResponseforplannerError.js';
import { RestErrorResponseforplannerError } from '../errors/restErrorResponseforplannerError.js';

export class IntelligenceServiceController extends BaseController {
  /**
   * Retrieves available device windows for Connection Planner.
   *
   * @param body
   * @return Response from the API call
   */
  async setConnectionPlanner(
    body?: GetDevicesWindowsRequestforplanner,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AsynchronousRequestResultforplanner>> {
    const req = this.createRequest(
      'POST',
      '/v1/intelligence/device/connection-planner'
    );
    const mapped = req.prepareArgs({
      body: [body, optional(getDevicesWindowsRequestforplannerSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, RestErrorResponseforplannerError, 'Bad request');
    req.throwOn(401, AuthRestErrorResponseforplannerError, 'Unauthorized');
    req.throwOn(403, RestErrorResponseforplannerError, 'Forbidden');
    req.throwOn(
      404,
      RestErrorResponseforplannerError,
      'Not Found / Does not exist'
    );
    req.throwOn(
      406,
      RestErrorResponseforplannerError,
      'Format / Request Unacceptable'
    );
    req.throwOn(429, RestErrorResponseforplannerError, 'Too many requests');
    req.defaultToError(RestErrorResponseforplannerError, 'Error response');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(
      asynchronousRequestResultforplannerSchema,
      requestOptions
    );
  }

  /**
   * Retrieves the device status for the Connection Planner service.
   *
   * @param body
   * @return Response from the API call
   */
  async statusConnectionPlanner(
    body?: GetDeviceStatusesRequestforplanner,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<GetDeviceStatusesResponseforplanner>> {
    const req = this.createRequest(
      'POST',
      '/v1/intelligence/device/connection-planner/status'
    );
    const mapped = req.prepareArgs({
      body: [body, optional(getDeviceStatusesRequestforplannerSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, RestErrorResponseforplannerError, 'Bad request');
    req.throwOn(401, AuthRestErrorResponseforplannerError, 'Unauthorized');
    req.throwOn(403, RestErrorResponseforplannerError, 'Forbidden');
    req.throwOn(
      404,
      RestErrorResponseforplannerError,
      'Not Found / Does not exist'
    );
    req.throwOn(
      406,
      RestErrorResponseforplannerError,
      'Format / Request Unacceptable'
    );
    req.throwOn(429, RestErrorResponseforplannerError, 'Too many requests');
    req.defaultToError(RestErrorResponseforplannerError, 'Error response');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(
      getDeviceStatusesResponseforplannerSchema,
      requestOptions
    );
  }
}
