/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  MapDataQueryRequest,
  mapDataQueryRequestSchema,
} from '../models/containers/mapDataQueryRequest.js';
import {
  ETXMAPDataIngestRequest,
  eTXMAPDataIngestRequestSchema,
} from '../models/eTXMAPDataIngestRequest.js';
import {
  ETXMessageStandardEnum,
  eTXMessageStandardEnumSchema,
} from '../models/eTXMessageStandardEnum.js';
import {
  GeofencePolygon,
  geofencePolygonSchema,
} from '../models/geofencePolygon.js';
import { array, string, unknown } from '../schema.js';
import { BaseController } from './baseController.js';
import { MdmErrorResponseError } from '../errors/mdmErrorResponseError.js';

export class MapMessageController extends BaseController {
  /**
   * This endpoint is deprecated. (Use /api/v2/mapdata/query for new integrations).
   *
   * This endpoint allows user to download SAE J2735 or ETSI MAP messages in ASN.1 UPER base64 encoded
   * format. The area for the MAP messages is needed to be defined in the query.
   *
   *
   * **Required request header:** `Accept` — specifies the response format. Omitting this header will
   * result in a `400 Bad Request`. Supported values:
   * - `text/plain` — ASN.1 UPER base64-encoded MAP messages (one per line)
   * - `application/json` — JSON-encoded MAP messages
   *
   * @param vendorID The VendorID set during the Vendor registration call.
   * @param geofence GeoJSON Polygon defining the area to retrieve MAP messages for.
   * @return Response from the API call
   * @deprecated
   */
  async downloadMAPMessages(
    vendorID: string,
    geofence: GeofencePolygon,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<string>> {
    const req = this.createRequest('GET', '/api/v2/mapdata');
    req.baseUrl('IMP Server');
    const mapped = req.prepareArgs({
      vendorID: [vendorID, string()],
      geofence: [geofence, geofencePolygonSchema],
    });
    req.header('VendorID', mapped.vendorID);
    req.query('Geofence', mapped.geofence);
    req.deprecated('MapMessageController.downloadMAPMessages');
    req.throwOn(400, MdmErrorResponseError, 'Bad Request');
    req.throwOn(401, MdmErrorResponseError, 'Unauthorized');
    req.throwOn(403, MdmErrorResponseError, 'Forbidden');
    req.throwOn(404, MdmErrorResponseError, 'Not found');
    req.throwOn(429, MdmErrorResponseError, 'Too many requests');
    req.throwOn(503, MdmErrorResponseError, 'Internal server error');
    req.defaultToError(MdmErrorResponseError, 'unexpected error');
    req.authenticate([{ thingspaceOauth: true, sessionToken: true }]);
    return req.callAsText(requestOptions);
  }

  /**
   * This endpoint allows the user to upload map messages in ASN.1 UPER base64 encoded format or JER
   * (JSON) formats. The MAP data message can have more than one intersections in it.
   * Both SAE and ETSI defined MAP messages are supported. The SAE type MAP messages have to be wrapped
   * in a MessageFrame, as defined in the SAE J2735 standard.
   * The ETSI type MAP messages are expected as MAPEM structures that include the ETSI header, as defined
   * in the ETSI TS 103 301 standard.
   * Note: The user needs to authenticate with their ThingSpace credentials using the Access/Bearer and
   * Session/M2M tokens in order to call this API.
   *
   *
   * **Required request header:** `Content-Type` — specifies the format of the request body. Omitting or
   * sending an unsupported value will result in a `415 Unsupported Media Type`. Supported values:
   * - `text/plain` — ASN.1 UPER base64-encoded MAP message
   * - `application/json` — JSON representation of the MAP message
   *
   * @param vendorID               The VendorID set during the Vendor registration
   *                                                                 call.
   * @param mapDataMessageStandard Select which V2X messaging standard will be used
   *                                                                 for the message generation. The following options
   *                                                                 are supported: - "etsi": The message will be
   *                                                                 generated using the ETSI (European) standard (e.g.
   *                                                                 MAPEM). - "sae": The message will be generated
   *                                                                 using the SAE J2735 (North American) standard (e.g.
   *                                                                 MAP). - if not sent while POST, defaults to
   *                                                                 "sae"
   * @param body                   UPER/ASN.1 J2735/ETSI base64 encoded MapData
   *                                                                 message or JSON representation of the MapData
   *                                                                 message.
   * @return Response from the API call
   */
  async ingestMAPMessages(
    vendorID: string,
    mapDataMessageStandard: ETXMessageStandardEnum,
    body: ETXMAPDataIngestRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<string>> {
    const req = this.createRequest('POST', '/api/v2/mapdata');
    req.baseUrl('IMP Server');
    const mapped = req.prepareArgs({
      vendorID: [vendorID, string()],
      mapDataMessageStandard: [
        mapDataMessageStandard,
        eTXMessageStandardEnumSchema,
      ],
      body: [body, eTXMAPDataIngestRequestSchema],
    });
    req.header('VendorID', mapped.vendorID);
    req.header('MessageStandard', mapped.mapDataMessageStandard);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, MdmErrorResponseError, 'Bad Request');
    req.throwOn(401, MdmErrorResponseError, 'Unauthorized');
    req.throwOn(403, MdmErrorResponseError, 'Forbidden');
    req.throwOn(405, MdmErrorResponseError, 'Method not allowed');
    req.throwOn(429, MdmErrorResponseError, 'Too many requests');
    req.throwOn(503, MdmErrorResponseError, 'Internal server error');
    req.defaultToError(MdmErrorResponseError, 'unexpected error');
    req.authenticate([{ thingspaceOauth: true, sessionToken: true }]);
    return req.callAsText(requestOptions);
  }

  /**
   * This endpoint allows users to download SAE J2735 or ETSI MAP messages as a JSON list.
   * Depending on the expectedType parameter, the response contains either ASN.1 UPER base64-encoded
   * messages with their respective region and intersection IDs, or fully decoded JSON messages.
   * The area for MAP message retrieval must be defined in the request body using one of two methods:
   * An array of region and intersection ID pairs, or a GeoJSON geofence specification.
   *
   *
   * @param vendorID     The VendorID set during the Vendor registration call.
   * @param body
   * @return Response from the API call
   */
  async queryMapMessages(
    vendorID: string,
    body: MapDataQueryRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown[]>> {
    const req = this.createRequest('POST', '/api/v2/mapdata/query');
    req.baseUrl('IMP Server');
    const mapped = req.prepareArgs({
      vendorID: [vendorID, string()],
      body: [body, mapDataQueryRequestSchema],
    });
    req.header('VendorID', mapped.vendorID);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, MdmErrorResponseError, 'Bad Request');
    req.throwOn(401, MdmErrorResponseError, 'Unauthorized');
    req.throwOn(403, MdmErrorResponseError, 'Forbidden');
    req.throwOn(405, MdmErrorResponseError, 'Method not allowed');
    req.throwOn(429, MdmErrorResponseError, 'Too many requests');
    req.throwOn(503, MdmErrorResponseError, 'Internal server error');
    req.defaultToError(MdmErrorResponseError, 'unexpected error');
    req.authenticate([{ thingspaceOauth: true, sessionToken: true }]);
    return req.callAsJson(array(unknown()), requestOptions);
  }

  /**
   * Removes a map message for the specified region and intersection ID.
   *
   * @param regionId Region ID to filter the map messages.
   * @param i10nid   Intersection ID to filter the map messages.
   * @return Response from the API call
   */
  async deleteMapMessage(
    regionId: string,
    i10nid: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('DELETE');
    req.baseUrl('IMP Server');
    const mapped = req.prepareArgs({
      regionId: [regionId, string()],
      i10nid: [i10nid, string()],
    });
    req.appendTemplatePath`/api/v2/mapdata/regionid/${mapped.regionId}/i10nid/${mapped.i10nid}`;
    req.throwOn(400, MdmErrorResponseError, 'Bad Request');
    req.throwOn(401, MdmErrorResponseError, 'Unauthorized');
    req.throwOn(403, MdmErrorResponseError, 'Forbidden');
    req.throwOn(404, MdmErrorResponseError, 'Not found');
    req.throwOn(429, MdmErrorResponseError, 'Too many requests');
    req.throwOn(503, MdmErrorResponseError, 'Internal server error');
    req.defaultToError(MdmErrorResponseError, 'unexpected error');
    req.authenticate([{ thingspaceOauth: true, sessionToken: true }]);
    return req.call(requestOptions);
  }
}
