/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  DtoListRulesRequest,
  dtoListRulesRequestSchema,
} from '../models/dtoListRulesRequest.js';
import {
  DtoOverwriteRuleRequest,
  dtoOverwriteRuleRequestSchema,
} from '../models/dtoOverwriteRuleRequest.js';
import { ResourceRule, resourceRuleSchema } from '../models/resourceRule.js';
import { array } from '../schema.js';
import { BaseController } from './baseController.js';
import { M400ManagementError } from '../errors/m400ManagementError.js';
import { M403ManagementError } from '../errors/m403ManagementError.js';
import { M404ManagementError } from '../errors/m404ManagementError.js';
import { M500ManagementError } from '../errors/m500ManagementError.js';
import { ManagementError } from '../errors/managementError.js';

export class SensorInsightsRulesController extends BaseController {
  /**
   * @param body         Overwrite a rule
   * @return Response from the API call
   */
  async sensorInsightsOverwriteRuleRequest(
    body: DtoOverwriteRuleRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ResourceRule>> {
    const req = this.createRequest('POST', '/dm/v1/rules');
    const mapped = req.prepareArgs({
      body: [body, dtoOverwriteRuleRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, M400ManagementError, 'Bad Request');
    req.throwOn(401, ManagementError, 'UnAuthorized');
    req.throwOn(403, M403ManagementError, 'Forbidden');
    req.throwOn(404, M404ManagementError, 'Not Found');
    req.throwOn(406, ManagementError, 'Not Acceptable');
    req.throwOn(415, ManagementError, 'Unsupported media type');
    req.throwOn(429, ManagementError, 'Too many requests');
    req.throwOn(500, M500ManagementError, 'Internal server error.');
    req.defaultToError(ManagementError, 'Unexpected error');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(resourceRuleSchema, requestOptions);
  }

  /**
   * @param body         Retrieve a rule
   * @return Response from the API call
   */
  async sensorInsightsListRulesRequest(
    body: DtoListRulesRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ResourceRule[]>> {
    const req = this.createRequest('POST', '/dm/v1/rules/actions/query');
    const mapped = req.prepareArgs({ body: [body, dtoListRulesRequestSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, M400ManagementError, 'Bad Request');
    req.throwOn(401, ManagementError, 'UnAuthorized');
    req.throwOn(403, M403ManagementError, 'Forbidden');
    req.throwOn(404, M404ManagementError, 'Not Found');
    req.throwOn(406, ManagementError, 'Not Acceptable');
    req.throwOn(415, ManagementError, 'Unsupported media type');
    req.throwOn(429, ManagementError, 'Too many requests');
    req.throwOn(500, M500ManagementError, 'Internal server error.');
    req.defaultToError(ManagementError, 'Unexpected error');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(array(resourceRuleSchema), requestOptions);
  }
}
