/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  DtoListDevicesRequest,
  dtoListDevicesRequestSchema,
} from '../models/dtoListDevicesRequest.js';
import {
  ResourceDevice,
  resourceDeviceSchema,
} from '../models/resourceDevice.js';
import { array } from '../schema.js';
import { BaseController } from './baseController.js';
import { M400ManagementError } from '../errors/m400ManagementError.js';
import { M403ManagementError } from '../errors/m403ManagementError.js';
import { M404ManagementError } from '../errors/m404ManagementError.js';
import { M500ManagementError } from '../errors/m500ManagementError.js';
import { ManagementError } from '../errors/managementError.js';

export class SensorInsightsGatewaysController extends BaseController {
  /**
   * @param body         Get gateway information
   * @return Response from the API call
   */
  async sensorInsightsListGatewayDevicesRequest(
    body: DtoListDevicesRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ResourceDevice[]>> {
    const req = this.createRequest(
      'POST',
      '/dm/v1/devices/gateways/actions/query'
    );
    const mapped = req.prepareArgs({
      body: [body, dtoListDevicesRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, M400ManagementError, 'Bad Request');
    req.throwOn(401, ManagementError, 'UnAuthorized');
    req.throwOn(403, M403ManagementError, 'Forbidden');
    req.throwOn(404, M404ManagementError, 'Not Found');
    req.throwOn(406, ManagementError, 'Not Acceptable');
    req.throwOn(415, ManagementError, 'Unsupported media type');
    req.throwOn(429, ManagementError, 'Too many requests');
    req.throwOn(500, M500ManagementError, 'Internal server error.');
    req.defaultToError(ManagementError, 'Unexpected error');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(array(resourceDeviceSchema), requestOptions);
  }
}
