/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  ESIMProfileRequest,
  eSIMProfileRequestSchema,
} from '../models/eSIMProfileRequest.js';
import {
  ESIMProfileRequest2,
  eSIMProfileRequest2Schema,
} from '../models/eSIMProfileRequest2.js';
import {
  ESIMRequestResponse,
  eSIMRequestResponseSchema,
} from '../models/eSIMRequestResponse.js';
import {
  ProfileRequest2,
  profileRequest2Schema,
} from '../models/profileRequest2.js';
import { BaseController } from './baseController.js';
import { ESIMRestErrorResponseError } from '../errors/eSIMRestErrorResponseError.js';

export class SIMActionsController extends BaseController {
  /**
   * System assign a new activation code to reactivate a deactivated device. **Note:** the previously
   * assigned ICCID must be used to request a new activation code.
   *
   * @param body         Device Profile Query
   * @return Response from the API call
   */
  async newactivatecode(
    body: ESIMProfileRequest2,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ESIMRequestResponse>> {
    const req = this.createRequest(
      'POST',
      '/m2m/v1/devices/profile/actions/renew_activation_code'
    );
    const mapped = req.prepareArgs({ body: [body, eSIMProfileRequest2Schema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ESIMRestErrorResponseError, 'Bad request');
    req.throwOn(401, ESIMRestErrorResponseError, 'Unauthorized');
    req.throwOn(403, ESIMRestErrorResponseError, 'Forbidden');
    req.throwOn(404, ESIMRestErrorResponseError, 'Not Found / Does not exist');
    req.throwOn(
      406,
      ESIMRestErrorResponseError,
      'Format / Request Unacceptable'
    );
    req.throwOn(429, ESIMRestErrorResponseError, 'Too many requests');
    req.defaultToError(ESIMRestErrorResponseError, 'Error response');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(eSIMRequestResponseSchema, requestOptions);
  }

  /**
   * Uses the profile to activate the SIM.
   *
   * @param body         Device Profile Query
   * @return Response from the API call
   */
  async setactivateUsingPOST(
    body: ESIMProfileRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ESIMRequestResponse>> {
    const req = this.createRequest(
      'POST',
      '/m2m/v1/devices/profile/actions/activate'
    );
    const mapped = req.prepareArgs({ body: [body, eSIMProfileRequestSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ESIMRestErrorResponseError, 'Bad request');
    req.throwOn(401, ESIMRestErrorResponseError, 'Unauthorized');
    req.throwOn(403, ESIMRestErrorResponseError, 'Forbidden');
    req.throwOn(404, ESIMRestErrorResponseError, 'Not Found / Does not exist');
    req.throwOn(
      406,
      ESIMRestErrorResponseError,
      'Format / Request Unacceptable'
    );
    req.throwOn(429, ESIMRestErrorResponseError, 'Too many requests');
    req.defaultToError(ESIMRestErrorResponseError, 'Error response');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(eSIMRequestResponseSchema, requestOptions);
  }

  /**
   * Uses the profile to deactivate the SIM.
   *
   * @param body         Device Profile Query
   * @return Response from the API call
   */
  async setdeactivateUsingPOST(
    body: ProfileRequest2,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ESIMRequestResponse>> {
    const req = this.createRequest(
      'POST',
      '/m2m/v1/devices/profile/actions/deactivate'
    );
    const mapped = req.prepareArgs({ body: [body, profileRequest2Schema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ESIMRestErrorResponseError, 'Bad request');
    req.throwOn(401, ESIMRestErrorResponseError, 'Unauthorized');
    req.throwOn(403, ESIMRestErrorResponseError, 'Forbidden');
    req.throwOn(404, ESIMRestErrorResponseError, 'Not Found / Does not exist');
    req.throwOn(
      406,
      ESIMRestErrorResponseError,
      'Format / Request Unacceptable'
    );
    req.throwOn(429, ESIMRestErrorResponseError, 'Too many requests');
    req.defaultToError(ESIMRestErrorResponseError, 'Error response');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(eSIMRequestResponseSchema, requestOptions);
  }
}
