/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  Domestic4GAnd5gNationwideNetworkCoverageBody,
  domestic4GAnd5gNationwideNetworkCoverageBodySchema,
} from '../models/containers/domestic4GAnd5gNationwideNetworkCoverageBody.js';
import {
  GetDeviceExperienceScoreBulkRequest,
  getDeviceExperienceScoreBulkRequestSchema,
} from '../models/getDeviceExperienceScoreBulkRequest.js';
import {
  GetDeviceExperienceScoreHistoryRequest,
  getDeviceExperienceScoreHistoryRequestSchema,
} from '../models/getDeviceExperienceScoreHistoryRequest.js';
import {
  GetNetworkConditionsRequest,
  getNetworkConditionsRequestSchema,
} from '../models/getNetworkConditionsRequest.js';
import {
  WNPRequestResponse,
  wNPRequestResponseSchema,
} from '../models/wNPRequestResponse.js';
import { BaseController } from './baseController.js';
import { WNPRestErrorResponseError } from '../errors/wNPRestErrorResponseError.js';

export class WirelessNetworkPerformanceController extends BaseController {
  /**
   * WNP Query for current network condition.
   *
   * @param body         Request for current network health.
   * @return Response from the API call
   */
  async nearRealTimeNetworkConditions(
    body: GetNetworkConditionsRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<WNPRequestResponse>> {
    const req = this.createRequest(
      'POST',
      '/m2m/v1/intelligence/network-conditions'
    );
    const mapped = req.prepareArgs({
      body: [body, getNetworkConditionsRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.defaultToError(WNPRestErrorResponseError, 'Error response');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(wNPRequestResponseSchema, requestOptions);
  }

  /**
   * Run a report for FWA Address qualification or to determine network types available and available
   * coverage. Network types covered include: CAT-M, NB-IOT, LTE, LTE-AWS, 5GNW, MMWAVE and C-BAND.
   *
   * @param body         Request for network coverage details.
   * @return Response from the API call
   */
  async domestic4GAnd5gNationwideNetworkCoverage(
    body: Domestic4GAnd5gNationwideNetworkCoverageBody,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<WNPRequestResponse>> {
    const req = this.createRequest(
      'POST',
      '/m2m/v1/intelligence/wireless-coverage'
    );
    const mapped = req.prepareArgs({
      body: [body, domestic4GAnd5gNationwideNetworkCoverageBodySchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.defaultToError(WNPRestErrorResponseError, 'Error response');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(wNPRequestResponseSchema, requestOptions);
  }

  /**
   * Identify the direction and general distance of nearby cell sites and the technology supported by the
   * equipment.
   *
   * @param body         Request for cell site proximity.
   * @return Response from the API call
   */
  async siteProximity(
    body: GetNetworkConditionsRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<WNPRequestResponse>> {
    const req = this.createRequest(
      'POST',
      '/m2m/v1/intelligence/site-proximity/action/list'
    );
    const mapped = req.prepareArgs({
      body: [body, getNetworkConditionsRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.defaultToError(WNPRestErrorResponseError, 'Error response');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(wNPRequestResponseSchema, requestOptions);
  }

  /**
   * A report of a specific device's service scores over a 30 day period.
   *
   * @param body         Request for a device's 30 day experience.
   * @return Response from the API call
   */
  async deviceExperience30daysHistory(
    body: GetDeviceExperienceScoreHistoryRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<WNPRequestResponse>> {
    const req = this.createRequest(
      'POST',
      '/m2m/v1/intelligence/device-experience/history/30-days'
    );
    const mapped = req.prepareArgs({
      body: [body, getDeviceExperienceScoreHistoryRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.defaultToError(WNPRestErrorResponseError, 'Error response');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(wNPRequestResponseSchema, requestOptions);
  }

  /**
   * Run a report to view the latest device experience score for specific devices.
   *
   * @param body         Request for bulk latest history details.
   * @return Response from the API call
   */
  async deviceExperienceBulkLatest(
    body: GetDeviceExperienceScoreBulkRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<WNPRequestResponse>> {
    const req = this.createRequest(
      'POST',
      '/m2m/v1/intelligence/device-experience/bulk/latest'
    );
    const mapped = req.prepareArgs({
      body: [body, getDeviceExperienceScoreBulkRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.defaultToError(WNPRestErrorResponseError, 'Error response');
    req.authenticate([{ thingspaceOauth: true, vZM2mToken: true }]);
    return req.callAsJson(wNPRequestResponseSchema, requestOptions);
  }
}
