/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import { DeviceId, deviceIdSchema } from './deviceId.js';

/** A list of deviceId objects to use when requesting information from multiple devices. */
export interface AccountDeviceList {
  /** All identifiers for the device. */
  deviceIds: DeviceId[];
  ipaddress?: string;
}

export const accountDeviceListSchema: Schema<AccountDeviceList> = lazy(() =>
  object({
    deviceIds: ['deviceIds', array(deviceIdSchema)],
    ipaddress: ['ipAddress', optional(string())],
  })
);
