/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import {
  AccountGroupShareFilterCriteria,
  accountGroupShareFilterCriteriaSchema,
} from './accountGroupShareFilterCriteria.js';

export interface AccountGroupShareIndividual1 {
  accountGroupShareIndividual?: AccountGroupShareFilterCriteria;
}

export const accountGroupShareIndividual1Schema: Schema<AccountGroupShareIndividual1> = lazy(
  () =>
    object({
      accountGroupShareIndividual: [
        'accountGroupShareIndividual',
        optional(accountGroupShareFilterCriteriaSchema),
      ],
    })
);
