/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema.js';

export interface Accountnames {
  accountNameList?: string[];
}

export const accountnamesSchema: Schema<Accountnames> = object({
  accountNameList: ['accountNameList', optional(array(string()))],
});
