/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import {
  AccountGroupShareIndividual1,
  accountGroupShareIndividual1Schema,
} from './accountGroupShareIndividual1.js';

export interface AccountGroupShareObject {
  accountGroupShare?: AccountGroupShareIndividual1;
}

export const accountGroupShareObjectSchema: Schema<AccountGroupShareObject> = lazy(
  () =>
    object({
      accountGroupShare: [
        'accountGroupShare',
        optional(accountGroupShareIndividual1Schema),
      ],
    })
);
