/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import {
  AccountGroupShareObject,
  accountGroupShareObjectSchema,
} from './accountGroupShareObject.js';
import {
  Notificationarray,
  notificationarraySchema,
} from './notificationarray.js';
import {
  TriggerCategoryEnum,
  triggerCategoryEnumSchema,
} from './triggerCategoryEnum.js';

export interface AccountGroupShareUpdateTrigger {
  /** The system assigned UUID of the trigger */
  triggerId?: string;
  /** The user defined name of the trigger */
  triggerName?: string;
  /** The numeric name of the account and must include leading zeroes */
  accountName?: string;
  /** The type of trigger being created or modified */
  triggerCategory?: TriggerCategoryEnum;
  dataTrigger?: AccountGroupShareObject;
  notification?: Notificationarray;
}

export const accountGroupShareUpdateTriggerSchema: Schema<AccountGroupShareUpdateTrigger> = lazy(
  () =>
    object({
      triggerId: ['triggerId', optional(string())],
      triggerName: ['triggerName', optional(string())],
      accountName: ['accountName', optional(string())],
      triggerCategory: ['triggerCategory', optional(triggerCategoryEnumSchema)],
      dataTrigger: ['dataTrigger', optional(accountGroupShareObjectSchema)],
      notification: ['notification', optional(notificationarraySchema)],
    })
);
