/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import {
  AccountGroupShareObject,
  accountGroupShareObjectSchema,
} from './accountGroupShareObject.js';
import { ActiveEnum, activeEnumSchema } from './activeEnum.js';
import {
  Notificationarray,
  notificationarraySchema,
} from './notificationarray.js';
import {
  TriggerCategoryEnum,
  triggerCategoryEnumSchema,
} from './triggerCategoryEnum.js';

export interface AccountGroupShareCreateTriggerRequest {
  /** The user defined name of the trigger */
  triggerName?: string;
  /** The numeric name of the account and must include leading zeroes */
  accountName?: string;
  /** The type of trigger being created or modified */
  triggerCategory?: TriggerCategoryEnum;
  pricePlanTrigger?: AccountGroupShareObject;
  notification?: Notificationarray;
  /** A flag to indicate of the trigger is active, true, or not, false */
  active?: ActiveEnum;
}

export const accountGroupShareCreateTriggerRequestSchema: Schema<AccountGroupShareCreateTriggerRequest> = lazy(
  () =>
    object({
      triggerName: ['triggerName', optional(string())],
      accountName: ['accountName', optional(string())],
      triggerCategory: ['triggerCategory', optional(triggerCategoryEnumSchema)],
      pricePlanTrigger: [
        'pricePlanTrigger',
        optional(accountGroupShareObjectSchema),
      ],
      notification: ['notification', optional(notificationarraySchema)],
      active: ['active', optional(activeEnumSchema)],
    })
);
