/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema.js';
import { Engagement, engagementSchema } from './engagement.js';

/** Returns a list and details of all custom services and states defined for a specified account. */
export interface AccountStatesAndServices {
  /** The engagements associated with the account. */
  engagement: Engagement[];
}

export const accountStatesAndServicesSchema: Schema<AccountStatesAndServices> = lazy(
  () => object({ engagement: ['engagement', array(engagementSchema)] })
);
