/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import { DataTrigger, dataTriggerSchema } from './dataTrigger.js';
import {
  Notificationarray,
  notificationarraySchema,
} from './notificationarray.js';
import {
  TriggerCategoryEnum,
  triggerCategoryEnumSchema,
} from './triggerCategoryEnum.js';

export interface AccountLevelCreateTrigger {
  /** The user defined name of the trigger */
  triggerName?: string;
  /** The Enterprise Customer Profile Database ID */
  ecpdId?: string;
  /** The type of trigger being created or modified */
  triggerCategory?: TriggerCategoryEnum;
  dataTrigger?: DataTrigger;
  notification?: Notificationarray;
}

export const accountLevelCreateTriggerSchema: Schema<AccountLevelCreateTrigger> = lazy(
  () =>
    object({
      triggerName: ['triggerName', optional(string())],
      ecpdId: ['ecpdId', optional(string())],
      triggerCategory: ['triggerCategory', optional(triggerCategoryEnumSchema)],
      dataTrigger: ['dataTrigger', optional(dataTriggerSchema)],
      notification: ['notification', optional(notificationarraySchema)],
    })
);
