/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface Accountid {
  /** The numeric name of the account and must include leading zeroes */
  accountName?: string;
  mtasAccountNumber?: string;
}

export const accountidSchema: Schema<Accountid> = object({
  accountName: ['accountName', optional(string())],
  mtasAccountNumber: ['mtasAccountNumber', optional(string())],
});
