/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { DeviceLabels, deviceLabelsSchema } from './deviceLabels.js';
import { DeviceList, deviceListSchema } from './deviceList.js';

/** Maximum of 2,000 objects are allowed in the array. */
export interface AccountLabels {
  devices: DeviceList[];
  label?: DeviceLabels[];
}

export const accountLabelsSchema: Schema<AccountLabels> = lazy(() =>
  object({
    devices: ['devices', array(deviceListSchema)],
    label: ['label', optional(array(deviceLabelsSchema))],
  })
);
