/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import { DataTrigger1, dataTrigger1Schema } from './dataTrigger1.js';
import {
  Notificationarray,
  notificationarraySchema,
} from './notificationarray.js';
import {
  TriggerCategoryEnum,
  triggerCategoryEnumSchema,
} from './triggerCategoryEnum.js';

export interface AccountLevelUpdateTrigger {
  /** The system assigned UUID of the trigger */
  triggerId?: string;
  /** The user defined name of the trigger */
  triggerName?: string;
  /** The Enterprise Customer Profile Database ID */
  ecpdId?: string;
  /** The type of trigger being created or modified */
  triggerCategory?: TriggerCategoryEnum;
  dataTrigger?: DataTrigger1;
  notification?: Notificationarray;
}

export const accountLevelUpdateTriggerSchema: Schema<AccountLevelUpdateTrigger> = lazy(
  () =>
    object({
      triggerId: ['triggerId', optional(string())],
      triggerName: ['triggerName', optional(string())],
      ecpdId: ['ecpdId', optional(string())],
      triggerCategory: ['triggerCategory', optional(triggerCategoryEnumSchema)],
      dataTrigger: ['dataTrigger', optional(dataTrigger1Schema)],
      notification: ['notification', optional(notificationarraySchema)],
    })
);
