/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import {
  AccountGroupShareAction,
  accountGroupShareActionSchema,
} from './accountGroupShareAction.js';
import {
  AccountGroupShareCondition,
  accountGroupShareConditionSchema,
} from './accountGroupShareCondition.js';
import {
  AccountGroupShareFilter,
  accountGroupShareFilterSchema,
} from './accountGroupShareFilter.js';

export interface AccountGroupShareFilterCriteria {
  filterCriteria?: AccountGroupShareFilter;
  condition?: AccountGroupShareCondition;
  action?: AccountGroupShareAction;
}

export const accountGroupShareFilterCriteriaSchema: Schema<AccountGroupShareFilterCriteria> = lazy(
  () =>
    object({
      filterCriteria: [
        'filterCriteria',
        optional(accountGroupShareFilterSchema),
      ],
      condition: ['condition', optional(accountGroupShareConditionSchema)],
      action: ['action', optional(accountGroupShareActionSchema)],
    })
);
