/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AccountLevelActionEnum
 */
export enum AccountLevelActionEnum {
  Notify = 'notify',
  Suspend = 'suspend',
  ChangePricePlan = 'changePricePlan',
}

/**
 * Schema for AccountLevelActionEnum
 */
export const accountLevelActionEnumSchema: Schema<AccountLevelActionEnum> = stringEnum(
  AccountLevelActionEnum
);
