/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, lazy, object, optional, Schema } from '../schema.js';
import {
  AccountShareFilterCriteria,
  accountShareFilterCriteriaSchema,
} from './accountShareFilterCriteria.js';
import {
  ChangePlanDetails,
  changePlanDetailsSchema,
} from './changePlanDetails.js';
import {
  AccountSharePricePlanTriggerCondition,
  accountSharePricePlanTriggerConditionSchema,
} from './containers/accountSharePricePlanTriggerCondition.js';

export interface AccountSharePricePlanTrigger {
  accountShare?: AccountShareFilterCriteria;
  condition?: AccountSharePricePlanTriggerCondition;
  /** a flag to set if the trigger changes service plans, true, or not, false */
  changePlan?: boolean;
  /** The service plan code to switch to */
  changePlanDetails?: ChangePlanDetails;
}

export const accountSharePricePlanTriggerSchema: Schema<AccountSharePricePlanTrigger> = lazy(
  () =>
    object({
      accountShare: [
        'accountShare',
        optional(accountShareFilterCriteriaSchema),
      ],
      condition: [
        'condition',
        optional(accountSharePricePlanTriggerConditionSchema),
      ],
      changePlan: ['changePlan', optional(boolean())],
      changePlanDetails: [
        'changePlanDetails',
        optional(changePlanDetailsSchema),
      ],
    })
);
