/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import { Actionobject, actionobjectSchema } from './actionobject.js';

export interface ActionObjectCall {
  action?: Actionobject;
}

export const actionObjectCallSchema: Schema<ActionObjectCall> = lazy(() =>
  object({ action: ['action', optional(actionobjectSchema)] })
);
