/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, lazy, object, optional, Schema } from '../schema.js';
import {
  ChangePlanDetails,
  changePlanDetailsSchema,
} from './changePlanDetails.js';
import {
  Suspenddetailsobject,
  suspenddetailsobjectSchema,
} from './suspenddetailsobject.js';

export interface Actionobject {
  suspend?: boolean;
  suspendDetails?: Suspenddetailsobject;
  /** a flag to set if the trigger changes service plans, true, or not, false */
  changePlan?: boolean;
  /** The service plan code to switch to */
  changePlanDetails?: ChangePlanDetails;
}

export const actionobjectSchema: Schema<Actionobject> = lazy(() =>
  object({
    suspend: ['suspend', optional(boolean())],
    suspendDetails: ['suspendDetails', optional(suspenddetailsobjectSchema)],
    changePlan: ['changePlan', optional(boolean())],
    changePlanDetails: ['changePlanDetails', optional(changePlanDetailsSchema)],
  })
);
