/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ActiveEnum
 */
export enum ActiveEnum {
  True = 'true',
  False = 'false',
}

/**
 * Schema for ActiveEnum
 */
export const activeEnumSchema: Schema<ActiveEnum> = stringEnum(ActiveEnum);
