/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema } from '../schema.js';

export interface ActionId {
  /** Unique ID for originating station. */
  originatingStationId: number;
  /** Counter used to differenciate multiple DENMs from same station. */
  sequenceNumber: number;
}

export const actionIdSchema: Schema<ActionId> = object({
  originatingStationId: ['originatingStationId', number()],
  sequenceNumber: ['sequenceNumber', number()],
});
