/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import {
  AccountDeviceList,
  accountDeviceListSchema,
} from './accountDeviceList.js';
import { CustomFields, customFieldsSchema } from './customFields.js';

/** Request to add the devices. */
export interface AddDevicesRequest {
  /** The initial service state for the devices. The only valid state is “Pre-active.” */
  state: string;
  /** The devices that you want to add. */
  devicesToAdd: AccountDeviceList[];
  /** The billing account to which the devices are added. */
  accountName?: string;
  /** The names and values for any custom fields that you want set for the devices as they are added to the account. */
  customFields?: CustomFields[];
  /** The name of a device group to add the devices to. They are added to the default device group if you don't include this parameter. */
  groupName?: string;
  /** The Stock Keeping Unit (SKU) number of a 4G device type with an embedded SIM. */
  skuNumber?: string;
  smsrOid?: string;
}

export const addDevicesRequestSchema: Schema<AddDevicesRequest> = lazy(() =>
  object({
    state: ['state', string()],
    devicesToAdd: ['devicesToAdd', array(accountDeviceListSchema)],
    accountName: ['accountName', optional(string())],
    customFields: ['customFields', optional(array(customFieldsSchema))],
    groupName: ['groupName', optional(string())],
    skuNumber: ['skuNumber', optional(string())],
    smsrOid: ['smsrOid', optional(string())],
  })
);
