/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { Address, addressSchema } from './address.js';

export interface Addressquery {
  address?: Address[];
}

export const addressquerySchema: Schema<Addressquery> = lazy(() =>
  object({ address: ['address', optional(array(addressSchema))] })
);
