/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema.js';
import { AdvisoryItem, advisoryItemSchema } from './containers/advisoryItem.js';

/** DataFrame content variant carrying advisory ITIS codes. */
export interface AdvisoryContent {
  /** List of typical ITIS warnings. */
  advisory: AdvisoryItem[];
}

export const advisoryContentSchema: Schema<AdvisoryContent> = lazy(() =>
  object({ advisory: ['advisory', array(advisoryItemSchema)] })
);
