/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import { GIODeviceId, gIODeviceIdSchema } from './gIODeviceId.js';

export interface AggregateUsage {
  deviceId?: GIODeviceId;
  /** The numeric name of the account, in the format "0000123456-00001". Leading zeros must be included. */
  accountName?: string;
  /** The start date of the time period queried as "$datetime" */
  startTime?: string;
  /** The end date of the time period being queried as "$datetime" */
  endTime?: string;
}

export const aggregateUsageSchema: Schema<AggregateUsage> = lazy(() =>
  object({
    deviceId: ['deviceId', optional(gIODeviceIdSchema)],
    accountName: ['accountName', optional(string())],
    startTime: ['startTime', optional(string())],
    endTime: ['endTime', optional(string())],
  })
);
