/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import { IErrorMessage, iErrorMessageSchema } from './iErrorMessage.js';

/** Error reported by a device. */
export interface AggregateUsageError {
  /** The International Mobile Equipment Identifier of the device. */
  imei?: string;
  /** A general error message. */
  errorMessage?: string;
  /** Error message. */
  errorResponse?: IErrorMessage;
}

export const aggregateUsageErrorSchema: Schema<AggregateUsageError> = lazy(() =>
  object({
    imei: ['imei', optional(string())],
    errorMessage: ['errorMessage', optional(string())],
    errorResponse: ['errorResponse', optional(iErrorMessageSchema)],
  })
);
