/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema.js';

/** Contains usage information per device. */
export interface AggregateUsageItem {
  /** The International Mobile Equipment Identifier of the device. */
  imei?: string;
  /** Number of sessions established by the device reporting usage. */
  numberOfSessions?: number;
  /** The amount of data transferred by the device reporting usage, measured in Bytes. */
  bytesTransferred?: number;
}

export const aggregateUsageItemSchema: Schema<AggregateUsageItem> = object({
  imei: ['imei', optional(string())],
  numberOfSessions: ['numberOfSessions', optional(number())],
  bytesTransferred: ['bytesTransferred', optional(number())],
});
