/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import {
  TriggerAttributesOptions2,
  triggerAttributesOptions2Schema,
} from './containers/triggerAttributesOptions2.js';

/** Trigger details. */
export interface AnomalyTriggerValue {
  /** The system assigned name of the trigger being updated. */
  triggerId?: string;
  /** The user defined name of the trigger. */
  triggerName?: string;
  /** The user assigned name of the organization associated with the trigger. */
  organizationName?: string;
  /** This is the value to use in the request body to detect anomalous behaivior. The values in this table will only be relevant when this parameter is set to this value. */
  triggerCategory?: string;
  /** Additional details and keys for the trigger. */
  triggerAttributes?: TriggerAttributesOptions2[];
  /** Timestamp for whe the trigger was created. */
  createdAt?: string;
  /** Timestamp for the most recent time the trigger was modified. */
  modifiedAt?: string;
}

export const anomalyTriggerValueSchema: Schema<AnomalyTriggerValue> = lazy(() =>
  object({
    triggerId: ['triggerId', optional(string())],
    triggerName: ['triggerName', optional(string())],
    organizationName: ['organizationName', optional(string())],
    triggerCategory: ['triggerCategory', optional(string())],
    triggerAttributes: [
      'triggerAttributes',
      optional(array(triggerAttributesOptions2Schema)),
    ],
    createdAt: ['createdAt', optional(string())],
    modifiedAt: ['modifiedAt', optional(string())],
  })
);
