/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import {
  SensitivityParameters,
  sensitivityParametersSchema,
} from './sensitivityParameters.js';

/** Anomaly detection request. */
export interface AnomalyDetectionRequest {
  /** The name of a billing account. An account name is usually numeric, and must include any leading zeros. */
  accountName?: string;
  /** The type of request being made. anomaly is the request to activate anomaly detection. */
  requestType?: string;
  /** Details for sensitivity parameters. */
  sensitivityParameter?: SensitivityParameters;
}

export const anomalyDetectionRequestSchema: Schema<AnomalyDetectionRequest> = lazy(
  () =>
    object({
      accountName: ['accountName', optional(string())],
      requestType: ['requestType', optional(string())],
      sensitivityParameter: [
        'sensitivityParameter',
        optional(sensitivityParametersSchema),
      ],
    })
);
