/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema.js';
import { Type7Enum, type7EnumSchema } from './type7Enum.js';

/** Indicates the surface of the roadway is asphalt or tar. */
export interface AsphaltOrTar {
  /** Indicates the type of asphalt or tar. */
  type?: Type7Enum;
}

export const asphaltOrTarSchema: Schema<AsphaltOrTar> = object({
  type: ['type', optional(type7EnumSchema)],
});
