/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema.js';
import { AccountLabels, accountLabelsSchema } from './accountLabels.js';

export interface AssociateLabelRequest {
  /** The name of a billing account. An account name is usually numeric, and must include any leading zeros. */
  accountName: string;
  /** Maximum of 2,000 objects are allowed in the array. */
  labels: AccountLabels;
}

export const associateLabelRequestSchema: Schema<AssociateLabelRequest> = lazy(
  () =>
    object({
      accountName: ['accountName', string()],
      labels: ['labels', accountLabelsSchema],
    })
);
