/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';
import {
  ReportStatusEnum,
  reportStatusEnumSchema,
} from './reportStatusEnum.js';

export interface AsynchronousLocationRequestResult {
  /** The transaction ID of the report. */
  txid?: string;
  /** Status of the report. */
  status?: ReportStatusEnum;
  /** Estimated number of minutes required to complete the report. */
  estimatedDuration?: string;
}

export const asynchronousLocationRequestResultSchema: Schema<AsynchronousLocationRequestResult> = object(
  {
    txid: ['txid', optional(string())],
    status: ['status', optional(reportStatusEnumSchema)],
    estimatedDuration: ['estimatedDuration', optional(string())],
  }
);
