/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, string } from '../schema.js';

/** A successful request returns the request ID (UUID) and the current status. */
export interface AsynchronousRequestResultforplanner {
  /** The unique ID of a request. This is a UUID value. */
  requestId?: string | null;
}

export const asynchronousRequestResultforplannerSchema: Schema<AsynchronousRequestResultforplanner> = object(
  { requestId: ['requestId', optional(nullable(string()))] }
);
