/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface AuthSubRestErrorResponseforplanner {
  code?: string;
  message?: string;
  description?: string;
}

export const authSubRestErrorResponseforplannerSchema: Schema<AuthSubRestErrorResponseforplanner> = object(
  {
    code: ['code', optional(string())],
    message: ['message', optional(string())],
    description: ['description', optional(string())],
  }
);
