/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AwarenessDistanceEnum
 */
export enum AwarenessDistanceEnum {
  LessThan50m = 'lessThan50m',
  LessThan100m = 'lessThan100m',
  LessThan200m = 'lessThan200m',
  LessThan500m = 'lessThan500m',
  LessThan1000m = 'lessThan1000m',
  LessThan5km = 'lessThan5km',
  LessThan10km = 'lessThan10km',
  Over10km = 'over10km',
}

/**
 * Schema for AwarenessDistanceEnum
 */
export const awarenessDistanceEnumSchema: Schema<AwarenessDistanceEnum> = stringEnum(
  AwarenessDistanceEnum
);
