/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import { BillingCycle, billingCycleSchema } from './billingCycle.js';
import { DeviceList, deviceListSchema } from './deviceList.js';
import { LabelsList, labelsListSchema } from './labelsList.js';

/** Information required to associate a usage segmentation label with a device to retrieve billing. */
export interface BilledusageListRequest {
  accountName: string;
  labels?: LabelsList;
  deviceIds?: DeviceList[];
  billingCycle?: BillingCycle;
}

export const billedusageListRequestSchema: Schema<BilledusageListRequest> = lazy(
  () =>
    object({
      accountName: ['accountName', string()],
      labels: ['labels', optional(labelsListSchema)],
      deviceIds: ['deviceIds', optional(array(deviceListSchema))],
      billingCycle: ['billingCycle', optional(billingCycleSchema)],
    })
);
