/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema.js';
import {
  DeviceServiceRequest,
  deviceServiceRequestSchema,
} from './deviceServiceRequest.js';

/** Account number and list of devices. */
export interface BullseyeServiceRequest {
  /** A list of devices. */
  deviceList: DeviceServiceRequest[];
  /** The numeric ID of the account and must include leading zeroes. This value is indentical to `accountName`. */
  accountNumber: string;
}

export const bullseyeServiceRequestSchema: Schema<BullseyeServiceRequest> = lazy(
  () =>
    object({
      deviceList: ['deviceList', array(deviceServiceRequestSchema)],
      accountNumber: ['accountNumber', string()],
    })
);
