/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface CallbackCreated {
  /** The numeric name of the account and must include leading zeroes. */
  accountName: string;
  /** The name of the callback service, which identifies the type and format of messages that will be sent to the registered URL. */
  name: string;
  /** The address of the callback listening service where the ThingSpace Platform will send callback messages for the service type. */
  url?: string;
}

export const callbackCreatedSchema: Schema<CallbackCreated> = object({
  accountName: ['accountName', string()],
  name: ['name', string()],
  url: ['url', optional(string())],
});
