/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import {
  AllowanceThreshold,
  allowanceThresholdSchema,
} from './allowanceThreshold.js';

export interface Carriercode1 {
  carrierCode?: string;
  percentage?: AllowanceThreshold;
}

export const carriercode1Schema: Schema<Carriercode1> = lazy(() =>
  object({
    carrierCode: ['carrierCode', optional(string())],
    percentage: ['percentage', optional(allowanceThresholdSchema)],
  })
);
