/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface Cellphonenumber {
  number?: string;
  carrier?: string;
}

export const cellphonenumberSchema: Schema<Cellphonenumber> = object({
  number: ['number', optional(string())],
  carrier: ['carrier', optional(string())],
});
