/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

/** Structure for the credentials required to connect to the ETX MQTT Message Exchange. */
export interface Certificate {
  /** The string containing the certificate */
  certPem: string;
  /** The string containing the private key */
  keyPem: string;
  /** The string containing the CA certificate */
  caPem: string;
  /** The string describing the expiration timestamp of the certificate */
  expirationTime: string;
}

export const certificateSchema: Schema<Certificate> = object({
  certPem: ['cert.pem', string()],
  keyPem: ['key.pem', string()],
  caPem: ['ca.pem', string()],
  expirationTime: ['ExpirationTime', string()],
});
