/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema.js';
import { Activate, activateSchema } from './activate.js';
import { PWNDeviceList, pWNDeviceListSchema } from './pWNDeviceList.js';

export interface ChangePWNDeviceStateActivateRequest {
  accountName: string;
  deviceList: PWNDeviceList[];
  activate: Activate;
}

export const changePWNDeviceStateActivateRequestSchema: Schema<ChangePWNDeviceStateActivateRequest> = lazy(
  () =>
    object({
      accountName: ['accountName', string()],
      deviceList: ['deviceList', array(pWNDeviceListSchema)],
      activate: ['activate', activateSchema],
    })
);
