/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** The service plan code to switch to */
export interface ChangePlanDetails {
  toCarrierServicePlanCode?: string;
}

export const changePlanDetailsSchema: Schema<ChangePlanDetails> = object({
  toCarrierServicePlanCode: ['toCarrierServicePlanCode', optional(string())],
});
