/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ClientSubtypeEnum
 */
export enum ClientSubtypeEnum {
  PassengerCar = 'PassengerCar',
  Truck = 'Truck',
  Bus = 'Bus',
  EmergencyVehicle = 'EmergencyVehicle',
  SchoolBus = 'SchoolBus',
  MaintenanceVehicle = 'MaintenanceVehicle',
  Pedestrian = 'Pedestrian',
  Bicycle = 'Bicycle',
  Scooter = 'Scooter',
  Motorcycle = 'Motorcycle',
  RoadSideUnit = 'RoadSideUnit',
  Camera = 'Camera',
  Lidar = 'Lidar',
  Radar = 'Radar',
  InductiveLoop = 'InductiveLoop',
  MagneticSensor = 'MagneticSensor',
  Platform = 'Platform',
  Application = 'Application',
  NA = 'NA',
}

/**
 * Schema for ClientSubtypeEnum
 */
export const clientSubtypeEnumSchema: Schema<ClientSubtypeEnum> = stringEnum(
  ClientSubtypeEnum
);
