/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ComparitorEnum
 */
export enum ComparitorEnum {
  Gt = 'gt',
  Lt = 'lt',
  Eq = 'eq',
}

/**
 * Schema for ComparitorEnum
 */
export const comparitorEnumSchema: Schema<ComparitorEnum> = stringEnum(
  ComparitorEnum
);
