/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ConditionActionEnum
 */
export enum ConditionActionEnum {
  Notify = 'notify',
  Suspend = 'suspend',
  ChangePricePlan = 'changePricePlan',
}

/**
 * Schema for ConditionActionEnum
 */
export const conditionActionEnumSchema: Schema<ConditionActionEnum> = stringEnum(
  ConditionActionEnum
);
