/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { Keyschunk2, keyschunk2Schema } from './keyschunk2.js';

export interface Condition {
  condition?: Keyschunk2[];
}

export const conditionSchema: Schema<Condition> = lazy(() =>
  object({ condition: ['condition', optional(array(keyschunk2Schema))] })
);
