/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema.js';

/** The ConfigurationList's item that contains the configuration identifier, name, description and the active flag. */
export interface ConfigurationListItem {
  /** The generated ID (UUID v4) for the configuration. It has to be used when asking for changing any of the configuration parameters. */
  id: string;
  /** Name of the configuration. */
  name?: string;
  /** Description of the configuration. */
  description?: string;
  isActive: boolean;
}

export const configurationListItemSchema: Schema<ConfigurationListItem> = object(
  {
    id: ['id', string()],
    name: ['name', optional(string())],
    description: ['description', optional(string())],
    isActive: ['isActive', boolean()],
  }
);
