/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema.js';
import { Geolocation, geolocationSchema } from './geolocation.js';
import { NetworkTypeEnum, networkTypeEnumSchema } from './networkTypeEnum.js';

/** Request for /clients/connection. It requires the device ID acquired in the registration request call; the geolocation of the device at the time of the request; and the network type (Verizon or non-Verizon). The system uses this information to determine with MQTT endpoint the device should use to connect the ETX Message Exchange. */
export interface ConnectionRequest {
  /**
   * The generated ID (UUID v4) for the device. It can be used as:
   *   - the MQTT Client ID when connecting to the Message Exchange system
   *   - a parameter when asking for the connection endpoint
   *   - a parameter when finishing the device registration
   *   - a parameter when unregistering the device
   */
  deviceID: string;
  /** Geolocation of the device at the time of the connection request in GPS coordinates. */
  geolocation: Geolocation;
  /**
   * The type of the device's network connection at the time of the request. If the device is on the Verizon cellular network it should use the "VZ" value otherwise the "non-VZ" value.
   * Devices on the Verizon network can directly access the ETX Message Exchange on the MEC (Mobile Edge Compute server)
   */
  networkType: NetworkTypeEnum;
}

export const connectionRequestSchema: Schema<ConnectionRequest> = lazy(() =>
  object({
    deviceID: ['DeviceID', string()],
    geolocation: ['Geolocation', geolocationSchema],
    networkType: ['NetworkType', networkTypeEnumSchema],
  })
);
