/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import { CustomFields, customFieldsSchema } from './customFields.js';

/** Network connection events for a device during a specified time period. */
export interface ConnectionEvent {
  /** The attributes that describe the connection event. */
  connectionEventAttributes?: CustomFields[];
  /** Currently not used. */
  extendedAttributes?: CustomFields[];
  /** The date and time when the connection event occured. */
  occurredAt?: string;
}

export const connectionEventSchema: Schema<ConnectionEvent> = lazy(() =>
  object({
    connectionEventAttributes: [
      'connectionEventAttributes',
      optional(array(customFieldsSchema)),
    ],
    extendedAttributes: [
      'extendedAttributes',
      optional(array(customFieldsSchema)),
    ],
    occurredAt: ['occurredAt', optional(string())],
  })
);
