/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, boolean, lazy, object, optional, Schema } from '../schema.js';
import { ConnectionEvent, connectionEventSchema } from './connectionEvent.js';

/** Response containing the connection history. It is a list of Network Connection Events for a device. */
export interface ConnectionHistoryResult {
  /** Device connection events, sorted by the occurredAt timestamp, oldest first. */
  connectionHistory?: ConnectionEvent[];
  /** False for a status 200 response.True for a status 202 response, indicating that there is more data to be retrieved. Send another request, adjusting the earliest value in the request based on the occuredAt value for the last device in the current response. */
  hasMoreData?: boolean;
}

export const connectionHistoryResultSchema: Schema<ConnectionHistoryResult> = lazy(
  () =>
    object({
      connectionHistory: [
        'connectionHistory',
        optional(array(connectionEventSchema)),
      ],
      hasMoreData: ['hasMoreData', optional(boolean())],
    })
);
