/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema.js';
import {
  FrictionInformation,
  frictionInformationSchema,
} from './frictionInformation.js';

export interface ContentFrictionInfo {
  frictionInfo: FrictionInformation;
}

export const contentFrictionInfoSchema: Schema<ContentFrictionInfo> = lazy(() =>
  object({ frictionInfo: ['frictionInfo', frictionInformationSchema] })
);
