/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import { ActiveEnum, activeEnumSchema } from './activeEnum.js';
import {
  Notificationarray,
  notificationarraySchema,
} from './notificationarray.js';
import {
  PricePlanTrigger,
  pricePlanTriggerSchema,
} from './pricePlanTrigger.js';
import {
  TriggerCategoryEnum,
  triggerCategoryEnumSchema,
} from './triggerCategoryEnum.js';

export interface Createtriggerchunk {
  /** The user defined name of the trigger */
  triggerName?: string;
  /** The Enterprise Customer Profile Database ID */
  ecpdId?: string;
  /** The type of trigger being created or modified */
  triggerCategory?: TriggerCategoryEnum;
  pricePlanTrigger?: PricePlanTrigger;
  notification?: Notificationarray;
  /** A flag to indicate of the trigger is active, true, or not, false */
  active?: ActiveEnum;
}

export const createtriggerchunkSchema: Schema<Createtriggerchunk> = lazy(() =>
  object({
    triggerName: ['triggerName', optional(string())],
    ecpdId: ['ecpdId', optional(string())],
    triggerCategory: ['triggerCategory', optional(triggerCategoryEnumSchema)],
    pricePlanTrigger: ['pricePlanTrigger', optional(pricePlanTriggerSchema)],
    notification: ['notification', optional(notificationarraySchema)],
    active: ['active', optional(activeEnumSchema)],
  })
);
