/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import {
  AnomalyTriggerRequest,
  anomalyTriggerRequestSchema,
} from './anomalyTriggerRequest.js';
import {
  DataTriggerRequest,
  dataTriggerRequestSchema,
} from './dataTriggerRequest.js';
import {
  SessionTriggerRequest,
  sessionTriggerRequestSchema,
} from './sessionTriggerRequest.js';
import {
  SMSTriggerRequest,
  sMSTriggerRequestSchema,
} from './sMSTriggerRequest.js';

export interface CreateTriggerRequest {
  accountName?: string;
  /** The details of the UsageAnomaly trigger. */
  anomalyTriggerRequest?: AnomalyTriggerRequest;
  dataTriggerRequest?: DataTriggerRequest;
  groupName?: string;
  name?: string;
  sessionTriggerRequest?: SessionTriggerRequest;
  smsTriggerRequest?: SMSTriggerRequest;
  triggerCategory?: string;
  triggerCycle?: string;
}

export const createTriggerRequestSchema: Schema<CreateTriggerRequest> = lazy(
  () =>
    object({
      accountName: ['accountName', optional(string())],
      anomalyTriggerRequest: [
        'anomalyTriggerRequest',
        optional(anomalyTriggerRequestSchema),
      ],
      dataTriggerRequest: [
        'dataTriggerRequest',
        optional(dataTriggerRequestSchema),
      ],
      groupName: ['groupName', optional(string())],
      name: ['name', optional(string())],
      sessionTriggerRequest: [
        'sessionTriggerRequest',
        optional(sessionTriggerRequestSchema),
      ],
      smsTriggerRequest: [
        'smsTriggerRequest',
        optional(sMSTriggerRequestSchema),
      ],
      triggerCategory: ['triggerCategory', optional(string())],
      triggerCycle: ['triggerCycle', optional(string())],
    })
);
