/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import {
  FieldsHttpHeaders,
  fieldsHttpHeadersSchema,
} from './fieldsHttpHeaders.js';

export interface CreateTargetRequestFields {
  httpheaders?: FieldsHttpHeaders;
  /** List of device types. */
  devicetypes?: string[];
}

export const createTargetRequestFieldsSchema: Schema<CreateTargetRequestFields> = lazy(
  () =>
    object({
      httpheaders: ['httpheaders', optional(fieldsHttpHeadersSchema)],
      devicetypes: ['devicetypes', optional(array(string()))],
    })
);
