/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema.js';
import {
  DeviceCredentialRequestItem,
  deviceCredentialRequestItemSchema,
} from './deviceCredentialRequestItem.js';

export interface CredentialsRequest {
  /** Enterprise Customer Profile ID */
  eCPD: string;
  /** Billing Account Number */
  accountNumber: string;
  /** List of devices (1-50 items) */
  items: DeviceCredentialRequestItem[];
}

export const credentialsRequestSchema: Schema<CredentialsRequest> = lazy(() =>
  object({
    eCPD: ['ECPD', string()],
    accountNumber: ['accountNumber', string()],
    items: ['items', array(deviceCredentialRequestItemSchema)],
  })
);
