/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import {
  ExtendedAttribute,
  extendedAttributeSchema,
} from './extendedAttribute.js';

export interface DailyUsageHistory {
  /** the total data usage recorded in Bytes */
  bytesUsed?: string;
  extendedAttributes?: ExtendedAttribute[];
  servicePlan?: string;
  /** The total number of SMS messages from and to the device */
  smsUsed?: string;
  /** Where the collected data is being gathered from */
  source?: string;
  /** Timestamp of when the retrieved record was completed ($datetime) */
  timestamp?: string;
}

export const dailyUsageHistorySchema: Schema<DailyUsageHistory> = lazy(() =>
  object({
    bytesUsed: ['bytesUsed', optional(string())],
    extendedAttributes: [
      'extendedAttributes',
      optional(array(extendedAttributeSchema)),
    ],
    servicePlan: ['servicePlan', optional(string())],
    smsUsed: ['smsUsed', optional(string())],
    source: ['source', optional(string())],
    timestamp: ['timestamp', optional(string())],
  })
);
