/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, optional, Schema } from '../schema.js';
import {
  AccountLevelObject,
  accountLevelObjectSchema,
} from './accountLevelObject.js';
import { Actionobject, actionobjectSchema } from './actionobject.js';
import {
  AllowanceThreshold,
  allowanceThresholdSchema,
} from './allowanceThreshold.js';
import { ComparitorEnum, comparitorEnumSchema } from './comparitorEnum.js';
import {
  ConditionTypeEnum,
  conditionTypeEnumSchema,
} from './conditionTypeEnum.js';
import {
  DeviceGroupFilterCriteria,
  deviceGroupFilterCriteriaSchema,
} from './deviceGroupFilterCriteria.js';
import {
  RulesCycleTypeEnum,
  rulesCycleTypeEnumSchema,
} from './rulesCycleTypeEnum.js';
import {
  ThresholdUnitEnum,
  thresholdUnitEnumSchema,
} from './thresholdUnitEnum.js';

export interface DataTrigger4 {
  accountLevel?: AccountLevelObject;
  deviceGroup?: DeviceGroupFilterCriteria;
  /** The condition type being monitored */
  conditionType?: ConditionTypeEnum;
  /** The boolean of the comparison. `gt` is Greater Than, `lt` is Less Than and `eq` is Equal To */
  comparitor?: ComparitorEnum;
  /** The threshold value the trigger monitors for */
  threshold?: number;
  /** The units of the threshold. This can be KB, Kilobits, MB, Megabits, or GB, Gigabits */
  thresholdUnit?: ThresholdUnitEnum;
  /** The interval to monitor for the threshold. This can be Daily, Weekly or Monthly */
  cycleType?: RulesCycleTypeEnum;
  allowanceThreshold?: AllowanceThreshold;
  action?: Actionobject;
}

export const dataTrigger4Schema: Schema<DataTrigger4> = lazy(() =>
  object({
    accountLevel: ['accountLevel', optional(accountLevelObjectSchema)],
    deviceGroup: ['deviceGroup', optional(deviceGroupFilterCriteriaSchema)],
    conditionType: ['conditionType', optional(conditionTypeEnumSchema)],
    comparitor: ['comparitor', optional(comparitorEnumSchema)],
    threshold: ['threshold', optional(number())],
    thresholdUnit: ['thresholdUnit', optional(thresholdUnitEnumSchema)],
    cycleType: ['cycleType', optional(rulesCycleTypeEnumSchema)],
    allowanceThreshold: [
      'allowanceThreshold',
      optional(allowanceThresholdSchema),
    ],
    action: ['action', optional(actionobjectSchema)],
  })
);
