/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import {
  DeactivateDeviceListIds,
  deactivateDeviceListIdsSchema,
} from './containers/deactivateDeviceListIds.js';

export interface DeactivateDeviceList {
  ids?: DeactivateDeviceListIds[];
}

export const deactivateDeviceListSchema: Schema<DeactivateDeviceList> = lazy(
  () => object({ ids: ['ids', optional(array(deactivateDeviceListIdsSchema))] })
);
