/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import {
  DeactivateDeviceList,
  deactivateDeviceListSchema,
} from './deactivateDeviceList.js';

export interface DeactivateDeviceProfileRequest {
  accountName: string;
  reasonCode: string;
  devices?: DeactivateDeviceList[];
  carrierName?: string;
  etfWaiver?: boolean;
  checkFallbackProfile?: boolean;
}

export const deactivateDeviceProfileRequestSchema: Schema<DeactivateDeviceProfileRequest> = lazy(
  () =>
    object({
      accountName: ['accountName', string()],
      reasonCode: ['reasonCode', string()],
      devices: ['devices', optional(array(deactivateDeviceListSchema))],
      carrierName: ['carrierName', optional(string())],
      etfWaiver: ['etfWaiver', optional(boolean())],
      checkFallbackProfile: ['checkFallbackProfile', optional(boolean())],
    })
);
