/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import {
  DeleteDevicesResultDeviceIds,
  deleteDevicesResultDeviceIdsSchema,
} from './containers/deleteDevicesResultDeviceIds.js';

/** Response for a request made to delete a device. */
export interface DeleteDevicesResult {
  /** One object per device to be deleted. Each object must contain a kind and id element identifying the device. */
  deviceIds?: DeleteDevicesResultDeviceIds;
  /** “Success” if the device was deleted, or “Failed” if there was a problem. */
  status?: string;
  /** Not present if status=Success. One of these messages if status=Failed:The device is not in deactivate state.The user does not have access to delete the device. */
  message?: string;
}

export const deleteDevicesResultSchema: Schema<DeleteDevicesResult> = lazy(() =>
  object({
    deviceIds: ['deviceIds', optional(deleteDevicesResultDeviceIdsSchema)],
    status: ['status', optional(string())],
    message: ['message', optional(string())],
  })
);
