/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import { Management, managementSchema } from './management.js';
import { Situation, situationSchema } from './situation.js';

/** The payload of the DENM PDU. */
export interface DenmPayload {
  /** This represent the management container describing the meta information about the event, such as the detection time, the event's location, the source of the event, and the notification distance. */
  management: Management;
  /** This represents the situation container describing the event and the reliability of the detection source. */
  situation?: Situation;
}

export const denmPayloadSchema: Schema<DenmPayload> = lazy(() =>
  object({
    management: ['management', managementSchema],
    situation: ['situation', optional(situationSchema)],
  })
);
