/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema.js';
import { Ice, iceSchema } from './ice.js';

export interface DescriptionOfRoadSurfaceIce {
  /** Indicates the surface of the roadway is ice. */
  ice: Ice;
}

export const descriptionOfRoadSurfaceIceSchema: Schema<DescriptionOfRoadSurfaceIce> = lazy(
  () => object({ ice: ['ice', iceSchema] })
);
