/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema.js';
import { Gravel, gravelSchema } from './gravel.js';

export interface DescriptionOfRoadSurfaceGravel {
  /** Indicates the surface of the roadway is gravel. */
  gravel: Gravel;
}

export const descriptionOfRoadSurfaceGravelSchema: Schema<DescriptionOfRoadSurfaceGravel> = lazy(
  () => object({ gravel: ['gravel', gravelSchema] })
);
