/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema.js';
import { Cinders, cindersSchema } from './cinders.js';

export interface DescriptionOfRoadSurfaceCinders {
  /** Indicates the surface of the roadway is cinders. */
  cinders: Cinders;
}

export const descriptionOfRoadSurfaceCindersSchema: Schema<DescriptionOfRoadSurfaceCinders> = lazy(
  () => object({ cinders: ['cinders', cindersSchema] })
);
