/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema.js';
import { PortlandCement, portlandCementSchema } from './portlandCement.js';

export interface DescriptionOfRoadSurfacePortlandCement {
  /** Indicates the surface of the roadway is portland cement. */
  portlandCement: PortlandCement;
}

export const descriptionOfRoadSurfacePortlandCementSchema: Schema<DescriptionOfRoadSurfacePortlandCement> = lazy(
  () => object({ portlandCement: ['portlandCement', portlandCementSchema] })
);
