/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { DeviceId, deviceIdSchema } from './deviceId.js';

export interface DeviceList {
  deviceIds?: DeviceId[];
}

export const deviceListSchema: Schema<DeviceList> = lazy(() =>
  object({ deviceIds: ['deviceIds', optional(array(deviceIdSchema))] })
);
