/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema.js';
import { PWNDeviceId, pWNDeviceIdSchema } from './pWNDeviceId.js';

export interface DeviceListIP {
  deviceIds: PWNDeviceId[];
  ipaddress: string;
}

export const deviceListIPSchema: Schema<DeviceListIP> = lazy(() =>
  object({
    deviceIds: ['deviceIds', array(pWNDeviceIdSchema)],
    ipaddress: ['ipAddress', string()],
  })
);
