/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import {
  DeviceGroupFilter,
  deviceGroupFilterSchema,
} from './deviceGroupFilter.js';

export interface DeviceGroupFilterCriteria {
  filterCriteria?: DeviceGroupFilter;
}

export const deviceGroupFilterCriteriaSchema: Schema<DeviceGroupFilterCriteria> = lazy(
  () =>
    object({
      filterCriteria: ['filterCriteria', optional(deviceGroupFilterSchema)],
    })
);
