/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import {
  DeviceIdforplanner,
  deviceIdforplannerSchema,
} from './deviceIdforplanner.js';

export interface DeviceStatusItemforplanner {
  deviceIds?: DeviceIdforplanner[] | null;
  status?: string | null;
  reason?: string | null;
}

export const deviceStatusItemforplannerSchema: Schema<DeviceStatusItemforplanner> = lazy(
  () =>
    object({
      deviceIds: [
        'deviceIds',
        optional(nullable(array(deviceIdforplannerSchema))),
      ],
      status: ['status', optional(nullable(string()))],
      reason: ['reason', optional(nullable(string()))],
    })
);
