/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import {
  DeviceList2Ids,
  deviceList2IdsSchema,
} from './containers/deviceList2Ids.js';

export interface DeviceList2 {
  ids?: DeviceList2Ids[];
}

export const deviceList2Schema: Schema<DeviceList2> = lazy(() =>
  object({ ids: ['ids', optional(array(deviceList2IdsSchema))] })
);
