/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import {
  DeviceIdforplanner,
  deviceIdforplannerSchema,
} from './deviceIdforplanner.js';
import {
  PrivateNetworkApns,
  privateNetworkApnsSchema,
} from './privateNetworkApns.js';

export interface DeviceListforplanner {
  deviceIds?: DeviceIdforplanner[] | null;
  privateNetworkApns?: PrivateNetworkApns[] | null;
  /** A IPv4 address */
  ipaddress?: string | null;
  /** The activation code value. */
  activationCode?: string | null;
}

export const deviceListforplannerSchema: Schema<DeviceListforplanner> = lazy(
  () =>
    object({
      deviceIds: [
        'deviceIds',
        optional(nullable(array(deviceIdforplannerSchema))),
      ],
      privateNetworkApns: [
        'privateNetworkApns',
        optional(nullable(array(privateNetworkApnsSchema))),
      ],
      ipaddress: ['ipAddress', optional(nullable(string()))],
      activationCode: ['activationCode', optional(nullable(string()))],
    })
);
