/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema.js';
import { DeviceId, deviceIdSchema } from './deviceId.js';

/** Request to return the provisioning history of a specified device during a specified time period. */
export interface DeviceProvisioningHistoryListRequest {
  /** An identifier for a single device. */
  deviceId: DeviceId;
  /** The earliest date and time for which you want provisioning data. */
  earliest: string;
  /** The last date and time for which you want provisioning data. */
  latest: string;
}

export const deviceProvisioningHistoryListRequestSchema: Schema<DeviceProvisioningHistoryListRequest> = lazy(
  () =>
    object({
      deviceId: ['deviceId', deviceIdSchema],
      earliest: ['earliest', string()],
      latest: ['latest', string()],
    })
);
