/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import { DeviceId, deviceIdSchema } from './deviceId.js';
import { Label, labelSchema } from './label.js';

/** Request to return the daily network data usage of a single device during a specified time period. */
export interface DeviceUsageListRequest {
  /** The earliest date for which you want usage data. */
  earliest: string;
  /** The last date for which you want usage data. */
  latest: string;
  /** An identifier for a single device. */
  deviceId?: DeviceId;
  label?: Label;
}

export const deviceUsageListRequestSchema: Schema<DeviceUsageListRequest> = lazy(
  () =>
    object({
      earliest: ['earliest', string()],
      latest: ['latest', string()],
      deviceId: ['deviceId', optional(deviceIdSchema)],
      label: ['label', optional(labelSchema)],
    })
);
