/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface DeviceCredentialRequestItem {
  /** 15-digit alphanumeric identifier */
  imei: string;
}

export const deviceCredentialRequestItemSchema: Schema<DeviceCredentialRequestItem> = object(
  { imei: ['imei', string()] }
);
