/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema.js';
import {
  HplBullseyeEnable,
  hplBullseyeEnableSchema,
} from './hplBullseyeEnable.js';

/** Device information. */
export interface DeviceServiceRequest {
  /** The International Mobile Equipment Identifier of the device. */
  imei: string;
  /** A flag that shows if Hyper Precise is enabled (true) or disabled (false). */
  bullseyeEnable: HplBullseyeEnable;
}

export const deviceServiceRequestSchema: Schema<DeviceServiceRequest> = lazy(
  () =>
    object({
      imei: ['imei', string()],
      bullseyeEnable: ['BullseyeEnable', hplBullseyeEnableSchema],
    })
);
