/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import { ApiResponseCode, apiResponseCodeSchema } from './apiResponseCode.js';
import {
  HplBullseyeEnable,
  hplBullseyeEnableSchema,
} from './hplBullseyeEnable.js';

/** Device service information. */
export interface DeviceServiceInformation {
  /** ResponseCode and/or a message indicating success or failure of the request. */
  responseType?: ApiResponseCode;
  /** The International Mobile Equipment Identifier of the device. */
  imei: string;
  /** A flag that shows if Hyper Precise is enabled (true) or disabled (false). */
  bullseyeEnable: HplBullseyeEnable;
}

export const deviceServiceInformationSchema: Schema<DeviceServiceInformation> = lazy(
  () =>
    object({
      responseType: ['responseType', optional(apiResponseCodeSchema)],
      imei: ['imei', string()],
      bullseyeEnable: ['BullseyeEnable', hplBullseyeEnableSchema],
    })
);
