/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import {
  DeviceGroupFilterCriteria,
  deviceGroupFilterCriteriaSchema,
} from './deviceGroupFilterCriteria.js';

export interface DeviceGroupObject {
  deviceGroup?: DeviceGroupFilterCriteria;
}

export const deviceGroupObjectSchema: Schema<DeviceGroupObject> = lazy(() =>
  object({
    deviceGroup: ['deviceGroup', optional(deviceGroupFilterCriteriaSchema)],
  })
);
