/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, lazy, object, optional, Schema } from '../schema.js';
import {
  Devicepropertyselection,
  devicepropertyselectionSchema,
} from './devicepropertyselection.js';

export interface Devicepropertyfilter {
  selection?: Devicepropertyselection;
  querytotalcount?: boolean;
}

export const devicepropertyfilterSchema: Schema<Devicepropertyfilter> = lazy(
  () =>
    object({
      selection: ['$selection', optional(devicepropertyselectionSchema)],
      querytotalcount: ['$querytotalcount', optional(boolean())],
    })
);
