/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for DistributionTypesEnum
 */
export enum DistributionTypesEnum {
  Targeted = 'Targeted',
  Broadcast = 'Broadcast',
}

/**
 * Schema for DistributionTypesEnum
 */
export const distributionTypesEnumSchema: Schema<DistributionTypesEnum> = stringEnum(
  DistributionTypesEnum
);
