/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import {
  DtoDeviceActionSetConfiguration1,
  dtoDeviceActionSetConfiguration1Schema,
} from './dtoDeviceActionSetConfiguration1.js';
import {
  DtoDeviceResourceIdentifier1,
  dtoDeviceResourceIdentifier1Schema,
} from './dtoDeviceResourceIdentifier1.js';

export interface DmV1DevicesActionsSetRequest {
  /** The numeric account name, which must include leading zeros */
  accountname?: string;
  configuration?: DtoDeviceActionSetConfiguration1;
  /** Device identifiers, one or more are required */
  resourceidentifier?: DtoDeviceResourceIdentifier1;
}

export const dmV1DevicesActionsSetRequestSchema: Schema<DmV1DevicesActionsSetRequest> = lazy(
  () =>
    object({
      accountname: ['accountname', optional(string())],
      configuration: [
        'configuration',
        optional(dtoDeviceActionSetConfiguration1Schema),
      ],
      resourceidentifier: [
        'resourceidentifier',
        optional(dtoDeviceResourceIdentifier1Schema),
      ],
    })
);
