/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import {
  BulkUpdateSmartalert,
  bulkUpdateSmartalertSchema,
} from './bulkUpdateSmartalert.js';
import {
  TheIDresourceandDeviceID,
  theIDresourceandDeviceIDSchema,
} from './theIDresourceandDeviceID.js';

export interface DtoBulkUpdate {
  /** The numeric account name, which must include leading zeros */
  accountname?: string;
  resourceidentifiers?: TheIDresourceandDeviceID[];
  smartalert?: BulkUpdateSmartalert;
}

export const dtoBulkUpdateSchema: Schema<DtoBulkUpdate> = lazy(() =>
  object({
    accountname: ['accountname', optional(string())],
    resourceidentifiers: [
      'resourceidentifiers',
      optional(array(theIDresourceandDeviceIDSchema)),
    ],
    smartalert: ['smartalert', optional(bulkUpdateSmartalertSchema)],
  })
);
