/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import { DtoProfile, dtoProfileSchema } from './dtoProfile.js';
import {
  DtoResourceidentifier,
  dtoResourceidentifierSchema,
} from './dtoResourceidentifier.js';

export interface DtoConfigurationProfilePath {
  /** The numeric account name, which must include leading zeros */
  accountName?: string;
  resourceidentifier?: DtoResourceidentifier;
  profile?: DtoProfile;
}

export const dtoConfigurationProfilePathSchema: Schema<DtoConfigurationProfilePath> = lazy(
  () =>
    object({
      accountName: ['accountName', optional(string())],
      resourceidentifier: [
        'resourceidentifier',
        optional(dtoResourceidentifierSchema),
      ],
      profile: ['profile', optional(dtoProfileSchema)],
    })
);
