/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import { DtoUserDTO, dtoUserDTOSchema } from './dtoUserDTO.js';

export interface DtoCreateUserRequest {
  /** The numeric account name, which must include leading zeros */
  accountname?: string;
  user?: DtoUserDTO;
}

export const dtoCreateUserRequestSchema: Schema<DtoCreateUserRequest> = lazy(
  () =>
    object({
      accountname: ['accountname', optional(string())],
      user: ['user', optional(dtoUserDTOSchema)],
    })
);
