/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import { DtoProfile, dtoProfileSchema } from './dtoProfile.js';

export interface DtoConfigurationProfile {
  /** The numeric account name, which must include leading zeros */
  accountname?: string;
  profiles?: DtoProfile[];
}

export const dtoConfigurationProfileSchema: Schema<DtoConfigurationProfile> = lazy(
  () =>
    object({
      accountname: ['accountname', optional(string())],
      profiles: ['profiles', optional(array(dtoProfileSchema))],
    })
);
