/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import {
  ActionResultwithDeviceConfig,
  actionResultwithDeviceConfigSchema,
} from './actionResultwithDeviceConfig.js';

export interface DtoDeviceActionSetResponse {
  actionresult?: ActionResultwithDeviceConfig[];
}

export const dtoDeviceActionSetResponseSchema: Schema<DtoDeviceActionSetResponse> = lazy(
  () =>
    object({
      actionresult: [
        'actionresult',
        optional(array(actionResultwithDeviceConfigSchema)),
      ],
    })
);
