/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import {
  SensorInsightsBLE,
  sensorInsightsBLESchema,
} from './sensorInsightsBLE.js';

export interface DtoDeviceConfig {
  /** Property objects for Bluetooth Low-Energy (BLE) devices */
  ble?: SensorInsightsBLE;
}

export const dtoDeviceConfigSchema: Schema<DtoDeviceConfig> = lazy(() =>
  object({ ble: ['ble', optional(sensorInsightsBLESchema)] })
);
