/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import { DtoDeviceConfig, dtoDeviceConfigSchema } from './dtoDeviceConfig.js';

export interface DtoDeviceActionSetConfiguration {
  deviceConfig?: DtoDeviceConfig;
}

export const dtoDeviceActionSetConfigurationSchema: Schema<DtoDeviceActionSetConfiguration> = lazy(
  () =>
    object({ deviceConfig: ['deviceConfig', optional(dtoDeviceConfigSchema)] })
);
