/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema.js';

export interface DtoDeleteNotificationGroupRequest {
  /** The numeric account name, which must include leading zeros */
  accountname?: string;
  force?: boolean;
  /** UUID of the user record, assigned at creation */
  id?: string;
}

export const dtoDeleteNotificationGroupRequestSchema: Schema<DtoDeleteNotificationGroupRequest> = object(
  {
    accountname: ['accountname', optional(string())],
    force: ['force', optional(boolean())],
    id: ['id', optional(string())],
  }
);
