/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** Fields to return needed by search */
export interface DtoFields {
  additionalProp1?: string;
  additionalProp2?: string;
  additionalProp3?: string;
}

export const dtoFieldsSchema: Schema<DtoFields> = object({
  additionalProp1: ['additionalProp1', optional(string())],
  additionalProp2: ['additionalProp2', optional(string())],
  additionalProp3: ['additionalProp3', optional(string())],
});
