/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import {
  DtoHealthScoreMetric,
  dtoHealthScoreMetricSchema,
} from './dtoHealthScoreMetric.js';

/** The values measured are for the network */
export interface DtoGetNetworkHealthScoreResponse {
  networksummary?: DtoHealthScoreMetric[];
  overallsummary?: DtoHealthScoreMetric[];
}

export const dtoGetNetworkHealthScoreResponseSchema: Schema<DtoGetNetworkHealthScoreResponse> = lazy(
  () =>
    object({
      networksummary: [
        'networksummary',
        optional(array(dtoHealthScoreMetricSchema)),
      ],
      overallsummary: [
        'overallsummary',
        optional(array(dtoHealthScoreMetricSchema)),
      ],
    })
);
