/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface DtoHealthScoreMetric {
  /** The type of measurement and can be overallscore, networkscore, gatewayscore, sensorscore, networkstatus, averagesignalstrength or networkavailabilitylast30 */
  metrictype?: string;
  /** the value of the `metrictype` as a percentage */
  metricvalue?: string;
}

export const dtoHealthScoreMetricSchema: Schema<DtoHealthScoreMetric> = object({
  metrictype: ['metrictype', optional(string())],
  metricvalue: ['metricvalue', optional(string())],
});
