/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import {
  DtoDeviceResourceIdentifier,
  dtoDeviceResourceIdentifierSchema,
} from './dtoDeviceResourceIdentifier.js';
import { DtoFilter, dtoFilterSchema } from './dtoFilter.js';

export interface DtoListSensorDevicesRequest {
  /** The numeric account name, which must include leading zeros */
  accountname?: string;
  filter?: DtoFilter;
  /** Device identifiers, one or more are required */
  resourceidentifier?: DtoDeviceResourceIdentifier;
}

export const dtoListSensorDevicesRequestSchema: Schema<DtoListSensorDevicesRequest> = lazy(
  () =>
    object({
      accountname: ['accountname', optional(string())],
      filter: ['filter', optional(dtoFilterSchema)],
      resourceidentifier: [
        'resourceidentifier',
        optional(dtoDeviceResourceIdentifierSchema),
      ],
    })
);
