/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import { ResourceEvent, resourceEventSchema } from './resourceEvent.js';

export interface DtoLastReportedTimeResponse {
  event?: ResourceEvent;
  timestamp?: string;
}

export const dtoLastReportedTimeResponseSchema: Schema<DtoLastReportedTimeResponse> = lazy(
  () =>
    object({
      event: ['event', optional(resourceEventSchema)],
      timestamp: ['timestamp', optional(string())],
    })
);
