/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import { DtoFilter, dtoFilterSchema } from './dtoFilter.js';

export interface DtoListNotificationGroupRequest {
  /** The numeric account name, which must include leading zeros */
  accountname?: string;
  filter?: DtoFilter;
}

export const dtoListNotificationGroupRequestSchema: Schema<DtoListNotificationGroupRequest> = lazy(
  () =>
    object({
      accountname: ['accountname', optional(string())],
      filter: ['filter', optional(dtoFilterSchema)],
    })
);
