/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import { Payload, payloadSchema } from './payload.js';

export interface DtoOnBoardSensorRequest {
  /** The numeric account name, which must include leading zeros */
  accountname?: string;
  payload?: Payload;
}

export const dtoOnBoardSensorRequestSchema: Schema<DtoOnBoardSensorRequest> = lazy(
  () =>
    object({
      accountname: ['accountname', optional(string())],
      payload: ['payload', optional(payloadSchema)],
    })
);
