/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import {
  DtoResourceidentifier,
  dtoResourceidentifierSchema,
} from './dtoResourceidentifier.js';
import { ResourceRule, resourceRuleSchema } from './resourceRule.js';

export interface DtoOverwriteRuleRequest {
  /** The numeric account name, which must include leading zeros */
  accountname?: string;
  resourceidentifier?: DtoResourceidentifier;
  rule?: ResourceRule;
}

export const dtoOverwriteRuleRequestSchema: Schema<DtoOverwriteRuleRequest> = lazy(
  () =>
    object({
      accountname: ['accountname', optional(string())],
      resourceidentifier: [
        'resourceidentifier',
        optional(dtoResourceidentifierSchema),
      ],
      rule: ['rule', optional(resourceRuleSchema)],
    })
);
