/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** The EUI64 address of the device being removed */
export interface DtoOffBoardSensor {
  /** the IEEE EUI64 address space used to identify a device. It is supplied by the device manufacturer */
  deveui?: string;
}

export const dtoOffBoardSensorSchema: Schema<DtoOffBoardSensor> = object({
  deveui: ['deveui', optional(string())],
});
