/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import {
  DtoDeviceResourceIdentifier,
  dtoDeviceResourceIdentifierSchema,
} from './dtoDeviceResourceIdentifier.js';
import { ResourceDevice, resourceDeviceSchema } from './resourceDevice.js';

export interface DtoPatchDeviceRequest {
  /** The numeric account name, which must include leading zeros */
  accountname?: string;
  device?: ResourceDevice;
  /** Device identifiers, one or more are required */
  resourceidentifier?: DtoDeviceResourceIdentifier;
}

export const dtoPatchDeviceRequestSchema: Schema<DtoPatchDeviceRequest> = lazy(
  () =>
    object({
      accountname: ['accountname', optional(string())],
      device: ['device', optional(resourceDeviceSchema)],
      resourceidentifier: [
        'resourceidentifier',
        optional(dtoDeviceResourceIdentifierSchema),
      ],
    })
);
