/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import {
  DtoResourceidentifier,
  dtoResourceidentifierSchema,
} from './dtoResourceidentifier.js';
import { UserSmartAlert, userSmartAlertSchema } from './userSmartAlert.js';

export interface DtoPatchSmartAlertRequest {
  /** The numeric account name, which must include leading zeros */
  accountname?: string;
  resourceidentifier?: DtoResourceidentifier;
  smartalert?: UserSmartAlert;
}

export const dtoPatchSmartAlertRequestSchema: Schema<DtoPatchSmartAlertRequest> = lazy(
  () =>
    object({
      accountname: ['accountname', optional(string())],
      resourceidentifier: [
        'resourceidentifier',
        optional(dtoResourceidentifierSchema),
      ],
      smartalert: ['smartalert', optional(userSmartAlertSchema)],
    })
);
