/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema.js';

export interface DtoQueryMetrics {
  /** The number of days in a recent period to query */
  days?: number;
}

export const dtoQueryMetricsSchema: Schema<DtoQueryMetrics> = object({
  days: ['days', optional(number())],
});
