/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface DtoResourceidentifier {
  /** UUID of the user record, assigned at creation */
  id?: string;
}

export const dtoResourceidentifierSchema: Schema<DtoResourceidentifier> = object(
  { id: ['id', optional(string())] }
);
