/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, boolean, lazy, object, optional, Schema } from '../schema.js';
import {
  DtoSensorBoardingEvent,
  dtoSensorBoardingEventSchema,
} from './dtoSensorBoardingEvent.js';

export interface DtoSensorOffBoardingStatusResponse {
  events?: DtoSensorBoardingEvent[];
  isstillregistered?: boolean;
}

export const dtoSensorOffBoardingStatusResponseSchema: Schema<DtoSensorOffBoardingStatusResponse> = lazy(
  () =>
    object({
      events: ['events', optional(array(dtoSensorBoardingEventSchema))],
      isstillregistered: ['isstillregistered', optional(boolean())],
    })
);
