/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import {
  Gatewayidentifier,
  gatewayidentifierSchema,
} from './gatewayidentifier.js';
import { Onboarding, onboardingSchema } from './onboarding.js';

export interface DtoSensorOnBoardStatusRequest {
  /** The numeric account name, which must include leading zeros */
  accountname?: string;
  gatewayidentifier?: Gatewayidentifier;
  onboarding?: Onboarding;
}

export const dtoSensorOnBoardStatusRequestSchema: Schema<DtoSensorOnBoardStatusRequest> = lazy(
  () =>
    object({
      accountname: ['accountname', optional(string())],
      gatewayidentifier: [
        'gatewayidentifier',
        optional(gatewayidentifierSchema),
      ],
      onboarding: ['onboarding', optional(onboardingSchema)],
    })
);
