/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import {
  Gatewayidentifier,
  gatewayidentifierSchema,
} from './gatewayidentifier.js';
import { Offboarding, offboardingSchema } from './offboarding.js';

export interface DtoSensorOffBoardStatusRequest {
  /** The numeric account name, which must include leading zeros */
  accountname?: string;
  gatewayidentifier?: Gatewayidentifier;
  offboarding?: Offboarding;
}

export const dtoSensorOffBoardStatusRequestSchema: Schema<DtoSensorOffBoardStatusRequest> = lazy(
  () =>
    object({
      accountname: ['accountname', optional(string())],
      gatewayidentifier: [
        'gatewayidentifier',
        optional(gatewayidentifierSchema),
      ],
      offboarding: ['offboarding', optional(offboardingSchema)],
    })
);
