/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import {
  DtoNotificationGroupRequestEntity,
  dtoNotificationGroupRequestEntitySchema,
} from './dtoNotificationGroupRequestEntity.js';

export interface DtoUpdateNotificationGroupRequest {
  /** The numeric account name, which must include leading zeros */
  accountname?: string;
  group: DtoNotificationGroupRequestEntity;
  /** UUID of the user record, assigned at creation */
  id?: string;
  userids?: string[];
}

export const dtoUpdateNotificationGroupRequestSchema: Schema<DtoUpdateNotificationGroupRequest> = lazy(
  () =>
    object({
      accountname: ['accountname', optional(string())],
      group: ['group', dtoNotificationGroupRequestEntitySchema],
      id: ['id', optional(string())],
      userids: ['userids', optional(array(string()))],
    })
);
