/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema } from '../schema.js';

/** Cause code wrapper for emergency vehicle approaching events. */
export interface EmergencyVehicleApproachingCauseCode {
  /**
   * The value shall be set to:
   * - 0 `unavailable`                   - in case further detailed information on the emergency vehicle approaching event is unavailable,
   * - 1 `emergencyVehicleApproaching`   - in case an operating emergency vehicle is approaching,
   * - 2 `prioritizedVehicleApproaching` - in case a prioritized vehicle is approaching,
   * - 3-255                             - reserved for future usage.
   */
  emergencyVehicleApproaching95: number;
}

export const emergencyVehicleApproachingCauseCodeSchema: Schema<EmergencyVehicleApproachingCauseCode> = object(
  { emergencyVehicleApproaching95: ['emergencyVehicleApproaching95', number()] }
);
