/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema.js';

export interface EnablePromoExp1 {
  enablePromoExp?: boolean;
}

export const enablePromoExp1Schema: Schema<EnablePromoExp1> = object({
  enablePromoExp: ['enablePromoExp', optional(boolean())],
});
