/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema.js';

export interface EnablePromoExp {
  key?: string;
  value?: boolean;
}

export const enablePromoExpSchema: Schema<EnablePromoExp> = object({
  key: ['key', optional(string())],
  value: ['value', optional(boolean())],
});
