/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import { AccountService, accountServiceSchema } from './accountService.js';

/** The engagements associated with the account. */
export interface Engagement {
  /** The engagement ID. */
  engagementId?: string;
  /** The charging group name. */
  chargingGroup?: string;
  /** The services associated with the account. */
  services?: AccountService[];
}

export const engagementSchema: Schema<Engagement> = lazy(() =>
  object({
    engagementId: ['engagementId', optional(string())],
    chargingGroup: ['chargingGroup', optional(string())],
    services: ['services', optional(array(accountServiceSchema))],
  })
);
