/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import { ESIMDeviceList, eSIMDeviceListSchema } from './eSIMDeviceList.js';

export interface ESIMProfileRequest {
  devices?: ESIMDeviceList[];
  carrierName?: string;
  accountName?: string;
  servicePlan?: string;
  mdnZipCode?: string;
}

export const eSIMProfileRequestSchema: Schema<ESIMProfileRequest> = lazy(() =>
  object({
    devices: ['devices', optional(array(eSIMDeviceListSchema))],
    carrierName: ['carrierName', optional(string())],
    accountName: ['accountName', optional(string())],
    servicePlan: ['servicePlan', optional(string())],
    mdnZipCode: ['mdnZipCode', optional(string())],
  })
);
