/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import {
  ESIMDeviceListDeviceIds,
  eSIMDeviceListDeviceIdsSchema,
} from './containers/eSIMDeviceListDeviceIds.js';

export interface ESIMDeviceList {
  deviceIds?: ESIMDeviceListDeviceIds[];
}

export const eSIMDeviceListSchema: Schema<ESIMDeviceList> = lazy(() =>
  object({
    deviceIds: ['deviceIds', optional(array(eSIMDeviceListDeviceIdsSchema))],
  })
);
