/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import {
  ESIMGlobalDeviceListDeviceFilter,
  eSIMGlobalDeviceListDeviceFilterSchema,
} from './containers/eSIMGlobalDeviceListDeviceFilter.js';
import {
  ProfileStatusFilterEnum,
  profileStatusFilterEnumSchema,
} from './profileStatusFilterEnum.js';
import {
  ProvisioningStatusFilterEnum,
  provisioningStatusFilterEnumSchema,
} from './provisioningStatusFilterEnum.js';

export interface ESIMGlobalDeviceList {
  /** The numeric name of the account. */
  accountName?: string;
  /** The last status of the device as a list filter. */
  provisioningStatusFilter?: ProvisioningStatusFilterEnum;
  /** The last status of the device's profile as a filter. */
  profileStatusFilter?: ProfileStatusFilterEnum;
  /** The cellular service provider. */
  carrierNameFilter?: string;
  /** An array of device identifiers to filter the list. */
  deviceFilter?: ESIMGlobalDeviceListDeviceFilter[];
}

export const eSIMGlobalDeviceListSchema: Schema<ESIMGlobalDeviceList> = lazy(
  () =>
    object({
      accountName: ['accountName', optional(string())],
      provisioningStatusFilter: [
        'provisioningStatusFilter',
        optional(provisioningStatusFilterEnumSchema),
      ],
      profileStatusFilter: [
        'profileStatusFilter',
        optional(profileStatusFilterEnumSchema),
      ],
      carrierNameFilter: ['carrierNameFilter', optional(string())],
      deviceFilter: [
        'deviceFilter',
        optional(array(eSIMGlobalDeviceListDeviceFilterSchema)),
      ],
    })
);
