/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** Lookup object for identifying an ETX client. One of the following IDs is required: DeviceID, IMEI, ICCID, or IMSI. If more than one ID is provided, the API will use the first ID found in the following order: DeviceID, IMEI, ICCID, IMSI. */
export interface ETXClientIDLookup {
  /**
   * The generated ID (UUID v4) for the device. It can be used as:
   *   - the MQTT Client ID when connecting to the Message Exchange system
   *   - a parameter when asking for the connection endpoint
   *   - a parameter when finishing the device registration
   *   - a parameter when unregistering the device
   */
  deviceID?: string;
  /** The IMEI number of the device. */
  iMEI?: string;
  /** The ICCID number of the device. */
  iCCID?: string;
  /** The IMSI number of the device. */
  iMSI?: string;
}

export const eTXClientIDLookupSchema: Schema<ETXClientIDLookup> = object({
  deviceID: ['DeviceID', optional(string())],
  iMEI: ['IMEI', optional(string())],
  iCCID: ['ICCID', optional(string())],
  iMSI: ['IMSI', optional(string())],
});
