/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for EtxClientTypeEnum
 */
export enum EtxClientTypeEnum {
  Vehicle = 'Vehicle',
  VulnerableRoadUser = 'VulnerableRoadUser',
  TrafficLightController = 'TrafficLightController',
  InfrastructureSensor = 'InfrastructureSensor',
  OnboardSensor = 'OnboardSensor',
  Software = 'Software',
}

/**
 * Schema for EtxClientTypeEnum
 */
export const etxClientTypeEnumSchema: Schema<EtxClientTypeEnum> = stringEnum(
  EtxClientTypeEnum
);
