/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ETXExpectedTypeEnum
 */
export enum ETXExpectedTypeEnum {
  BASE64 = 'BASE64',
  JSON = 'JSON',
}

/**
 * Schema for ETXExpectedTypeEnum
 */
export const eTXExpectedTypeEnumSchema: Schema<ETXExpectedTypeEnum> = stringEnum(
  ETXExpectedTypeEnum
);
