/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ETXMAPMessageGeofenceGeometryEnum
 */
export enum ETXMAPMessageGeofenceGeometryEnum {
  Polygon = 'Polygon',
}

/**
 * Schema for ETXMAPMessageGeofenceGeometryEnum
 */
export const eTXMAPMessageGeofenceGeometryEnumSchema: Schema<ETXMAPMessageGeofenceGeometryEnum> = stringEnum(
  ETXMAPMessageGeofenceGeometryEnum
);
