/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, unknown } from '../schema.js';

/** JSON representation of a J2735/ETSI MapData message for ingestion. The value field must contain a valid MAP message body conforming to the SAE J2735 or ETSI TS 103 301 standard. */
export interface ETXMAPDataIngestRequest {
  /** SAE J2735 DSRCmsgID for the MAP message type. */
  messageId: number;
  /** The decoded MAP message body containing intersection and lane data. */
  value?: unknown;
  /** Issue revision number of the MAP message. */
  msgIssueRevision?: number;
}

export const eTXMAPDataIngestRequestSchema: Schema<ETXMAPDataIngestRequest> = object(
  {
    messageId: ['messageId', number()],
    value: ['value', optional(unknown())],
    msgIssueRevision: ['msgIssueRevision', optional(number())],
  }
);
