/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import {
  CauseCodeChoice,
  causeCodeChoiceSchema,
} from './containers/causeCodeChoice.js';

/** The type of event including direct and sub cause. */
export interface EventType {
  /** The main cause of a detected event. Each entry is of a different type and represents the sub cause code. */
  ccAndScc?: CauseCodeChoice;
}

export const eventTypeSchema: Schema<EventType> = lazy(() =>
  object({ ccAndScc: ['ccAndScc', optional(causeCodeChoiceSchema)] })
);
