/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, Schema } from '../schema.js';
import { Altitude, altitudeSchema } from './altitude.js';
import {
  PosConfidenceEllipse,
  posConfidenceEllipseSchema,
} from './posConfidenceEllipse.js';

export interface EventPosition {
  /** Latitude of the event location in microdegrees (900000001 shall be used when unavailable). */
  latitude: number;
  /** Longitude of the event location in microdegrees (1800000001 shall be used when unavailable). */
  longitude: number;
  positionConfidenceEllipse: PosConfidenceEllipse;
  altitude: Altitude;
}

export const eventPositionSchema: Schema<EventPosition> = lazy(() =>
  object({
    latitude: ['latitude', number()],
    longitude: ['longitude', number()],
    positionConfidenceEllipse: [
      'positionConfidenceEllipse',
      posConfidenceEllipseSchema,
    ],
    altitude: ['altitude', altitudeSchema],
  })
);
