/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema.js';
import {
  TextPhraseOrITIS,
  textPhraseOrITISSchema,
} from './containers/textPhraseOrITIS.js';

/** DataFrame content variant carrying exit service information. */
export interface ExitServiceContent {
  /** List of roadside available services. */
  exitService: TextPhraseOrITIS[];
}

export const exitServiceContentSchema: Schema<ExitServiceContent> = lazy(() =>
  object({ exitService: ['exitService', array(textPhraseOrITISSchema)] })
);
