/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import {
  FallBackDevices,
  fallBackDevicesSchema,
} from './containers/fallBackDevices.js';

export interface FallBack {
  /** An array containing the `deviceId` array. */
  devices?: FallBackDevices[];
  /** The numeric name of the account, in the format "0000123456-00001". Leading zeros must be included. */
  accountName?: string;
}

export const fallBackSchema: Schema<FallBack> = lazy(() =>
  object({
    devices: ['devices', optional(array(fallBackDevicesSchema))],
    accountName: ['accountName', optional(string())],
  })
);
