/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, unknown } from '../schema.js';
import { Geometry, geometrySchema } from './containers/geometry.js';
import { Type1Enum, type1EnumSchema } from './type1Enum.js';

export interface FeatureItem {
  type: Type1Enum;
  geometry: Geometry;
  /** Properties object for a GeoJSON Feature (no additional properties allowed). */
  properties?: unknown;
}

export const featureItemSchema: Schema<FeatureItem> = lazy(() =>
  object({
    type: ['type', type1EnumSchema],
    geometry: ['geometry', geometrySchema],
    properties: ['properties', optional(unknown())],
  })
);
