/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import { MConfiguration, mConfigurationSchema } from './mConfiguration.js';

/** List of fields affected by the event. */
export interface Fields {
  /** List of the field names and values to set. */
  configuration?: MConfiguration;
}

export const fieldsSchema: Schema<Fields> = lazy(() =>
  object({ configuration: ['configuration', optional(mConfigurationSchema)] })
);
