/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import {
  ReadySimServicePlan,
  readySimServicePlanSchema,
} from './readySimServicePlan.js';

export interface Filtercriteria {
  filterCriteria?: ReadySimServicePlan[];
}

export const filtercriteriaSchema: Schema<Filtercriteria> = lazy(() =>
  object({
    filterCriteria: [
      'filterCriteria',
      optional(array(readySimServicePlanSchema)),
    ],
  })
);
