/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import { FilterCriteria1, filterCriteria1Schema } from './filterCriteria1.js';

export interface FiltercriteriaObjectCall {
  filterCriteria?: FilterCriteria1;
}

export const filtercriteriaObjectCallSchema: Schema<FiltercriteriaObjectCall> = lazy(
  () =>
    object({
      filterCriteria: ['filterCriteria', optional(filterCriteria1Schema)],
    })
);
