/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import {
  FindDeviceByPropertyResponse,
  findDeviceByPropertyResponseSchema,
} from './findDeviceByPropertyResponse.js';

/** A success response includes an array of all matching devices. Each device includes the full device resource definition. */
export interface FindDeviceByPropertyResponseList {
  deviceProperty?: FindDeviceByPropertyResponse[];
}

export const findDeviceByPropertyResponseListSchema: Schema<FindDeviceByPropertyResponseList> = lazy(
  () =>
    object({
      deviceProperty: [
        'DeviceProperty',
        optional(array(findDeviceByPropertyResponseSchema)),
      ],
    })
);
