/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

/** Message ID referencing a further information link (ATIS message). */
export interface FurtherInfoMsgId {
  /**
   * Links to ATIS message. A link to any other incident information data that may be available in the normal ATIS incident description or other messages.
   * The value is described as a 4-character hexadecimal string.
   */
  furtherInfoID: string;
}

export const furtherInfoMsgIdSchema: Schema<FurtherInfoMsgId> = object({
  furtherInfoID: ['furtherInfoID', string()],
});
