/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface GenerateResponseItemCredential {
  username?: string;
  password?: string;
}

export const generateResponseItemCredentialSchema: Schema<GenerateResponseItemCredential> = object(
  {
    username: ['username', optional(string())],
    password: ['password', optional(string())],
  }
);
