/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema.js';
import {
  TextPhraseOrITIS,
  textPhraseOrITISSchema,
} from './containers/textPhraseOrITIS.js';

/** DataFrame content variant carrying generic sign information. */
export interface GenericSignContent {
  /** List of MUTCD signs and directions. */
  genericSign: TextPhraseOrITIS[];
}

export const genericSignContentSchema: Schema<GenericSignContent> = lazy(() =>
  object({ genericSign: ['genericSign', array(textPhraseOrITISSchema)] })
);
