/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema.js';
import { FeatureItem, featureItemSchema } from './featureItem.js';
import { TypeEnum, typeEnumSchema } from './typeEnum.js';

/** The GeoJSON representation of geofence. Geofence supports the following geometry types: LineString, Polygon, MultiLineString, and MultiPolygon. The system only supports a single Feature in the FeatureCollection, so only one Line, Polygon, MultiLine or MultiPolygon can be defined within one Geofencing configuration. */
export interface GeoFence {
  type: TypeEnum;
  features: FeatureItem[];
}

export const geoFenceSchema: Schema<GeoFence> = lazy(() =>
  object({
    type: ['type', typeEnumSchema],
    features: ['features', array(featureItemSchema)],
  })
);
