/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { Message4, message4Schema } from './containers/message4.js';
import { GeoFence, geoFenceSchema } from './geoFence.js';
import {
  MessageStandardEnum,
  messageStandardEnumSchema,
} from './messageStandardEnum.js';

/** Request for /api/v1/application/configurations/geofence PUT endpoint. It requires at least one of vendorId, name, description, geofence, messages and isActive fields to be populated. */
export interface GeoFenceConfigurationUpdateRequest {
  /** Name of the configuration. */
  name?: string;
  /** Description of the configuration. */
  description?: string;
  /** The GeoJSON representation of geofence. Geofence supports the following geometry types: LineString, Polygon, MultiLineString, and MultiPolygon. The system only supports a single Feature in the FeatureCollection, so only one Line, Polygon, MultiLine or MultiPolygon can be defined within one Geofencing configuration. */
  geoFence?: GeoFence;
  /**
   * Select which V2X messaging standard will be used for the message generation. The following options are supported:
   *   - "etsi": The message will be generated using the ETSI (European) standard (e.g. DENM).
   *   - "sae": The message will be generated using the SAE J2735 (North American) standard (e.g. RSA, TIM).
   *   - if not sent while POST, defaults to "sae"
   *   - mandatory to send "etsi" standard here, if ETSI messages are being sent in config
   */
  messageStandard?: MessageStandardEnum;
  /** List of predefined messages that belongs to the geofence. These are the messages that are sent out by the system when the Trigger Condition for the message is met. */
  messages?: Message4[];
  isActive?: boolean;
}

export const geoFenceConfigurationUpdateRequestSchema: Schema<GeoFenceConfigurationUpdateRequest> = lazy(
  () =>
    object({
      name: ['name', optional(string())],
      description: ['description', optional(string())],
      geoFence: ['geoFence', optional(geoFenceSchema)],
      messageStandard: ['messageStandard', optional(messageStandardEnumSchema)],
      messages: ['messages', optional(array(message4Schema))],
      isActive: ['isActive', optional(boolean())],
    })
);
