/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema.js';
import { OffsetSystem, offsetSystemSchema } from './offsetSystem.js';

/** This data frame can describe a complex path of arbitrary size using node offset method (LL offsets). */
export interface GeographicalPathDescription {
  /** The OffsetSystem data frame selects a sequence of node offsets described in the Lat-Long offset method. */
  path: OffsetSystem;
}

export const geographicalPathDescriptionSchema: Schema<GeographicalPathDescription> = lazy(
  () => object({ path: ['path', offsetSystemSchema] })
);
