/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema } from '../schema.js';

/** Geolocation of the device at the time of the connection request in GPS coordinates. */
export interface Geolocation {
  /** The GPS Latitude value */
  latitude: number;
  /** The GPS Longitude value */
  longitude: number;
}

export const geolocationSchema: Schema<Geolocation> = object({
  latitude: ['Latitude', number()],
  longitude: ['Longitude', number()],
});
