/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  nullable,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import {
  IPPoolforplanner,
  iPPoolforplannerSchema,
} from './iPPoolforplanner.js';
import {
  ServicePlanResponseforplanner,
  servicePlanResponseforplannerSchema,
} from './servicePlanResponseforplanner.js';

export interface GetAccountInformationResponseforplanner {
  accountName?: string;
  /** The numeric name of the account, including leading zeros. */
  accountNumber?: string | null;
  /** The list of carrier names with profiles. */
  carriers?: string[];
  /** a list of features associated with the resident profiles. */
  features?: string[];
  ipPools?: IPPoolforplanner[];
  /** A flag indicating if provisioning is allowed (true) or provisioning is locked (false). */
  isProvisioningAllowed?: boolean;
  /** The user assigned organization name. */
  organizationName?: string;
  /** A list of service plans associated with the resident profiles. */
  servicePlans?: ServicePlanResponseforplanner[];
}

export const getAccountInformationResponseforplannerSchema: Schema<GetAccountInformationResponseforplanner> = lazy(
  () =>
    object({
      accountName: ['accountName', optional(string())],
      accountNumber: ['accountNumber', optional(nullable(string()))],
      carriers: ['carriers', optional(array(string()))],
      features: ['features', optional(array(string()))],
      ipPools: ['ipPools', optional(array(iPPoolforplannerSchema))],
      isProvisioningAllowed: ['isProvisioningAllowed', optional(boolean())],
      organizationName: ['organizationName', optional(string())],
      servicePlans: [
        'servicePlans',
        optional(array(servicePlanResponseforplannerSchema)),
      ],
    })
);
