/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import {
  DeviceStatusItemforplanner,
  deviceStatusItemforplannerSchema,
} from './deviceStatusItemforplanner.js';

export interface GetDeviceStatusesResponseforplanner {
  /** The numeric name of the account, including leading zeros. */
  accountNumber?: string | null;
  requestId?: string | null;
  deviceStatusList?: DeviceStatusItemforplanner[] | null;
}

export const getDeviceStatusesResponseforplannerSchema: Schema<GetDeviceStatusesResponseforplanner> = lazy(
  () =>
    object({
      accountNumber: ['accountNumber', optional(nullable(string()))],
      requestId: ['requestId', optional(nullable(string()))],
      deviceStatusList: [
        'deviceStatusList',
        optional(nullable(array(deviceStatusItemforplannerSchema))),
      ],
    })
);
