/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema.js';
import { Coordinates, coordinatesSchema } from './coordinates.js';

/** Get network conditions. */
export interface GetNetworkConditionsRequest {
  /** Account name. */
  accountName: string;
  /** Type of location detail. */
  locationType: string;
  /** Coordinates information. */
  coordinates: Coordinates;
}

export const getNetworkConditionsRequestSchema: Schema<GetNetworkConditionsRequest> = lazy(
  () =>
    object({
      accountName: ['accountName', string()],
      locationType: ['locationType', string()],
      coordinates: ['coordinates', coordinatesSchema],
    })
);
