/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import {
  GetTriggerResponse,
  getTriggerResponseSchema,
} from './getTriggerResponse.js';

export interface GetTriggerResponseList {
  triggers?: GetTriggerResponse[];
}

export const getTriggerResponseListSchema: Schema<GetTriggerResponseList> = lazy(
  () =>
    object({
      triggers: ['triggers', optional(array(getTriggerResponseSchema))],
    })
);
