/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema.js';
import { Locations, locationsSchema } from './locations.js';
import {
  NetworkTypeObject,
  networkTypeObjectSchema,
} from './networkTypeObject.js';

/** Get wireless coverage FWA. */
export interface GetWirelessCoverageRequestFWA {
  /** Account name. */
  accountName: string;
  /** Type of request made. FWA for address qualification and NW for Nationwide coverage. */
  requestType: string;
  /** Type of location detail. */
  locationType: string;
  locations: Locations;
  networkTypesList: NetworkTypeObject[];
}

export const getWirelessCoverageRequestFWASchema: Schema<GetWirelessCoverageRequestFWA> = lazy(
  () =>
    object({
      accountName: ['accountName', string()],
      requestType: ['requestType', string()],
      locationType: ['locationType', string()],
      locations: ['locations', locationsSchema],
      networkTypesList: ['networkTypesList', array(networkTypeObjectSchema)],
    })
);
