/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { GIODeviceList, gIODeviceListSchema } from './gIODeviceList.js';

export interface GIODeactivateDeviceProfileRequest {
  devices?: GIODeviceList[];
  accountName?: string;
  servicePlan?: string;
  etfWaiver?: boolean;
  reasonCode?: string;
}

export const gIODeactivateDeviceProfileRequestSchema: Schema<GIODeactivateDeviceProfileRequest> = lazy(
  () =>
    object({
      devices: ['devices', optional(array(gIODeviceListSchema))],
      accountName: ['accountName', optional(string())],
      servicePlan: ['servicePlan', optional(string())],
      etfWaiver: ['etfWaiver', optional(boolean())],
      reasonCode: ['reasonCode', optional(string())],
    })
);
