/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { GIODeviceId, gIODeviceIdSchema } from './gIODeviceId.js';

export interface GIODeviceList {
  deviceIds?: GIODeviceId[];
}

export const gIODeviceListSchema: Schema<GIODeviceList> = lazy(() =>
  object({ deviceIds: ['deviceIds', optional(array(gIODeviceIdSchema))] })
);
