/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import { GIODeviceList, gIODeviceListSchema } from './gIODeviceList.js';

export interface GIOProfileRequest {
  devices: GIODeviceList[];
  accountName: string;
  /** The Subscription Manager Secure Router Object ID, used for remote SIM provisioning. SMSR securely routes the download and management of eSIM profiles. */
  smrsOid?: string;
  mdnZipCode?: string;
  servicePlan?: string;
}

export const gIOProfileRequestSchema: Schema<GIOProfileRequest> = lazy(() =>
  object({
    devices: ['devices', array(gIODeviceListSchema)],
    accountName: ['accountName', string()],
    smrsOid: ['smrsOid', optional(string())],
    mdnZipCode: ['mdnZipCode', optional(string())],
    servicePlan: ['servicePlan', optional(string())],
  })
);
