/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema.js';
import { Type9Enum, type9EnumSchema } from './type9Enum.js';

/** Indicates the surface of the roadway is grass. */
export interface Grass {
  /** Indicates the surface of the roadway is grass with low speed limit. */
  type?: Type9Enum;
}

export const grassSchema: Schema<Grass> = object({
  type: ['type', optional(type9EnumSchema)],
});
