/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema.js';
import { Type8Enum, type8EnumSchema } from './type8Enum.js';

/** Indicates the surface of the roadway is gravel. */
export interface Gravel {
  /** Indicates the type of gravel. */
  type?: Type8Enum;
}

export const gravelSchema: Schema<Gravel> = object({
  type: ['type', optional(type8EnumSchema)],
});
