/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, nullable, object, Schema } from '../schema.js';
import { HeadingRange, headingRangeSchema } from './headingRange.js';

/**
 * Heading limitation provides minimum and maximum value for road user heading in unit of degrees. If the road user's heading value is between the given minimum and maximum value and the TriggerConditions are also met the message will be sent out.
 * The heading minimum value can be bigger than the maximum value as negative number are not supported. For example, the +/- 10 degrees around the north (0 degrees) can be defined as 350 (min) to 10 (max) degrees.
 */
export interface HeadingItem {
  /** Acceptable heading range for road users in degrees. */
  heading: HeadingRange | null;
}

export const headingItemSchema: Schema<HeadingItem> = lazy(() =>
  object({ heading: ['heading', nullable(headingRangeSchema)] })
);
