/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema } from '../schema.js';
import { MessageIdEnum, messageIdEnumSchema } from './messageIdEnum.js';
import {
  ProtocolVersionEnum,
  protocolVersionEnumSchema,
} from './protocolVersionEnum.js';

/** The header of the DENM PDU. */
export interface Header {
  /** The protocol version of the DENM. */
  protocolVersion: ProtocolVersionEnum;
  /** The type of ITIS message (typically 1 for DENM). */
  messageId: MessageIdEnum;
  /** The station identifier of the ITS-S. */
  stationId: number;
}

export const headerSchema: Schema<Header> = object({
  protocolVersion: ['protocolVersion', protocolVersionEnumSchema],
  messageId: ['messageId', messageIdEnumSchema],
  stationId: ['stationId', number()],
});
