/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import { Device, deviceSchema } from './device.js';
import {
  HistorySearchFilterAttributes,
  historySearchFilterAttributesSchema,
} from './historySearchFilterAttributes.js';

/** The selected device and attributes for which a request should retrieve data. */
export interface HistorySearchFilter {
  /** Account name identifier. */
  accountName: string;
  /** Identifies a particular IoT device. */
  device: Device;
  /** Streaming RF parameters for which you want to retrieve history data. */
  attributes?: HistorySearchFilterAttributes;
}

export const historySearchFilterSchema: Schema<HistorySearchFilter> = lazy(() =>
  object({
    accountName: ['accountName', string()],
    device: ['device', deviceSchema],
    attributes: ['attributes', optional(historySearchFilterAttributesSchema)],
  })
);
