/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema.js';
import {
  AttributeIdentifierEnum,
  attributeIdentifierEnumSchema,
} from './attributeIdentifierEnum.js';

/** Streaming RF parameters for which you want to retrieve history data. */
export interface HistorySearchFilterAttributes {
  /** Attribute identifier. */
  name?: AttributeIdentifierEnum;
}

export const historySearchFilterAttributesSchema: Schema<HistorySearchFilterAttributes> = object(
  { name: ['name', optional(attributeIdentifierEnumSchema)] }
);
