/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import { Device, deviceSchema } from './device.js';
import {
  HistoryAttributeValue,
  historyAttributeValueSchema,
} from './historyAttributeValue.js';

/** History data for a selected device and its attributes at a specific time. */
export interface History {
  /** The name of the billing account for which you want retrieve history data. An account name is usually numeric, and must include any leading zeros. */
  accountName: string;
  /** Identifies a particular IoT device. */
  device: Device;
  /** Streaming RF parameter for which you want to retrieve history data. */
  attributes?: HistoryAttributeValue;
}

export const historySchema: Schema<History> = lazy(() =>
  object({
    accountName: ['accountName', string()],
    device: ['device', deviceSchema],
    attributes: ['attributes', optional(historyAttributeValueSchema)],
  })
);
