/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { HplDeviceId, hplDeviceIdSchema } from './hplDeviceId.js';

/** A list of device IDs */
export interface HplAccountDeviceList {
  deviceIds?: HplDeviceId[];
}

export const hplAccountDeviceListSchema: Schema<HplAccountDeviceList> = lazy(
  () => object({ deviceIds: ['deviceIds', optional(array(hplDeviceIdSchema))] })
);
