/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import {
  HplAccountDeviceList,
  hplAccountDeviceListSchema,
} from './hplAccountDeviceList.js';
import { HplCustomFields, hplCustomFieldsSchema } from './hplCustomFields.js';

/** Request to add the devices. */
export interface HplAddDevicesRequest {
  /** The initial service state for the devices. The only valid state is "Preactive." */
  state?: string;
  /** The devices that you want to add. */
  devicesToAdd?: HplAccountDeviceList[];
  /** The numeric name of the account and must include leading zeroes. */
  accountName?: string;
  /** The names and values for any custom fields that you want set for the devices as they are added to the account. */
  customFields?: HplCustomFields[];
  /** The name of a device group to add the devices to. They are added to the default device group if you don't include this parameter. */
  groupName?: string;
  /** The Stock Keeping Unit (SKU) number of a 4G device type with an embedded SIM. */
  skuNumber?: string;
  /** The Subscription Manager Secure Router Object ID, used for remote SIM provisioning. SMSR securely routes the download and management of eSIM profiles. */
  smsrOid?: string;
  /** numberOfVirtualImei. */
  numberOfVirtualImei?: number;
  /** uploadType. */
  uploadType?: string;
}

export const hplAddDevicesRequestSchema: Schema<HplAddDevicesRequest> = lazy(
  () =>
    object({
      state: ['state', optional(string())],
      devicesToAdd: [
        'devicesToAdd',
        optional(array(hplAccountDeviceListSchema)),
      ],
      accountName: ['accountName', optional(string())],
      customFields: ['customFields', optional(array(hplCustomFieldsSchema))],
      groupName: ['groupName', optional(string())],
      skuNumber: ['skuNumber', optional(string())],
      smsrOid: ['smsrOid', optional(string())],
      numberOfVirtualImei: ['numberOfVirtualImei', optional(number())],
      uploadType: ['uploadType', optional(string())],
    })
);
