/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema.js';

/** A flag that shows if Hyper Precise is enabled (true) or disabled (false). */
export interface HplBullseyeEnable {
  bullseyeEnable?: boolean;
}

export const hplBullseyeEnableSchema: Schema<HplBullseyeEnable> = object({
  bullseyeEnable: ['BullseyeEnable', optional(boolean())],
});
