/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema.js';
import { Type12Enum, type12EnumSchema } from './type12Enum.js';

/** Indicates the surface of the roadway is ice. */
export interface Ice {
  /** Indicates the type of ice. */
  type?: Type12Enum;
}

export const iceSchema: Schema<Ice> = object({
  type: ['type', optional(type12EnumSchema)],
});
