/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema.js';

export interface IPPoolforplanner {
  isDefaultPool?: boolean;
  poolName?: string;
  poolType?: string;
}

export const iPPoolforplannerSchema: Schema<IPPoolforplanner> = object({
  isDefaultPool: ['isDefaultPool', optional(boolean())],
  poolName: ['poolName', optional(string())],
  poolType: ['poolType', optional(string())],
});
