/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema.js';
import { ITISItemContent, iTISItemContentSchema } from './iTISItemContent.js';

/** A wrapper carrying an ITIS code item. */
export interface ITISItemWrapper {
  /** An item object wrapping an ITIS code value. */
  item: ITISItemContent;
}

export const iTISItemWrapperSchema: Schema<ITISItemWrapper> = lazy(() =>
  object({ item: ['item', iTISItemContentSchema] })
);
