/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface KvPairforplanner {
  key?: string;
  value?: string;
}

export const kvPairforplannerSchema: Schema<KvPairforplanner> = object({
  key: ['key', optional(string())],
  value: ['value', optional(string())],
});
