/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import {
  LabelsListDeviceIds,
  labelsListDeviceIdsSchema,
} from './containers/labelsListDeviceIds.js';

export interface LabelsList {
  deviceIds?: LabelsListDeviceIds[];
}

export const labelsListSchema: Schema<LabelsList> = lazy(() =>
  object({
    deviceIds: ['deviceIds', optional(array(labelsListDeviceIdsSchema))],
  })
);
