/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import { LicenseDeviceId, licenseDeviceIdSchema } from './licenseDeviceId.js';

/** List of all devices. */
export interface LicenseDeviceList {
  /** For 4G devices, IMEI (decimal, up to 15 digits). */
  deviceIds?: LicenseDeviceId[];
  ipaddress?: string;
}

export const licenseDeviceListSchema: Schema<LicenseDeviceList> = lazy(() =>
  object({
    deviceIds: ['deviceIds', optional(array(licenseDeviceIdSchema))],
    ipaddress: ['ipAddress', optional(string())],
  })
);
