/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { AddressItem, addressItemSchema } from './addressItem.js';

/** Location details. */
export interface Locations {
  addressList?: AddressItem[];
}

export const locationsSchema: Schema<Locations> = lazy(() =>
  object({ addressList: ['addressList', optional(array(addressItemSchema))] })
);
