/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { Coordinates, coordinatesSchema } from './coordinates.js';

/** Location coordinates. */
export interface Locationscoord {
  coordinatesList?: Coordinates[];
}

export const locationscoordSchema: Schema<Locationscoord> = lazy(() =>
  object({
    coordinatesList: ['coordinatesList', optional(array(coordinatesSchema))],
  })
);
