/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import { PositionData, positionDataSchema } from './positionData.js';
import { PositionError, positionErrorSchema } from './positionError.js';

/** Device location information. */
export interface Location {
  /** MDN. */
  msid?: string;
  /** Position data. */
  pd?: PositionData;
  /** Position error. */
  error?: PositionError;
}

export const locationSchema: Schema<Location> = lazy(() =>
  object({
    msid: ['msid', optional(string())],
    pd: ['pd', optional(positionDataSchema)],
    error: ['error', optional(positionErrorSchema)],
  })
);
