/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import { Locations1, locations1Schema } from './locations1.js';
import {
  NetworkTypeObject,
  networkTypeObjectSchema,
} from './networkTypeObject.js';

export interface M2mV1IntelligenceWirelessCoverageRequest {
  /** Account name. */
  accountName?: string;
  /** Type of request made. FWA for address qualification and NW for Nationwide coverage. */
  requestType?: string;
  /** Type of location detail. */
  locationType?: string;
  locations?: Locations1;
  networkTypesList?: NetworkTypeObject[];
}

export const m2mV1IntelligenceWirelessCoverageRequestSchema: Schema<M2mV1IntelligenceWirelessCoverageRequest> = lazy(
  () =>
    object({
      accountName: ['accountName', optional(string())],
      requestType: ['requestType', optional(string())],
      locationType: ['locationType', optional(string())],
      locations: ['locations', optional(locations1Schema)],
      networkTypesList: [
        'networkTypesList',
        optional(array(networkTypeObjectSchema)),
      ],
    })
);
