/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import {
  M5gBiaccountNameobjectCustomFields,
  m5gBiaccountNameobjectCustomFieldsSchema,
} from './containers/m5gBiaccountNameobjectCustomFields.js';
import {
  M5gBiaccountNameobjectDeviceIds,
  m5gBiaccountNameobjectDeviceIdsSchema,
} from './containers/m5gBiaccountNameobjectDeviceIds.js';
import {
  M5gBiaccountNameobjectExtendedAttributes,
  m5gBiaccountNameobjectExtendedAttributesSchema,
} from './containers/m5gBiaccountNameobjectExtendedAttributes.js';
import { GroupName, groupNameSchema } from './groupName.js';
import {
  M5gBiCarrierInformation,
  m5gBiCarrierInformationSchema,
} from './m5gBiCarrierInformation.js';

export interface M5gBiaccountNameobject {
  accountName?: string;
  billingCycleEndDate?: string;
  carrierInformation?: M5gBiCarrierInformation[];
  connected?: boolean;
  createdAt?: string;
  customFields?: M5gBiaccountNameobjectCustomFields[];
  deviceIds?: M5gBiaccountNameobjectDeviceIds[];
  extendedAttributes?: M5gBiaccountNameobjectExtendedAttributes[];
  groupNames?: GroupName[];
  ipaddress?: string;
  lastActivationBy?: string;
  lastActivationDate?: string;
}

export const m5gBiaccountNameobjectSchema: Schema<M5gBiaccountNameobject> = lazy(
  () =>
    object({
      accountName: ['accountName', optional(string())],
      billingCycleEndDate: ['billingCycleEndDate', optional(string())],
      carrierInformation: [
        'carrierInformation',
        optional(array(m5gBiCarrierInformationSchema)),
      ],
      connected: ['connected', optional(boolean())],
      createdAt: ['createdAt', optional(string())],
      customFields: [
        'customFields',
        optional(array(m5gBiaccountNameobjectCustomFieldsSchema)),
      ],
      deviceIds: [
        'deviceIds',
        optional(array(m5gBiaccountNameobjectDeviceIdsSchema)),
      ],
      extendedAttributes: [
        'extendedAttributes',
        optional(array(m5gBiaccountNameobjectExtendedAttributesSchema)),
      ],
      groupNames: ['groupNames', optional(array(groupNameSchema))],
      ipaddress: ['ipAddress', optional(string())],
      lastActivationBy: ['lastActivationBy', optional(string())],
      lastActivationDate: ['lastActivationDate', optional(string())],
    })
);
