/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import {
  M5gBichangeRequestDeviceListWithServiceAddress,
  m5gBichangeRequestDeviceListWithServiceAddressSchema,
} from './containers/m5gBichangeRequestDeviceListWithServiceAddress.js';

export interface M5gBichangeRequest {
  accountName?: string;
  servicePlan?: string;
  deviceListWithServiceAddress?: M5gBichangeRequestDeviceListWithServiceAddress[];
  currentServicePlan?: string;
}

export const m5gBichangeRequestSchema: Schema<M5gBichangeRequest> = lazy(() =>
  object({
    accountName: ['accountName', optional(string())],
    servicePlan: ['servicePlan', optional(string())],
    deviceListWithServiceAddress: [
      'deviceListWithServiceAddress',
      optional(array(m5gBichangeRequestDeviceListWithServiceAddressSchema)),
    ],
    currentServicePlan: ['currentServicePlan', optional(string())],
  })
);
