/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import { M5gBideviceId1, m5gBideviceId1Schema } from './m5gBideviceId1.js';

export interface M5gBideviceId {
  deviceId?: M5gBideviceId1;
}

export const m5gBideviceIdSchema: Schema<M5gBideviceId> = lazy(() =>
  object({ deviceId: ['deviceId', optional(m5gBideviceId1Schema)] })
);
