/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import {
  M5gBiaddressAndcustomerinfo,
  m5gBiaddressAndcustomerinfoSchema,
} from './m5gBiaddressAndcustomerinfo.js';

export interface M5gBiaddressAndcustomerinfo2 {
  primaryPlaceofuse?: M5gBiaddressAndcustomerinfo;
}

export const m5gBiaddressAndcustomerinfo2Schema: Schema<M5gBiaddressAndcustomerinfo2> = lazy(
  () =>
    object({
      primaryPlaceofuse: [
        'primaryPlaceofuse',
        optional(m5gBiaddressAndcustomerinfoSchema),
      ],
    })
);
