/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import {
  M5gBiprimaryPlaceofuse,
  m5gBiprimaryPlaceofuseSchema,
} from './m5gBiprimaryPlaceofuse.js';

export interface M5gBiaddressAndcustomerinfo {
  primaryPlaceofuse?: M5gBiprimaryPlaceofuse;
}

export const m5gBiaddressAndcustomerinfoSchema: Schema<M5gBiaddressAndcustomerinfo> = lazy(
  () =>
    object({
      primaryPlaceofuse: [
        'primaryPlaceofuse',
        optional(m5gBiprimaryPlaceofuseSchema),
      ],
    })
);
