/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import { StatusList, statusListSchema } from './statusList.js';

export interface ManagedAccountsAddResponse {
  /** Transaction identifier */
  txId?: string;
  statusList?: StatusList[];
}

export const managedAccountsAddResponseSchema: Schema<ManagedAccountsAddResponse> = lazy(
  () =>
    object({
      txId: ['TxId', optional(string())],
      statusList: ['statusList', optional(array(statusListSchema))],
    })
);
