/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, boolean, lazy, object, optional, Schema } from '../schema.js';
import { Limits, limitsSchema } from './containers/limits.js';
import {
  DistributionSchedule,
  distributionScheduleSchema,
} from './distributionSchedule.js';
import {
  DistributionTypesEnum,
  distributionTypesEnumSchema,
} from './distributionTypesEnum.js';
import {
  EtsiAlertPayload,
  etsiAlertPayloadSchema,
} from './etsiAlertPayload.js';
import {
  RoadUserTypesEnum,
  roadUserTypesEnumSchema,
} from './roadUserTypesEnum.js';
import {
  TriggerConditionEnum,
  triggerConditionEnumSchema,
} from './triggerConditionEnum.js';

export interface Message3 {
  /**
   * Defines whether the message is private or public.
   * Private messages are published under the Vendor ID defined in the configuration and only visible to devices of selected vendors.
   * Public messages are published under the Public vendor and are visible to all the users.
   */
  isPrivate: boolean;
  /** Type of the Road User. */
  roadUserType: RoadUserTypesEnum[];
  /** Trigger conditions that define on which road user action the message will be sent. If multiple Trigger Conditions are defined any of them will trigger the message. */
  triggerConditions: TriggerConditionEnum[];
  /** List of limitations. These limitations can be used for making the trigger condition more precise by defining speed and motion direction requirements to be met before the messages are sent out. */
  limits?: Limits[];
  /** Type of the distribution. */
  distributionType?: DistributionTypesEnum[];
  /** The distribution schedule parameters for broadcast messages. */
  distributionSchedule?: DistributionSchedule;
  /** DENM (Decentralized Environmental Notification Message) payload as defined in ETSI. */
  etsiAlert: EtsiAlertPayload;
}

export const message3Schema: Schema<Message3> = lazy(() =>
  object({
    isPrivate: ['isPrivate', boolean()],
    roadUserType: ['roadUserType', array(roadUserTypesEnumSchema)],
    triggerConditions: ['triggerConditions', array(triggerConditionEnumSchema)],
    limits: ['limits', optional(array(limitsSchema))],
    distributionType: [
      'distributionType',
      optional(array(distributionTypesEnumSchema)),
    ],
    distributionSchedule: [
      'distributionSchedule',
      optional(distributionScheduleSchema),
    ],
    etsiAlert: ['etsiAlert', etsiAlertPayloadSchema],
  })
);
