/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, numberEnum } from '../schema.js';

/**
 * Enum for MessageIdEnum
 */
export enum MessageIdEnum {
  Enum1 = 1,
}

/**
 * Schema for MessageIdEnum
 */
export const messageIdEnumSchema: Schema<MessageIdEnum> = numberEnum(
  MessageIdEnum
);
