/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, number, object, Schema } from '../schema.js';
import { Type5Enum, type5EnumSchema } from './type5Enum.js';

/** A MultiPolygon is a type of geometry that represents a collection of Polygon geometries. */
export interface MultiPolygon {
  type: Type5Enum;
  coordinates: number[];
}

export const multiPolygonSchema: Schema<MultiPolygon> = object({
  type: ['type', type5EnumSchema],
  coordinates: ['coordinates', array(number())],
});
