/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, number, object, Schema } from '../schema.js';
import { Type4Enum, type4EnumSchema } from './type4Enum.js';

/** A MultiLineString is a type of geometry that represents a collection of LineString geometries. */
export interface MultiLineString {
  type: Type4Enum;
  coordinates: number[];
}

export const multiLineStringSchema: Schema<MultiLineString> = object({
  type: ['type', type4EnumSchema],
  coordinates: ['coordinates', array(number())],
});
