/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema } from '../schema.js';

/** A 64-bit node type with lat-long values expressed in standard SAE 1/10th of a microdegree. */
export interface NodeLLmD64b {
  /** The geographic longitude of an object, expressed in 1/10th integer microdegrees, as a 32-bit value, and with reference to the horizontal datum then in use. The value 1800000001 shall be used when unavailable. */
  lon: number;
  /** The geographic latitude of an object, expressed in 1/10th integer microdegrees, as a 31 bit value, and with reference to the horizontal datum then in use. The value 900000001 shall be used when unavailable. */
  lat: number;
}

export const nodeLLmD64bSchema: Schema<NodeLLmD64b> = object({
  lon: ['lon', number()],
  lat: ['lat', number()],
});
