/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema.js';
import { DeviceList, deviceListSchema } from './deviceList.js';

export interface NotificationReportRequest {
  accountName: string;
  requestType: string;
  devices: DeviceList[];
  monitorExpirationTime: string;
}

export const notificationReportRequestSchema: Schema<NotificationReportRequest> = lazy(
  () =>
    object({
      accountName: ['accountName', string()],
      requestType: ['requestType', string()],
      devices: ['devices', array(deviceListSchema)],
      monitorExpirationTime: ['monitorExpirationTime', string()],
    })
);
