/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema.js';
import {
  AttributeIdentifierEnum,
  attributeIdentifierEnumSchema,
} from './attributeIdentifierEnum.js';

/** Streaming RF parameter that you want to observe. */
export interface ObservationRequestAttribute {
  /** Attribute identifier. */
  name?: AttributeIdentifierEnum;
}

export const observationRequestAttributeSchema: Schema<ObservationRequestAttribute> = object(
  { name: ['name', optional(attributeIdentifierEnumSchema)] }
);
