/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import { Device, deviceSchema } from './device.js';
import { NumericalData, numericalDataSchema } from './numericalData.js';
import {
  ObservationRequestAttribute,
  observationRequestAttributeSchema,
} from './observationRequestAttribute.js';

/** Used to define callbacks including the device identity, the attribute names, corresponding attribute values and the date/timestamp of when the observation was made. */
export interface ObservationRequest {
  /** Account identifier in "##########-#####". */
  accountName: string;
  /** List of devices. */
  devices: Device[];
  /** Attributes are streaming RF parameters that you want to observe. */
  attributes: ObservationRequestAttribute[];
  /** Describes value and unit of time. */
  frequency?: NumericalData;
  /** Describes value and unit of time. */
  duration?: NumericalData;
}

export const observationRequestSchema: Schema<ObservationRequest> = lazy(() =>
  object({
    accountName: ['accountName', string()],
    devices: ['devices', array(deviceSchema)],
    attributes: ['attributes', array(observationRequestAttributeSchema)],
    frequency: ['frequency', optional(numericalDataSchema)],
    duration: ['duration', optional(numericalDataSchema)],
  })
);
