/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface Onboarding {
  /** the IEEE EUI64 address space used to identify a device. It is supplied by the device manufacturer */
  sensoridentifier?: string;
}

export const onboardingSchema: Schema<Onboarding> = object({
  sensoridentifier: ['sensoridentifier', optional(string())],
});
