/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

/**
 * Pagination filter containing an opaque token for fetching the next/previous page of results.
 * The page token is returned in the response headers (X-Next, X-Prev) and should be passed as-is.
 */
export interface PaginationFilter {
  /**
   * Opaque pagination token for fetching the next/previous page of results.
   * This is a encoded string. Do not parse or modify; pass it as received.
   */
  page: string;
}

export const paginationFilterSchema: Schema<PaginationFilter> = object({
  page: ['Page', string()],
});
