/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import { ActiveEnum, activeEnumSchema } from './activeEnum.js';
import {
  Notificationarray,
  notificationarraySchema,
} from './notificationarray.js';
import {
  PayAsYouGoPricePlanTrigger,
  payAsYouGoPricePlanTriggerSchema,
} from './payAsYouGoPricePlanTrigger.js';
import {
  TriggerCategoryEnum,
  triggerCategoryEnumSchema,
} from './triggerCategoryEnum.js';

export interface PayAsYouGoCreateTriggerRequest {
  /** The user defined name of the trigger */
  triggerName?: string;
  /** The Enterprise Customer Profile Database ID */
  ecpdId?: string;
  /** The type of trigger being created or modified */
  triggerCategory?: TriggerCategoryEnum;
  pricePlanTrigger?: PayAsYouGoPricePlanTrigger;
  notification?: Notificationarray;
  /** A flag to indicate of the trigger is active, true, or not, false */
  active?: ActiveEnum;
}

export const payAsYouGoCreateTriggerRequestSchema: Schema<PayAsYouGoCreateTriggerRequest> = lazy(
  () =>
    object({
      triggerName: ['triggerName', optional(string())],
      ecpdId: ['ecpdId', optional(string())],
      triggerCategory: ['triggerCategory', optional(triggerCategoryEnumSchema)],
      pricePlanTrigger: [
        'pricePlanTrigger',
        optional(payAsYouGoPricePlanTriggerSchema),
      ],
      notification: ['notification', optional(notificationarraySchema)],
      active: ['active', optional(activeEnumSchema)],
    })
);
