/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import { Actionobject, actionobjectSchema } from './actionobject.js';
import {
  PayAsYouGoPricePlanTriggerCondition,
  payAsYouGoPricePlanTriggerConditionSchema,
} from './containers/payAsYouGoPricePlanTriggerCondition.js';
import {
  PayAsYouGoFilterCriteria,
  payAsYouGoFilterCriteriaSchema,
} from './payAsYouGoFilterCriteria.js';

export interface PayAsYouGoPricePlanTrigger {
  payAsYouGo?: PayAsYouGoFilterCriteria;
  condition?: PayAsYouGoPricePlanTriggerCondition;
  action?: Actionobject;
}

export const payAsYouGoPricePlanTriggerSchema: Schema<PayAsYouGoPricePlanTrigger> = lazy(
  () =>
    object({
      payAsYouGo: ['payAsYouGo', optional(payAsYouGoFilterCriteriaSchema)],
      condition: [
        'condition',
        optional(payAsYouGoPricePlanTriggerConditionSchema),
      ],
      action: ['action', optional(actionobjectSchema)],
    })
);
