/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema.js';

export interface PayAsYouGoFilterCriteria1 {
  carrierServicePlanCode?: string;
  /** An array of account names */
  accountNameList?: string[];
}

export const payAsYouGoFilterCriteria1Schema: Schema<PayAsYouGoFilterCriteria1> = object(
  {
    carrierServicePlanCode: ['carrierServicePlanCode', optional(string())],
    accountNameList: ['accountNameList', optional(array(string()))],
  }
);
