/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import {
  PayAsYouGoFilterCriteria1,
  payAsYouGoFilterCriteria1Schema,
} from './payAsYouGoFilterCriteria1.js';

export interface PayAsYouGoFilterCriteria {
  filterCriteria?: PayAsYouGoFilterCriteria1;
}

export const payAsYouGoFilterCriteriaSchema: Schema<PayAsYouGoFilterCriteria> = lazy(
  () =>
    object({
      filterCriteria: [
        'filterCriteria',
        optional(payAsYouGoFilterCriteria1Schema),
      ],
    })
);
