/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, number, object, Schema } from '../schema.js';
import { Type3Enum, type3EnumSchema } from './type3Enum.js';

/**
 * A Polygon is a type of geometry that represents a collection of points that form a closed ring.
 * NOTE: This API only supports a single polygon in the Polygon geometry, so holes cannot be defines at this point. Support for hole will be added in future releases.
 */
export interface Polygon {
  type: Type3Enum;
  coordinates: number[];
}

export const polygonSchema: Schema<Polygon> = object({
  type: ['type', type3EnumSchema],
  coordinates: ['coordinates', array(number())],
});
