/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, lazy, object, optional, Schema } from '../schema.js';
import {
  AccountShareFilterCriteria,
  accountShareFilterCriteriaSchema,
} from './accountShareFilterCriteria.js';
import { Actionobject, actionobjectSchema } from './actionobject.js';
import {
  ChangePlanDetails,
  changePlanDetailsSchema,
} from './changePlanDetails.js';
import {
  PricePlanTrigger2Condition,
  pricePlanTrigger2ConditionSchema,
} from './containers/pricePlanTrigger2Condition.js';
import {
  FiltercriteriaObjectCall,
  filtercriteriaObjectCallSchema,
} from './filtercriteriaObjectCall.js';
import {
  PayAsYouGoFilterCriteria,
  payAsYouGoFilterCriteriaSchema,
} from './payAsYouGoFilterCriteria.js';

export interface PricePlanTrigger2 {
  accountShare?: AccountShareFilterCriteria;
  condition?: PricePlanTrigger2Condition;
  /** a flag to set if the trigger changes service plans, true, or not, false */
  changePlan?: boolean;
  /** The service plan code to switch to */
  changePlanDetails?: ChangePlanDetails;
  payAsYouGo?: PayAsYouGoFilterCriteria;
  action?: Actionobject;
  standAlone?: FiltercriteriaObjectCall;
}

export const pricePlanTrigger2Schema: Schema<PricePlanTrigger2> = lazy(() =>
  object({
    accountShare: ['accountShare', optional(accountShareFilterCriteriaSchema)],
    condition: ['condition', optional(pricePlanTrigger2ConditionSchema)],
    changePlan: ['changePlan', optional(boolean())],
    changePlanDetails: ['changePlanDetails', optional(changePlanDetailsSchema)],
    payAsYouGo: ['payAsYouGo', optional(payAsYouGoFilterCriteriaSchema)],
    action: ['action', optional(actionobjectSchema)],
    standAlone: ['standAlone', optional(filtercriteriaObjectCallSchema)],
  })
);
