/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, string } from '../schema.js';

export interface PrivateNetworkApns {
  /** the Access Point Name */
  apnName?: string | null;
  /** The method used for address assignment. */
  addressAssignmentMethod?: string | null;
  /** A IPv4 address */
  ipaddress?: string | null;
}

export const privateNetworkApnsSchema: Schema<PrivateNetworkApns> = object({
  apnName: ['apnName', optional(nullable(string()))],
  addressAssignmentMethod: [
    'addressAssignmentMethod',
    optional(nullable(string())),
  ],
  ipaddress: ['ipAddress', optional(nullable(string()))],
});
