/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { DeviceList2, deviceList2Schema } from './deviceList2.js';

export interface ProfileRequest2 {
  devices?: DeviceList2[];
  accountName?: string;
  carrierName?: string;
  reasonCode?: string;
  etfWaiver?: boolean;
  checkFallbackProfile?: boolean;
}

export const profileRequest2Schema: Schema<ProfileRequest2> = lazy(() =>
  object({
    devices: ['devices', optional(array(deviceList2Schema))],
    accountName: ['accountName', optional(string())],
    carrierName: ['carrierName', optional(string())],
    reasonCode: ['reasonCode', optional(string())],
    etfWaiver: ['etfWaiver', optional(boolean())],
    checkFallbackProfile: ['checkFallbackProfile', optional(boolean())],
  })
);
