/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  object,
  optional,
  Schema,
  unknown,
} from '../schema.js';
import { Keyschunk2, keyschunk2Schema } from './keyschunk2.js';

export interface PromoAlert1 {
  filterCriteria?: unknown[];
  condition?: Keyschunk2[];
  enablePromoExp?: boolean;
}

export const promoAlert1Schema: Schema<PromoAlert1> = lazy(() =>
  object({
    filterCriteria: ['filterCriteria', optional(array(unknown()))],
    condition: ['condition', optional(array(keyschunk2Schema))],
    enablePromoExp: ['enablePromoExp', optional(boolean())],
  })
);
