/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, numberEnum } from '../schema.js';

/**
 * Enum for ProtocolVersionEnum
 */
export enum ProtocolVersionEnum {
  Enum2 = 2,
}

/**
 * Schema for ProtocolVersionEnum
 */
export const protocolVersionEnumSchema: Schema<ProtocolVersionEnum> = numberEnum(
  ProtocolVersionEnum
);
