/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import { FlowInfo, flowInfoSchema } from './flowInfo.js';
import { QosDeviceId, qosDeviceIdSchema } from './qosDeviceId.js';

export interface QosDeviceInfo {
  deviceId: QosDeviceId;
  deviceIPv6Addr?: string;
  flowInfo: FlowInfo[];
}

export const qosDeviceInfoSchema: Schema<QosDeviceInfo> = lazy(() =>
  object({
    deviceId: ['deviceId', qosDeviceIdSchema],
    deviceIPv6Addr: ['deviceIPv6Addr', optional(string())],
    flowInfo: ['flowInfo', array(flowInfoSchema)],
  })
);
