/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, optional, Schema } from '../schema.js';
import { ModeEnum, modeEnumSchema } from './modeEnum.js';
import {
  PeriodicReporting,
  periodicReportingSchema,
} from './periodicReporting.js';
import { Tscore, tscoreSchema } from './tscore.js';

export interface RbsHighPrecisionTiltConfig {
  /** the reporting mode of the tilt sensor */
  mode?: ModeEnum;
  /** The units and values of the time interval for the sensor to send a report */
  periodicReporting?: PeriodicReporting;
  /** The time the threshold condition exists, in milliseconds, to recognize an event */
  holdTime?: number;
  /** the threshold value, from verticle, to recognize an event */
  angleAway?: number;
  /** the threshold value, moving towards  verticle, to recognize an event */
  angleToward?: number;
  tscore?: Tscore;
}

export const rbsHighPrecisionTiltConfigSchema: Schema<RbsHighPrecisionTiltConfig> = lazy(
  () =>
    object({
      mode: ['mode', optional(modeEnumSchema)],
      periodicReporting: [
        'periodic-reporting',
        optional(periodicReportingSchema),
      ],
      holdTime: ['hold-time', optional(number())],
      angleAway: ['angle-away', optional(number())],
      angleToward: ['angle-toward', optional(number())],
      tscore: ['tscore', optional(tscoreSchema)],
    })
);
