/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import {
  RbsHighPrecisionTiltConfig,
  rbsHighPrecisionTiltConfigSchema,
} from './rbsHighPrecisionTiltConfig.js';

export interface Rbstiltconfig {
  rbsHighPrecisionTiltConfig?: RbsHighPrecisionTiltConfig;
}

export const rbstiltconfigSchema: Schema<Rbstiltconfig> = lazy(() =>
  object({
    rbsHighPrecisionTiltConfig: [
      'RbsHighPrecisionTiltConfig',
      optional(rbsHighPrecisionTiltConfigSchema),
    ],
  })
);
