/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema.js';

/** Specific region and intersection identification pair */
export interface RegionIntersectionPair {
  /** The region identifier code (0-65535) */
  regionId?: number;
  /** The intersection identifier code (0-65535) */
  intersectionId: number;
}

export const regionIntersectionPairSchema: Schema<RegionIntersectionPair> = object(
  {
    regionId: ['regionId', optional(number())],
    intersectionId: ['intersectionId', number()],
  }
);
