/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import { PromoAlert1, promoAlert1Schema } from './promoAlert1.js';

export interface RequestTrigger {
  triggerId?: string;
  triggerName?: string;
  accountName?: string;
  organizationName?: string;
  triggerCategory?: string;
  promoAlerts?: PromoAlert1[];
}

export const requestTriggerSchema: Schema<RequestTrigger> = lazy(() =>
  object({
    triggerId: ['triggerId', optional(string())],
    triggerName: ['triggerName', optional(string())],
    accountName: ['accountName', optional(string())],
    organizationName: ['organizationName', optional(string())],
    triggerCategory: ['triggerCategory', optional(string())],
    promoAlerts: ['promoAlerts', optional(array(promoAlert1Schema))],
  })
);
