/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import {
  ReadySimDeviceId,
  readySimDeviceIdSchema,
} from './readySimDeviceId.js';

export interface RequestBodyForUsage {
  accountId?: string;
  deviceId?: ReadySimDeviceId[];
  startTime?: string;
  endTime?: string;
}

export const requestBodyForUsageSchema: Schema<RequestBodyForUsage> = lazy(() =>
  object({
    accountId: ['accountId', optional(string())],
    deviceId: ['deviceId', optional(array(readySimDeviceIdSchema))],
    startTime: ['startTime', optional(string())],
    endTime: ['endTime', optional(string())],
  })
);
