/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import {
  Devicepropertyfilter,
  devicepropertyfilterSchema,
} from './devicepropertyfilter.js';

export interface ResourceResourceQuery {
  filter?: Devicepropertyfilter;
}

export const resourceResourceQuerySchema: Schema<ResourceResourceQuery> = lazy(
  () => object({ filter: ['filter', optional(devicepropertyfilterSchema)] })
);
