/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, boolean, lazy, object, optional, Schema } from '../schema.js';
import {
  ReadySimDeviceId,
  readySimDeviceIdSchema,
} from './readySimDeviceId.js';
import { UsageHistory, usageHistorySchema } from './usageHistory.js';

export interface ResponseToUsageQuery {
  hasmoredata?: boolean;
  deviceId?: ReadySimDeviceId;
  usageHistory?: UsageHistory[];
}

export const responseToUsageQuerySchema: Schema<ResponseToUsageQuery> = lazy(
  () =>
    object({
      hasmoredata: ['hasmoredata', optional(boolean())],
      deviceId: ['deviceId', optional(readySimDeviceIdSchema)],
      usageHistory: ['usageHistory', optional(array(usageHistorySchema))],
    })
);
