/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface RetrieveResponseItem {
  imei?: string;
  /** Present if credentials exist */
  username?: string;
  /** Present if retrieval failed */
  failure?: string;
}

export const retrieveResponseItemSchema: Schema<RetrieveResponseItem> = object({
  imei: ['imei', optional(string())],
  username: ['username', optional(string())],
  failure: ['failure', optional(string())],
});
