/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import {
  RetrieveResponseItem,
  retrieveResponseItemSchema,
} from './retrieveResponseItem.js';

export interface RetrieveResponse {
  items?: RetrieveResponseItem[];
}

export const retrieveResponseSchema: Schema<RetrieveResponse> = lazy(() =>
  object({ items: ['items', optional(array(retrieveResponseItemSchema))] })
);
