/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import {
  RetrievesAvailableFilesResponse,
  retrievesAvailableFilesResponseSchema,
} from './retrievesAvailableFilesResponse.js';

export interface RetrievesAvailableFilesResponseList {
  availableFilesResponse?: RetrievesAvailableFilesResponse[];
}

export const retrievesAvailableFilesResponseListSchema: Schema<RetrievesAvailableFilesResponseList> = lazy(
  () =>
    object({
      availableFilesResponse: [
        'AvailableFilesResponse',
        optional(array(retrievesAvailableFilesResponseSchema)),
      ],
    })
);
