/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema.js';
import { RoadSignID, roadSignIDSchema } from './roadSignID.js';

/** Message ID referencing a road sign location. */
export interface RoadSignMsgId {
  /** It provide a precise location of one or more roadside signs. */
  roadSignID: RoadSignID;
}

export const roadSignMsgIdSchema: Schema<RoadSignMsgId> = lazy(() =>
  object({ roadSignID: ['roadSignID', roadSignIDSchema] })
);
