/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema.js';
import {
  RoadSignPosition,
  roadSignPositionSchema,
} from './roadSignPosition.js';

/** It provide a precise location of one or more roadside signs. */
export interface RoadSignID {
  /** Precise location of a road sign in the WGS-84 coordinate system, from which short offsets may be used to create additional data using a flat earth projection centered on this location. */
  position: RoadSignPosition;
  /** OctetStrings are described as hexadecimal strings, where each octet is represented by two hexadecimal characters. */
  viewAngle: string;
}

export const roadSignIDSchema: Schema<RoadSignID> = lazy(() =>
  object({
    position: ['position', roadSignPositionSchema],
    viewAngle: ['viewAngle', string()],
  })
);
