/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema.js';
import { Type11Enum, type11EnumSchema } from './type11Enum.js';

/** Indicates the surface of the roadway is rock. */
export interface Rock {
  /** Indicates the type of rock. */
  type?: Type11Enum;
}

export const rockSchema: Schema<Rock> = object({
  type: ['type', optional(type11EnumSchema)],
});
