/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema.js';
import { SaeInfoPayload, saeInfoPayloadSchema } from './saeInfoPayload.js';

/** Traveler Information Message (TIM) message and its mandatory fields. The traveler information message is used to send various types of information (advisory and road sign types) to equipped devices. */
export interface SaeInfoMessage {
  /** Traveler Information Message (TIM) payload as defined in SAE J2735. */
  saeInfo: SaeInfoPayload;
}

export const saeInfoMessageSchema: Schema<SaeInfoMessage> = lazy(() =>
  object({ saeInfo: ['saeInfo', saeInfoPayloadSchema] })
);
