/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { DataFrame, dataFrameSchema } from './dataFrame.js';

/** Traveler Information Message (TIM) payload as defined in SAE J2735. */
export interface SaeInfoPayload {
  /** It is used to provide a sequence number within a stream of messages with the same DSRCmsgID (here RoadSideAlert) and from the same sender. */
  msgCnt?: number;
  /**
   * The number of elapsed minutes of the current year in the time system being used (typically UTC time).
   * -- the value 527040 shall be used for invalid
   */
  timeStamp?: number;
  /**
   * Provides a relatively unique value which can be used to connect to (link to) other supporting messages in other formats.
   * The value is described as a 18-character hexadecimal string.
   */
  packetID?: string;
  /**
   * A valid internet style URI/URL in the form of a text string which will form the base of a compound string which, when
   * combined with the URL-short data element, will link to the designated resource.
   */
  urlB?: string;
  /** List of data frames. */
  dataFrames: DataFrame[];
}

export const saeInfoPayloadSchema: Schema<SaeInfoPayload> = lazy(() =>
  object({
    msgCnt: ['msgCnt', optional(number())],
    timeStamp: ['timeStamp', optional(number())],
    packetID: ['packetID', optional(string())],
    urlB: ['urlB', optional(string())],
    dataFrames: ['dataFrames', array(dataFrameSchema)],
  })
);
