/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import {
  DownloadTimeWindow,
  downloadTimeWindowSchema,
} from './downloadTimeWindow.js';

export interface SchedulesSoftwareUpgradeRequest {
  /** The campaign name. */
  campaignName?: string;
  /** Software name. */
  softwareName?: string;
  /** Old software name. */
  softwareFrom?: string;
  /** New software name. */
  softwareTo?: string;
  /** Valid values */
  distributionType?: string;
  /** Campaign start date. */
  startDate?: string;
  /** Campaign end date. */
  endDate?: string;
  /** Specifies the starting date the client should download the package. If null, client downloads as soon as possible. */
  downloadAfterDate?: string;
  /** List of allowed download time windows. */
  downloadTimeWindowList?: DownloadTimeWindow[];
  /** The date after which you install the package. If null, install as soon as possible. */
  installAfterDate?: string;
  /** List of allowed install time windows. */
  installTimeWindowList?: DownloadTimeWindow[];
  /** Device IMEI list. */
  deviceList?: string[];
}

export const schedulesSoftwareUpgradeRequestSchema: Schema<SchedulesSoftwareUpgradeRequest> = lazy(
  () =>
    object({
      campaignName: ['campaignName', optional(string())],
      softwareName: ['softwareName', optional(string())],
      softwareFrom: ['softwareFrom', optional(string())],
      softwareTo: ['softwareTo', optional(string())],
      distributionType: ['distributionType', optional(string())],
      startDate: ['startDate', optional(string())],
      endDate: ['endDate', optional(string())],
      downloadAfterDate: ['downloadAfterDate', optional(string())],
      downloadTimeWindowList: [
        'downloadTimeWindowList',
        optional(array(downloadTimeWindowSchema)),
      ],
      installAfterDate: ['installAfterDate', optional(string())],
      installTimeWindowList: [
        'installTimeWindowList',
        optional(array(downloadTimeWindowSchema)),
      ],
      deviceList: ['deviceList', optional(array(string()))],
    })
);
