/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, number, object, optional, Schema, unknown } from '../schema.js';

/** Property objects for Bluetooth Low-Energy (BLE) devices */
export interface SensorInsightsBLE {
  /** The data mode the sensor is using */
  dataMode?: number;
  /** The numeric manufacturer ID */
  manufacturerId?: number;
  /** How frequently the device can be scanned */
  maxNumScan?: number;
  /** The minimum signal strength needed for the sensor to transmit (in Decibels or dB) */
  minSigStr?: number;
  /** The ammount of time to monitor the sensor and varies by device */
  monitorPeriod?: number;
  /** Values for the manufacturer and these vary by device */
  moreManufId?: unknown[];
  /** The operation mode */
  opMode?: number;
  /** The ammount of time between sensor readings and reports */
  reportOffset?: number;
  /** The ammount of time between reports */
  reportPeriod?: number;
  /** The report type */
  reportType?: number;
  /** The ammount of time the sensor is queried for data */
  scanDuration?: number;
}

export const sensorInsightsBLESchema: Schema<SensorInsightsBLE> = object({
  dataMode: ['dataMode', optional(number())],
  manufacturerId: ['manufacturerId', optional(number())],
  maxNumScan: ['maxNumScan', optional(number())],
  minSigStr: ['minSigStr', optional(number())],
  monitorPeriod: ['monitorPeriod', optional(number())],
  moreManufId: ['moreManufId', optional(array(unknown()))],
  opMode: ['opMode', optional(number())],
  reportOffset: ['reportOffset', optional(number())],
  reportPeriod: ['reportPeriod', optional(number())],
  reportType: ['reportType', optional(number())],
  scanDuration: ['scanDuration', optional(number())],
});
