/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import {
  DtoOffBoardSensor,
  dtoOffBoardSensorSchema,
} from './dtoOffBoardSensor.js';

/** The configuration of the remove request */
export interface Sensorinsightsconfig {
  /** The EUI64 address of the device being removed */
  removesensor?: DtoOffBoardSensor;
}

export const sensorinsightsconfigSchema: Schema<Sensorinsightsconfig> = lazy(
  () =>
    object({
      removesensor: ['removesensor', optional(dtoOffBoardSensorSchema)],
    })
);
