/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import {
  KvPairforplanner,
  kvPairforplannerSchema,
} from './kvPairforplanner.js';

export interface ServicePlanResponseforplanner {
  /** The name of the service plan code */
  carrierServicePlanCode?: string;
  /** The actiavtion code value. */
  code?: string;
  /** key/value pairs assigned by the user for filtering. */
  extendedAttributes?: KvPairforplanner[];
  /** The carrier name of the active profile. */
  name?: string;
  /** size in Kilobytes of the service plan */
  sizeKb?: number;
}

export const servicePlanResponseforplannerSchema: Schema<ServicePlanResponseforplanner> = lazy(
  () =>
    object({
      carrierServicePlanCode: ['carrierServicePlanCode', optional(string())],
      code: ['code', optional(string())],
      extendedAttributes: [
        'extendedAttributes',
        optional(array(kvPairforplannerSchema)),
      ],
      name: ['name', optional(string())],
      sizeKb: ['sizeKb', optional(number())],
    })
);
