/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema.js';
import {
  TextPhraseOrITIS,
  textPhraseOrITISSchema,
} from './containers/textPhraseOrITIS.js';

/** DataFrame content variant carrying speed limit information. */
export interface SpeedLimitContent {
  /** List of speed limits and cautions. */
  speedLimit: TextPhraseOrITIS[];
}

export const speedLimitContentSchema: Schema<SpeedLimitContent> = lazy(() =>
  object({ speedLimit: ['speedLimit', array(textPhraseOrITISSchema)] })
);
