/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, nullable, object, Schema } from '../schema.js';
import { SpeedRange, speedRangeSchema } from './speedRange.js';

/**
 * Defines the acceptable speed range for road users in m/s. Messages are triggered when:
 *     1. The road user's speed is below the required minimum OR
 *     2. The road user's speed is above the acceptable maximum AND
 *     3. The associated TriggerConditions are met.
 * Example: For the speed range of 10-20 m/s and a TriggerCondition of 'user inside geofence', the message is sent if the user's speed is below 10 m/s or above 20 m/s while in the geofence area.
 */
export interface SpeedItem {
  /** Acceptable speed range for road users in m/s. */
  speed: SpeedRange | null;
}

export const speedItemSchema: Schema<SpeedItem> = lazy(() =>
  object({ speed: ['speed', nullable(speedRangeSchema)] })
);
