/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema } from '../schema.js';

/** Acceptable speed range for road users in m/s. */
export interface SpeedRange {
  /** The minimum required speed in m/s. */
  min: number;
  /** The maximum acceptable speed in m/s. */
  max: number;
}

export const speedRangeSchema: Schema<SpeedRange> = object({
  min: ['min', number()],
  max: ['max', number()],
});
