/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema.js';
import { DeviceList, deviceListSchema } from './deviceList.js';

export interface StopMonitorRequest {
  accountName: string;
  devices: DeviceList[];
}

export const stopMonitorRequestSchema: Schema<StopMonitorRequest> = lazy(() =>
  object({
    accountName: ['accountName', string()],
    devices: ['devices', array(deviceListSchema)],
  })
);
