/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';
import {
  ReportStatusEnum,
  reportStatusEnumSchema,
} from './reportStatusEnum.js';

export interface SynchronousLocationRequestResult {
  /** The transaction ID of the report. */
  txid: string;
  /** Status of the report. */
  status: ReportStatusEnum;
}

export const synchronousLocationRequestResultSchema: Schema<SynchronousLocationRequestResult> = object(
  { txid: ['txid', string()], status: ['status', reportStatusEnumSchema] }
);
