/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import {
  TargetAuthenticationBody,
  targetAuthenticationBodySchema,
} from './targetAuthenticationBody.js';

/** OAuth 2 token and refresh token for TS to stream events to Target. */
export interface TargetAuthentication {
  body?: TargetAuthenticationBody;
  version?: string;
}

export const targetAuthenticationSchema: Schema<TargetAuthentication> = lazy(
  () =>
    object({
      body: ['body', optional(targetAuthenticationBodySchema)],
      version: ['version', optional(string())],
    })
);
