/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

/** An item object wrapping a text phrase value. */
export interface TextPhraseItemContent {
  /** Text phrase provides very short sections of text interspersed between the ITIS codes to create phrases. In general, this is used for expressing proper nouns, such as street names reflecting local expressions that do not appear in the ITIS tables. */
  text: string;
}

export const textPhraseItemContentSchema: Schema<TextPhraseItemContent> = object(
  { text: ['text', string()] }
);
