/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema.js';
import { TextItemContent, textItemContentSchema } from './textItemContent.js';

/** A wrapper carrying a text item. */
export interface TextItemWrapper {
  /** An item object wrapping a text value. */
  item: TextItemContent;
}

export const textItemWrapperSchema: Schema<TextItemWrapper> = lazy(() =>
  object({ item: ['item', textItemContentSchema] })
);
