/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ThresholdUnitEnum
 */
export enum ThresholdUnitEnum {
  KB = 'KB',
  MB = 'MB',
  GB = 'GB',
}

/**
 * Schema for ThresholdUnitEnum
 */
export const thresholdUnitEnumSchema: Schema<ThresholdUnitEnum> = stringEnum(
  ThresholdUnitEnum
);
