/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface TriggerResponse {
  /** The system assigned UUID of the trigger */
  triggerId?: string;
}

export const triggerResponseSchema: Schema<TriggerResponse> = object({
  triggerId: ['triggerId', optional(string())],
});
