/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import {
  TriggerNotification,
  triggerNotificationSchema,
} from './triggerNotification.js';
import {
  UsageAnomalyAttributes,
  usageAnomalyAttributesSchema,
} from './usageAnomalyAttributes.js';

/** Trigger details. */
export interface TriggerType2 {
  /** The details of the UsageAnomaly trigger. */
  anomalyattributes?: UsageAnomalyAttributes;
  /** The notification details of the trigger. */
  notification?: TriggerNotification;
}

export const triggerType2Schema: Schema<TriggerType2> = lazy(() =>
  object({
    anomalyattributes: [
      'anomalyattributes',
      optional(usageAnomalyAttributesSchema),
    ],
    notification: ['notification', optional(triggerNotificationSchema)],
  })
);
