/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import {
  TriggervalueChunk2,
  triggervalueChunk2Schema,
} from './containers/triggervalueChunk2.js';

export interface TriggerValueResponse2 {
  triggers?: TriggervalueChunk2[];
}

export const triggerValueResponse2Schema: Schema<TriggerValueResponse2> = lazy(
  () =>
    object({
      triggers: ['triggers', optional(array(triggervalueChunk2Schema))],
    })
);
