/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for TriggerCategoryEnum
 */
export enum TriggerCategoryEnum {
  AccountUsage = 'AccountUsage',
  DeviceGroupUsage = 'DeviceGroupUsage',
  PricePlanDataUsage = 'PricePlanDataUsage',
}

/**
 * Schema for TriggerCategoryEnum
 */
export const triggerCategoryEnumSchema: Schema<TriggerCategoryEnum> = stringEnum(
  TriggerCategoryEnum
);
