/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for TriggerConditionEnum
 */
export enum TriggerConditionEnum {
  Enter = 'enter',
  Leave = 'leave',
  Inside = 'inside',
  Crossing = 'crossing',
}

/**
 * Schema for TriggerConditionEnum
 */
export const triggerConditionEnumSchema: Schema<TriggerConditionEnum> = stringEnum(
  TriggerConditionEnum
);
