/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { PromoAlert, promoAlertSchema } from './promoAlert.js';

export interface Triggervalues2 {
  triggerId?: string;
  triggerName?: string;
  accountName?: string;
  organizationName?: string;
  triggerCategory?: string;
  promoAlerts?: PromoAlert[];
  active?: boolean;
  createdAt?: string;
  modifiedAt?: string;
}

export const triggervalues2Schema: Schema<Triggervalues2> = lazy(() =>
  object({
    triggerId: ['triggerId', optional(string())],
    triggerName: ['triggerName', optional(string())],
    accountName: ['accountName', optional(string())],
    organizationName: ['organizationName', optional(string())],
    triggerCategory: ['triggerCategory', optional(string())],
    promoAlerts: ['promoAlerts', optional(array(promoAlertSchema))],
    active: ['active', optional(boolean())],
    createdAt: ['createdAt', optional(string())],
    modifiedAt: ['modifiedAt', optional(string())],
  })
);
