/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import {
  AnomalyTriggerRequest,
  anomalyTriggerRequestSchema,
} from './anomalyTriggerRequest.js';
import {
  TriggerNotification,
  triggerNotificationSchema,
} from './triggerNotification.js';

/** Trigger details. */
export interface TriggerType1 {
  /** Trigger name. */
  name?: string;
  /** This is the value to use in the request body to detect anomalous behaivior. The values in this table will only be relevant when this parameter is set to this value. */
  triggerCategory?: string;
  /** Account name. */
  accountName?: string;
  /** The details of the UsageAnomaly trigger. */
  anomalyTriggerRequest?: AnomalyTriggerRequest;
  /** The notification details of the trigger. */
  notification?: TriggerNotification;
}

export const triggerType1Schema: Schema<TriggerType1> = lazy(() =>
  object({
    name: ['name', optional(string())],
    triggerCategory: ['triggerCategory', optional(string())],
    accountName: ['accountName', optional(string())],
    anomalyTriggerRequest: [
      'anomalyTriggerRequest',
      optional(anomalyTriggerRequestSchema),
    ],
    notification: ['notification', optional(triggerNotificationSchema)],
  })
);
