/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, lazy, object, optional, Schema, string } from '../schema.js';
import {
  AnomalyTriggerRequest,
  anomalyTriggerRequestSchema,
} from './anomalyTriggerRequest.js';
import { CycleTypeEnum, cycleTypeEnumSchema } from './cycleTypeEnum.js';
import {
  DataTriggerRequest,
  dataTriggerRequestSchema,
} from './dataTriggerRequest.js';
import {
  PromoAlertTriggerRequest,
  promoAlertTriggerRequestSchema,
} from './promoAlertTriggerRequest.js';
import {
  SessionTriggerRequest,
  sessionTriggerRequestSchema,
} from './sessionTriggerRequest.js';
import {
  SMSTriggerRequest,
  sMSTriggerRequestSchema,
} from './sMSTriggerRequest.js';

export interface UpdateTriggerRequest {
  accountName?: string;
  active?: boolean;
  /** The details of the UsageAnomaly trigger. */
  anomalyTriggerRequest?: AnomalyTriggerRequest;
  cycleType?: CycleTypeEnum;
  dataTriggerRequest?: DataTriggerRequest;
  groupName?: string;
  promoAlertTriggerRequest?: PromoAlertTriggerRequest;
  sessionTriggerRequest?: SessionTriggerRequest;
  smsTriggerRequest?: SMSTriggerRequest;
  triggerCategory?: string;
  triggerId?: string;
  triggerName?: string;
}

export const updateTriggerRequestSchema: Schema<UpdateTriggerRequest> = lazy(
  () =>
    object({
      accountName: ['accountName', optional(string())],
      active: ['active', optional(boolean())],
      anomalyTriggerRequest: [
        'anomalyTriggerRequest',
        optional(anomalyTriggerRequestSchema),
      ],
      cycleType: ['cycleType', optional(cycleTypeEnumSchema)],
      dataTriggerRequest: [
        'dataTriggerRequest',
        optional(dataTriggerRequestSchema),
      ],
      groupName: ['groupName', optional(string())],
      promoAlertTriggerRequest: [
        'promoAlertTriggerRequest',
        optional(promoAlertTriggerRequestSchema),
      ],
      sessionTriggerRequest: [
        'sessionTriggerRequest',
        optional(sessionTriggerRequestSchema),
      ],
      smsTriggerRequest: [
        'smsTriggerRequest',
        optional(sMSTriggerRequestSchema),
      ],
      triggerCategory: ['triggerCategory', optional(string())],
      triggerId: ['triggerId', optional(string())],
      triggerName: ['triggerName', optional(string())],
    })
);
