/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { V2AccountDevice, v2AccountDeviceSchema } from './v2AccountDevice.js';

/** List of device information for an account. */
export interface V2AccountDeviceList {
  /** Account name. */
  accountName: string;
  /** Has more device flag? */
  hasMoreData: boolean;
  /** Last seen device identifier. */
  lastSeenDeviceId?: string;
  /** Maximum page size. */
  maxPageSize: number;
  /** Account device list. */
  deviceList: V2AccountDevice[];
}

export const v2AccountDeviceListSchema: Schema<V2AccountDeviceList> = lazy(() =>
  object({
    accountName: ['accountName', string()],
    hasMoreData: ['hasMoreData', boolean()],
    lastSeenDeviceId: ['lastSeenDeviceId', optional(string())],
    maxPageSize: ['maxPageSize', number()],
    deviceList: ['deviceList', array(v2AccountDeviceSchema)],
  })
);
