/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, number, object, Schema, string } from '../schema.js';
import { V2DeviceStatus, v2DeviceStatusSchema } from './v2DeviceStatus.js';

/** License assignment or removal confirmation. */
export interface V2LicensesAssignedRemovedResult {
  /** Account name. */
  accountName: string;
  /** Total license count. */
  licTotalCount: number;
  /** Assigned license count. */
  licUsedCount: number;
  /** List of devices with id in IMEI. */
  deviceList: V2DeviceStatus[];
}

export const v2LicensesAssignedRemovedResultSchema: Schema<V2LicensesAssignedRemovedResult> = lazy(
  () =>
    object({
      accountName: ['accountName', string()],
      licTotalCount: ['licTotalCount', number()],
      licUsedCount: ['licUsedCount', number()],
      deviceList: ['deviceList', array(v2DeviceStatusSchema)],
    })
);
