/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import {
  AccountLevelActionEnum,
  accountLevelActionEnumSchema,
} from './accountLevelActionEnum.js';
import {
  AccountLevelFilter,
  accountLevelFilterSchema,
} from './accountLevelFilter.js';
import { ActiveEnum, activeEnumSchema } from './activeEnum.js';
import {
  V2TriggersRequestCondition,
  v2TriggersRequestConditionSchema,
} from './containers/v2TriggersRequestCondition.js';
import {
  V2TriggersRequestSmsNumbers,
  v2TriggersRequestSmsNumbersSchema,
} from './containers/v2TriggersRequestSmsNumbers.js';
import { DataTrigger4, dataTrigger4Schema } from './dataTrigger4.js';
import {
  Notificationarray,
  notificationarraySchema,
} from './notificationarray.js';
import {
  PricePlanTrigger1,
  pricePlanTrigger1Schema,
} from './pricePlanTrigger1.js';
import {
  TriggerCategoryEnum,
  triggerCategoryEnumSchema,
} from './triggerCategoryEnum.js';

export interface V2TriggersRequest {
  /** The user defined name of the trigger */
  triggerName?: string;
  /** The Enterprise Customer Profile Database ID */
  ecpdId?: string;
  /** The type of trigger being created or modified */
  triggerCategory?: TriggerCategoryEnum;
  dataTrigger?: DataTrigger4;
  notification?: Notificationarray;
  notificationType?: string;
  callback?: boolean;
  emailNotification?: boolean;
  notificationGroupName?: string;
  notificationFrequencyFactor?: number;
  notificationFrequencyInterval?: string;
  externalEmailRecipients?: string;
  smsNotification?: boolean;
  smsNumbers?: V2TriggersRequestSmsNumbers[];
  reminder?: boolean;
  severity?: string;
  /** A flag to indicate of the trigger is active, true, or not, false */
  active?: ActiveEnum;
  filterCriteria?: AccountLevelFilter;
  condition?: V2TriggersRequestCondition;
  /** The action taken when trigger conditions are met */
  action?: AccountLevelActionEnum;
  /** The numeric name of the account and must include leading zeroes */
  accountName?: string;
  pricePlanTrigger?: PricePlanTrigger1;
}

export const v2TriggersRequestSchema: Schema<V2TriggersRequest> = lazy(() =>
  object({
    triggerName: ['triggerName', optional(string())],
    ecpdId: ['ecpdId', optional(string())],
    triggerCategory: ['triggerCategory', optional(triggerCategoryEnumSchema)],
    dataTrigger: ['dataTrigger', optional(dataTrigger4Schema)],
    notification: ['notification', optional(notificationarraySchema)],
    notificationType: ['notificationType', optional(string())],
    callback: ['callback', optional(boolean())],
    emailNotification: ['emailNotification', optional(boolean())],
    notificationGroupName: ['notificationGroupName', optional(string())],
    notificationFrequencyFactor: [
      'notificationFrequencyFactor',
      optional(number()),
    ],
    notificationFrequencyInterval: [
      'notificationFrequencyInterval',
      optional(string()),
    ],
    externalEmailRecipients: ['externalEmailRecipients', optional(string())],
    smsNotification: ['smsNotification', optional(boolean())],
    smsNumbers: [
      'smsNumbers',
      optional(array(v2TriggersRequestSmsNumbersSchema)),
    ],
    reminder: ['reminder', optional(boolean())],
    severity: ['severity', optional(string())],
    active: ['active', optional(activeEnumSchema)],
    filterCriteria: ['filterCriteria', optional(accountLevelFilterSchema)],
    condition: ['condition', optional(v2TriggersRequestConditionSchema)],
    action: ['action', optional(accountLevelActionEnumSchema)],
    accountName: ['accountName', optional(string())],
    pricePlanTrigger: ['pricePlanTrigger', optional(pricePlanTrigger1Schema)],
  })
);
