/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { ActiveEnum, activeEnumSchema } from './activeEnum.js';
import {
  V2TriggersRequest1SmsNumbers,
  v2TriggersRequest1SmsNumbersSchema,
} from './containers/v2TriggersRequest1SmsNumbers.js';
import { DataTrigger5, dataTrigger5Schema } from './dataTrigger5.js';
import {
  Notificationarray,
  notificationarraySchema,
} from './notificationarray.js';
import {
  PricePlanTrigger2,
  pricePlanTrigger2Schema,
} from './pricePlanTrigger2.js';
import {
  TriggerCategoryEnum,
  triggerCategoryEnumSchema,
} from './triggerCategoryEnum.js';

export interface V2TriggersRequest1 {
  /** The system assigned UUID of the trigger */
  triggerId?: string;
  /** The user defined name of the trigger */
  triggerName?: string;
  /** The Enterprise Customer Profile Database ID */
  ecpdId?: string;
  /** The type of trigger being created or modified */
  triggerCategory?: TriggerCategoryEnum;
  dataTrigger?: DataTrigger5;
  notification?: Notificationarray;
  notificationType?: string;
  callback?: boolean;
  emailNotification?: boolean;
  notificationGroupName?: string;
  notificationFrequencyFactor?: number;
  notificationFrequencyInterval?: string;
  externalEmailRecipients?: string;
  smsNotification?: boolean;
  smsNumbers?: V2TriggersRequest1SmsNumbers[];
  reminder?: boolean;
  severity?: string;
  /** A flag to indicate of the trigger is active, true, or not, false */
  active?: ActiveEnum;
  /** The numeric name of the account and must include leading zeroes */
  accountName?: string;
  pricePlanTrigger?: PricePlanTrigger2;
}

export const v2TriggersRequest1Schema: Schema<V2TriggersRequest1> = lazy(() =>
  object({
    triggerId: ['triggerId', optional(string())],
    triggerName: ['triggerName', optional(string())],
    ecpdId: ['ecpdId', optional(string())],
    triggerCategory: ['triggerCategory', optional(triggerCategoryEnumSchema)],
    dataTrigger: ['dataTrigger', optional(dataTrigger5Schema)],
    notification: ['notification', optional(notificationarraySchema)],
    notificationType: ['notificationType', optional(string())],
    callback: ['callback', optional(boolean())],
    emailNotification: ['emailNotification', optional(boolean())],
    notificationGroupName: ['notificationGroupName', optional(string())],
    notificationFrequencyFactor: [
      'notificationFrequencyFactor',
      optional(number()),
    ],
    notificationFrequencyInterval: [
      'notificationFrequencyInterval',
      optional(string()),
    ],
    externalEmailRecipients: ['externalEmailRecipients', optional(string())],
    smsNotification: ['smsNotification', optional(boolean())],
    smsNumbers: [
      'smsNumbers',
      optional(array(v2TriggersRequest1SmsNumbersSchema)),
    ],
    reminder: ['reminder', optional(boolean())],
    severity: ['severity', optional(string())],
    active: ['active', optional(activeEnumSchema)],
    accountName: ['accountName', optional(string())],
    pricePlanTrigger: ['pricePlanTrigger', optional(pricePlanTrigger2Schema)],
  })
);
