/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import {
  CampaignMetaInfoProtocolEnum,
  campaignMetaInfoProtocolEnumSchema,
} from './campaignMetaInfoProtocolEnum.js';
import { V3TimeWindow, v3TimeWindowSchema } from './v3TimeWindow.js';

/** Campaign and campaign details. */
export interface V3CampaignMetaInfo {
  /** Account identifier. */
  accountName: string;
  /** Campaign identifier. */
  id: string;
  /** Campaign name. */
  campaignName?: string;
  /** Firmware name. */
  firmwareName?: string;
  /** Old firmware version. */
  firmwareFrom?: string;
  /** New software version. */
  firmwareTo?: string;
  /** Firmware protocol. Valid values include: LWM2M, OMD-DM. */
  protocol?: CampaignMetaInfoProtocolEnum;
  /** Device make. */
  make: string;
  /** Device model. */
  model: string;
  /** Campaign start date. */
  startDate: string;
  /** Campaign end date. */
  endDate: string;
  /** List of allowed campaign time windows. */
  campaignTimeWindowList?: V3TimeWindow[];
  /** Firmware upgrade status. */
  status: string;
}

export const v3CampaignMetaInfoSchema: Schema<V3CampaignMetaInfo> = lazy(() =>
  object({
    accountName: ['accountName', string()],
    id: ['id', string()],
    campaignName: ['campaignName', optional(string())],
    firmwareName: ['firmwareName', optional(string())],
    firmwareFrom: ['firmwareFrom', optional(string())],
    firmwareTo: ['firmwareTo', optional(string())],
    protocol: ['protocol', optional(campaignMetaInfoProtocolEnumSchema)],
    make: ['make', string()],
    model: ['model', string()],
    startDate: ['startDate', string()],
    endDate: ['endDate', string()],
    campaignTimeWindowList: [
      'campaignTimeWindowList',
      optional(array(v3TimeWindowSchema)),
    ],
    status: ['status', string()],
  })
);
