/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema.js';
import {
  TextPhraseOrITIS,
  textPhraseOrITISSchema,
} from './containers/textPhraseOrITIS.js';

/** DataFrame content variant carrying work zone information. */
export interface WorkZoneContent {
  /** List of work zone signs and directions. */
  workZone: TextPhraseOrITIS[];
}

export const workZoneContentSchema: Schema<WorkZoneContent> = lazy(() =>
  object({ workZone: ['workZone', array(textPhraseOrITISSchema)] })
);
