/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema } from '../schema.js';

/** Cause code wrapper for wrong way driving events. */
export interface WrongWayDrivingCauseCode {
  /**
   * The value shall be set to:
   * - 0 `unavailable`    - in case further detailed information on wrong way driving event is unavailable,
   * - 1 `wrongLane`      - in case vehicle is driving on a lane for which it has no authorization to use,
   * - 2 `wrongDirection` - in case vehicle is driving in a direction that it is not allowed,
   * - 3-255              - reserved for future usage.
   */
  wrongWayDriving14: number;
}

export const wrongWayDrivingCauseCodeSchema: Schema<WrongWayDrivingCauseCode> = object(
  { wrongWayDriving14: ['wrongWayDriving14', number()] }
);
